### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ithakaa** [benphelps/homepage#1]
.

**Comment by adamshand** [comment]
Just follow the instructions in the readme for Development.

The amount you lot complaint about what other people offer for free. 🙄

**Comment by ithakaa** [comment]
> Just follow the instructions in the readme for Development.
> 
> The amount you lot complaint about what other people offer for free. 🙄

We're not all super heroes

**Comment by benphelps** [comment]
I added more information to the readme to cover running the application locally, see [c90f781](https://github.com/benphelps/homepage/commit/c90f7816503baac0a6da376f06b6d4900224697d)

**Comment by ithakaa** [comment]
> I added more information to the readme to cover running the application locally, see [c90f781](https://github.com/benphelps/homepage/commit/c90f7816503baac0a6da376f06b6d4900224697d)

Thank you sir, it's greatly appreciated
