### ISSUE TITLE
[Bug] Color is not working on firefox

### ISSUE THREAD

**Issue by martinmartossimon** [benphelps/homepage#1000]
### Description

On chrome color scheema works fine, but now in firefox.
![imagen](https://user-images.githubusercontent.com/16241139/218837101-bc92ea43-5990-4cce-a686-1dbdc761409c.png)

Firefox version:  109.0.1 (64-bit)

### Steps to reproduce

1. Open homepage URL

### homepage version

v0.6.7 (f8a0c69, 7 feb 2023)

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by martinmartossimon** [comment]
The same configuration seen on chrome:
![imagen](https://user-images.githubusercontent.com/16241139/218837590-2b9d7e97-fb4b-47ef-a4b3-21bc8f7073f0.png)

**Comment by shamoon** [comment]
Can't reproduce this. Im willing to bet you're using some kind of extension in FF that's causing this.

<img width="1716" alt="Screenshot 2023-02-14 at 11 42 30 AM" src="https://user-images.githubusercontent.com/4887959/218841382-4e54be7d-d891-41a6-818d-55188cfe02e2.png">

**Comment by MarioNoll** [comment]
Just for anyone landing in this issue here, I resolved it by disabling FF extension https://addons.mozilla.org/en-US/firefox/addon/darkreader/.
