### ISSUE TITLE
Tautulli Bitrate Reporting Kbps instead of Mbps

### ISSUE THREAD

**Issue by phutur1st** [benphelps/homepage#101]
On 0.3.9 - seeing Kbps reported when it should be Mbps. Below is the key pair from the response.  Did not see this behavior before:

"total_bandwidth": 5876, "lan_bandwidth": 5876

and is being presented (rounded to int) as Kbps:

![image](https://user-images.githubusercontent.com/22960702/189512425-1c7c7897-af8f-408e-bfc8-98e39103ffcf.png)

apologies for the double post, after re-reading the issue i commented on initially I realized the separation.  Thanks for the efforts!

**Comment by benphelps** [comment]
Thanks for reporting, I'll get this fixed.

**Comment by noobyogi0010** [comment]
@benphelps I would like to work on this issue if no one else has taken it up.
Thanks!

**Comment by benphelps** [comment]
All of the media streaming widgets have been redesigned fully and this isn't going to be an issue in the current `main` tag.
