### ISSUE TITLE
[Bug] Date-Time widget displays time as 24:xx in 24 hour notation between 00:00 and 01:00

### ISSUE THREAD

**Issue by afentoe** [benphelps/homepage#1014]
### Description

When I use the example for 24 hour notation from 
https://gethomepage.dev/en/widgets/datetime/
time is displayed as 24:xx between 00:00 and 01:00.

```
# 13:37
format:
  timeStyle: short
  hour12: false
```

This is caused by a bug when using "hour12: false", which defaults to using the setting: hourCycle: h24.

More info and a good explanation about the issue here:
https://github.com/moment/luxon/issues/726#issuecomment-675151145

Fix is to use this config:
```
# 13:37
format:
  timeStyle: short
  hourCycle: h23
```

So if you agree with this, please update the example for 24 hour notation on:
https://gethomepage.dev/en/widgets/datetime/

### Steps to reproduce

- Use 24 hour notation from example:

```
format:
  timeStyle: short
  hour12: false
```

Set computer to a timezone where the time is between 00:00 and 01:00.

This will display time as 24:xx.

### homepage version

0.6.7

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by afentoe** [comment]
Sorry, this seems to be a duplicate of 
https://github.com/benphelps/homepage/issues/585

I think updating the example docs, will avoid this issue for future users.

**Comment by afentoe** [comment]
Hi @shamoon you closed this, but will you update the 24h example in the docs with the this?

```
# 13:37
format:
  timeStyle: short
  hourCycle: h23
```

**Comment by shamoon** [comment]
I did already thanks

**Comment by afentoe** [comment]
ah, ok thanks. It wasn't updated when I checked.
