### ISSUE TITLE
[Feature Request] ChangeDetection.io Widget

### ISSUE THREAD

**Issue by joe-heaton** [benphelps/homepage#1017]
### Description

Would be cool to add this function, could be possible with [this](https://github.com/dgtlmoon/changedetection.io#json-api-monitoring)

**Comment by Aesop7** [comment]
I think this might exist already?  https://github.com/benphelps/homepage/tree/main/src/widgets/changedetectionio

**Comment by shamoon** [comment]
Completed in #386
