### ISSUE TITLE
since updating latest release i've got "Missing Widget Type: prowlarr" 

### ISSUE THREAD

**Issue by divemasterjm** [benphelps/homepage#1034]
### Description

after update latest version widget prowlarr is not working, i've got error
Missing Widget Type: prowlarr

### Steps to reproduce

web page

### homepage version

0.6.9

### Installation method

Other (please describe above)

### Configuration

```yaml
proxmox lxc (source)
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
As you're running from source I have to assume that's the problem, no issue here:
<img width="500" alt="Screenshot 2023-02-21 at 8 13 18 AM" src="https://user-images.githubusercontent.com/4887959/220399692-0f251556-7309-495e-b333-dd7025e96fb8.png">
