### ISSUE TITLE
[Bug] jellyfin widget show bug

### ISSUE THREAD

**Issue by spupuz** [benphelps/homepage#1036]
### Description

since version 0.68 i got this error:

```
API Error: Invalid data
URL: http://192.168.1.112:8096/emby/Sessions?api_key=***
Response Data:
Error processing request.
```

![image](https://user-images.githubusercontent.com/1721792/220454680-876d044a-ac0d-412c-b450-6112252e69d2.png)

### Steps to reproduce

-

### homepage version

v0.6.9 (767fc1e, Feb 21, 2023)

### Installation method

Docker

### Configuration

```yaml
-
```

### Container Logs

-

### Browser Logs

-

### Other

-

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
No issues here. <img width="508" alt="Screenshot 2023-02-21 at 1 33 44 PM" src="https://user-images.githubusercontent.com/4887959/220463496-792b5e0d-9c39-43e8-b588-6e05c6b6762b.png">

You indicated above you performed the tasks from the troubleshooting guide, please post the output of the `ping` and `curl` calls

**Comment by spupuz** [comment]
> No issues here. <img alt="Screenshot 2023-02-21 at 1 33 44 PM" width="508" src="https://user-images.githubusercontent.com/4887959/220463496-792b5e0d-9c39-43e8-b588-6e05c6b6762b.png">
> 
> You indicated above you performed the tasks from the troubleshooting guide, please post the output of the `ping` and `curl` calls

Oh ok I'll so it tomorrow morning

**Comment by spupuz** [comment]
Ok I discovered that was a problem with Jellyfin unstable, move to stable version of Jellyfin and now is fine.
