### ISSUE TITLE
[Bug] hideVersion not working

### ISSUE THREAD

**Issue by krintek** [benphelps/homepage#1037]
### Description

![image](https://user-images.githubusercontent.com/87629857/220639344-3bbe55e5-f76d-4a9f-9f82-d0751c9a36fb.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/87629857/220639636-3c8a8137-1f34-4f94-ba8c-3e0e0e5e900f.png)

### homepage version

v0.6.9

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Sir, it hasn’t been released yet, you can use `main` tag in the meantime
