### ISSUE TITLE
[Feature Request] Minecraft server status

### ISSUE THREAD

**Issue by 21st-centuryman** [benphelps/homepage#1042]
### Description

This would be a widget that sends a request to the following URL:

https://mcapi.us/server/status?ip={IP_ADDRESS}&port={PORT}. 

This returns a json indicating if the sever is online, how many players are online and what the IP/name of the server is.

This would be similar to the smart app on the fenrus dashboard, I have a link to their code below:
https://github.com/revenz/Fenrus/tree/master/apps/Smart/Minecraft

### Other

I got quite a bit of a busy upcoming weeks, but if I find the time I could do it.

**Comment by Sairenity** [comment]
You have impecable timing... I have implemented exactly that feature as an exercise.

Would this be enough data?

![https://srnt.ch/Rl5l9B71q.png](https://srnt.ch/Rl5l9B71q.png)

**Comment by 21st-centuryman** [comment]
oh lmao I literally was just about to start working on this. Decided to check the issue just in case

I would prefer to also have a option to see whether the server is on or not, I have it on a seperate machine.
