### ISSUE TITLE
[Bug] Error: Invalid argument not valid semver ('homepage-0.1.0' received)

### ISSUE THREAD

**Issue by eanmclaughlin** [benphelps/homepage#1049]
### Description

Looks like the new release isn't a valid semver tag!

Were the github actions changed? The release published ~10 minutes ago was published by github-actions rather than a user like previous releases.

### Steps to reproduce

Load homepage; version check blows up. 

### homepage version

v0.68.0

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by milespossing** [comment]
Same bug, started just this morning

**Comment by anirudhgiran** [comment]
I am facing the same issue. Worked just fine last night

**Comment by Stuke00** [comment]
Same thing for me too, I even tried restoring a backup from a couple days ago and I still get the error.

**Comment by milespossing** [comment]
So I've just pulled down the `nightly` tag for this container and it does work. I'm going to use that for now

**Comment by anirudhgiran** [comment]
I switched to homepage:main for the time being. That's working. Will wait for this bug to be fixed

**Comment by eanmclaughlin** [comment]
Seems to be from [this commit](https://github.com/benphelps/homepage/commit/c2136e8353786d4347e5bcd6af55e6be4e1bb6ca) adding helm charts

**Comment by jammin1911** [comment]
Can someone explain how its possible that all of us are having this issue pop up at the same time when this is a self hosted product?  I did not touch or update my container.  Does this not imply that there is some sort of phone home or other externality acting on our installs of homepage?

**Comment by Robert-litts** [comment]
I am receiving the same error on my system as of this morning: Error: Invalid argument not valid semver ('homepage-0.1.0' received). Switching from homepage:latest to homepage:main solved for me, for now.

**Comment by PixelDJ** [comment]
> Can someone explain how its possible that all of us are having this issue pop up at the same time when this is a self hosted product? I did not touch or update my container. Does this not imply that there is some sort of phone home or other externality acting on our installs of homepage?

I am wondering how this works as well. I want my homepage to work as configured until I decide to update it.

**Comment by eanmclaughlin** [comment]
@jammin1911 @PixelDJ there's a built-in version check to add a small UI label to let you know if there's an update available.

**Comment by JordyEGNL** [comment]
> Can someone explain how its possible that all of us are having this issue pop up at the same time when this is a self hosted product? I did not touch or update my container. Does this not imply that there is some sort of phone home or other externality acting on our installs of homepage?

I think that the server is checking for a new version, and expects a number. For example 0.6.9. But it received homepage-0.1.0

**Comment by PixelDJ** [comment]
> @jammin1911 @PixelDJ there's a built-in version check to add a small UI label to let you know if there's an update available.

Ok yeah this makes sense. Thank you.

**Comment by eanmclaughlin** [comment]
That version checking is [done here](https://github.com/benphelps/homepage/blob/main/src/components/version.jsx) for ref. Doesn't look like there's any exposed configuration around it, but running `dev`, `nightly`, or `main` disables it by returning `null` instead of comparing versions.

**Comment by tokinwithzigg** [comment]
Also getting hit with this.

**Comment by nomandera** [comment]
Restored and working for me again with no change or restart.

**Comment by falco1717** [comment]
works for me now without a restore, just refreshed the page.

**Comment by eanmclaughlin** [comment]
Looks like the errant release was deleted, I'm guessing by @shamoon

**Comment by raclariu** [comment]
can confirm that it's working now

**Comment by nomandera** [comment]
Now that this is fixed I think it came as surprise to more than just  that there was any online component since "T_he entire site is statically generated at build time_".

I dont have an issue with this in principle but I do think this and anything else like this should be optional.

Nice work on the reports and fix.

**Comment by anirudhgiran** [comment]
`homepage:latest` is working again. Love the quick action from the community!

**Comment by eanmclaughlin** [comment]
@nomandera Well, the components are statically built. But all the data to populate them needs to come from somewhere. 

Do agree on adding configuration around this. I might see about doing that this weekend if I have time.

**Comment by Robert-litts** [comment]
`homepage:latest` working for me again as well, thanks!

**Comment by BANanaD3V** [comment]
worked for me for some time, now broke again. gonna go sleep, so idk how to help.

**Comment by nomandera** [comment]
Also broken again for me

**Comment by callbacked** [comment]
redeployed again in Docker by using latest image, but I am still getting the same issue sadly.

**Comment by eanmclaughlin** [comment]
@shamoon looks like every commit to `main` is resulting in an invalid release from the new helm chart gh action

**Comment by shamoon** [comment]
Yes, an issue with a recent PR. Ive deleted the erroneous release so should be sorted while we figure out the actions issue.

Looks like I stepped away from my computer at the wrong moment, ha. Thanks for your patience
