### ISSUE TITLE
[Feature Request] PBS (Proxmox Backup Server) Support

### ISSUE THREAD

**Issue by jbagwell27** [benphelps/homepage#1053]
### Description

I would like to see the following Server Information:  

- Datastore space used/available
- Backup count for "CT" and "VM" (Host is optional in my opinion)
- Current job count
- Disk IOPS

![image](https://user-images.githubusercontent.com/53024286/221244390-38f4cc80-6707-4795-8b62-8411e146e6c6.png)  

![image](https://user-images.githubusercontent.com/53024286/221246070-03dba8c1-2c7c-4fc1-8455-c5c1b9eec359.png)

I hope the supporting images help with the information I'm requesting.

### Other

There may be more than one datastore, so it might be necessary to call them by name, or force the APIKey to be able to access only one store at a time. They show as their own entry in the apikey permissions menu:  

![image](https://user-images.githubusercontent.com/53024286/221245656-1f16e026-438b-4db8-bb44-c1d9335798ae.png)

**Comment by shamoon** [comment]
You're saying to adjust the PBS widget? One already exists, wasn't sure if you already knew that

**Comment by jbagwell27** [comment]
I realized that the PBS widget was already there after I added this. I just
forgot to close it. 😬
