### ISSUE TITLE
[Feature Request] the cloudflare widget should not require a global API key

### ISSUE THREAD

**Issue by Cyrisub** [benphelps/homepage#1060]
### Description

as the [pull#868](https://github.com/benphelps/homepage/pull/868) get the infomation through https://api.cloudflare.com/client/v4/accounts/account-id/cfd_tunnel/tunnel-id using `X-Auth-Email` and `X-Auth-Key`, it requires user exposing the global API key to the script which has not permission limitation and also not recommended by [Cloudflare](https://developers.cloudflare.com/fundamentals/api/get-started/keys/), which has a **great safety danger**.

The tunnel state infomation can be acquired through an API token, with `Account: CloudflareTunnel: Read` permission only. Also the api can be simpler by the [Bearer Auth](https://developers.cloudflare.com/api), just use 'Authorization: Bearer <api-token>` instead of `X-Auth-Email` and `X-Auth-Key`.

The API returns are identical with before and no other code need to change i believe ^-^.  Sadly i know nothing about JavaScript so that i cannot raise a pull request...

### Steps to reproduce

null

### homepage version

v0.6.9

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Thanks for reporting this. Not exactly a bug but sounds worth changing. Hopefully will be as straightforward as you suggest but unfortunately it will be a breaking change
