### ISSUE TITLE
Text color icon abit hard to select on mobile

### ISSUE THREAD

**Issue by karmarcharger** [benphelps/homepage#107]
![image](https://media.discordapp.net/attachments/955469090812747816/1018549736178978996/IMG_0455.png?width=418&height=904)

The color selector is abit hard to interact with on mobile, not sure if this occurs only on Iphone safari only.

**Comment by benphelps** [comment]
Odd, I'll investigate.

**Comment by benphelps** [comment]
Will be fixed in the next release.

![969E29F6-6E82-475F-97AC-69BADEE24383](https://user-images.githubusercontent.com/82196/189537762-367fa233-92cd-4425-9a33-69f58fcb855d.png)
