### ISSUE TITLE
[Feature Request] Lidarr, Readarr, Prowlarr, Bazarr Widgets 

### ISSUE THREAD

**Issue by Nomlla** [benphelps/homepage#110]
I think these would be a great addition to add.

**Comment by xicopitz** [comment]
What kind of information we seek to Prowlarr widget?

- number of active indexer?
- connected applications?
- more ideas?

**Comment by Nomlla** [comment]
> What kind of information we seek to Prowlarr widget?
> 
> * number of active indexers?
> * connected applications?
> * more ideas?

Indexer errors would be useful
![indexer](https://user-images.githubusercontent.com/85586586/189742685-48268a72-63a3-4e10-9ec2-da07cc7a36b3.png)

**Comment by xicopitz** [comment]
> > What kind of information we seek to Prowlarr widget?
> > 
> > * number of active indexers?
> > * connected applications?
> > * more ideas?
> 
> Indexer errors would be useful ![indexer](https://user-images.githubusercontent.com/85586586/189742685-48268a72-63a3-4e10-9ec2-da07cc7a36b3.png)

Hi,
It was added the following stats (but can be revisited):

- Number of active Indexers 
- Number of grabs
- Number of queries
- Number of failed grabs
- Number of failed queries

**Comment by benphelps** [comment]
These have all be added, massive thanks to @JazzFisch :)
