### ISSUE TITLE
[Bug] language of date is not correct on phone 

### ISSUE THREAD

**Issue by TibiaBubble** [benphelps/homepage#1107]
### Description

![B73D0848-C834-4FB4-9B4B-909CB0CD0CAF](https://user-images.githubusercontent.com/122465540/225216328-13addb7c-d7b6-4d0c-b179-34536c902fe0.jpeg)

I do not have this issue on the computer but on the phone I get a language I do not recognize.

I have the same issue on safari and chrome.

Mot should says “Mars 15” but it says “njukcamánnu 15”.

### Steps to reproduce

All browsers on phone 

### homepage version

Latest 

### Installation method

Docker

### Configuration

```yaml
Date config from tutorial with se local
```

### Container Logs

Don’t know

### Browser Logs

Don’t know

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please post your actual config. And can you explain what is incorrect? Is your locale `se`?

**Comment by TibiaBubble** [comment]
> Please post your actual config. And can you explain what is incorrect? Is your locale `se`? If not presumably your phone is set incorrectly somehow. I cannot reproduce this, nor can any of our other users, it seems...

I will try to get the config file when I return home.
It’s weird I tried accessing through inkognito mode and different browsers.

**Comment by TibiaBubble** [comment]
here are thr numbers




widgets.yaml                                                  
---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    label: System
    cpu: true
    memory: true
    expanded: true
    disk: /



- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    locale: se
    format:
      dateStyle: long
      timeStyle: long

- openmeteo:
    label: Sthlm # optional
    latitude: X (dont want to print out)
    longitude: X  (dont want to print out)
    timezone: Europe/Stockholm # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits

**Comment by shamoon** [comment]
> * locale: se

Are you intentionally using `se` instead of `sv`? https://www.w3schools.com/tags/ref_language_codes.asp

<img width="343" alt="Screenshot 2023-03-15 at 10 34 37 AM" src="https://user-images.githubusercontent.com/4887959/225394767-243accc2-e8a1-46f2-ac29-e4c31c7eb128.png">

**Comment by shamoon** [comment]
Either way, these translations come entirely from javascript as noted in the [docs](https://gethomepage.dev/en/widgets/datetime/)

**Comment by TibiaBubble** [comment]
> > * locale: se
> 
> Are you intentionally using `se` instead of `sv`? https://www.w3schools.com/tags/ref_language_codes.asp
> 
> <img alt="Screenshot 2023-03-15 at 10 34 37 AM" width="343" src="https://user-images.githubusercontent.com/4887959/225394767-243accc2-e8a1-46f2-ac29-e4c31c7eb128.png">

hahaha ofcourse! omg how stupid am I :D
thanks mans!
