### ISSUE TITLE
Alternate weather provider?

### ISSUE THREAD

**Issue by sheeepdev** [benphelps/homepage#111]
Hey!

First, I wanna thank you for creating this awesome homepage!

The main problem I have with it that both weather providers it supports need some paid plan / trial
OpenWeatherMap is 0.12 gbp per 100 calls (which i wont be wasting on a homepage weather widget) while WeatherAPI is only a 14 day trial
Is there some alternate free provider you can add or can you support the openweathermap free plan?

Thanks

**Comment by benphelps** [comment]
I don't believe there is a "free as in speech" weather API provider, it's a complicated and costly service to offer.

However.

OpenWeatherMap is free, you'll be well within the free tier amount of API calls.
<img width="286" alt="Screenshot 2022-09-11 at 11 55 42 PM" src="https://user-images.githubusercontent.com/82196/189548494-df3b6cef-cd59-4b75-88bf-f4a61765fb60.png">


WeatherAPI is also free, after the 14 day trial, you'll be on the free plan.  They don't advertise this, or show a "free" tier on their pricing page, but it does indeed have a free tier.
<img width="619" alt="Screenshot 2022-09-11 at 11 56 29 PM" src="https://user-images.githubusercontent.com/82196/189548528-a55801de-50ee-4f4d-9b2f-6f01e0d21b10.png">

**Comment by sheeepdev** [comment]
I did not mean free as in freedom or something like that. I litteraly meant free.
About the free plan, when I tried the openwearthermap free plan it was saying api error so I thought I needed the paid plan. Thanks for the heads up! I will probably stick with WeatherAPI if there is a free tier

**Comment by benphelps** [comment]
OpenWeatherMap API keys take 5+ minutes to activate in my experience, so you might have just tried the key too early.

**Comment by sheeepdev** [comment]
Hmm idk if you mean this but I tried an api key from way earlier I use for everything, idk if you meant 5 mins to load or to activate the key on owm

**Comment by sheeepdev** [comment]
> I don't believe there is a "free as in speech" weather API provider, it's a complicated and costly service to offer.
> 
> However.
> 
> OpenWeatherMap is free, you'll be well within the free tier amount of API calls. <img alt="Screenshot 2022-09-11 at 11 55 42 PM" width="286" src="https://user-images.githubusercontent.com/82196/189548494-df3b6cef-cd59-4b75-88bf-f4a61765fb60.png">
> 
> WeatherAPI is also free, after the 14 day trial, you'll be on the free plan. They don't advertise this, or show a "free" tier on their pricing page, but it does indeed have a free tier. <img alt="Screenshot 2022-09-11 at 11 56 29 PM" width="619" src="https://user-images.githubusercontent.com/82196/189548528-a55801de-50ee-4f4d-9b2f-6f01e0d21b10.png">

Hey, now that the 14-day trial has passed I have come to notice that the API key has been disabled and I've got an email saying that if I want to continue to use the service I have to switch to a paid plan. So there is indeed no "free tier"

**Comment by JazzFisch** [comment]
@sheeepdev I am using OpenWeatherMap per the information that Ben provided in the wiki.  After creating your account, go to https://home.openweathermap.org/subscriptions and set your "Calls per day" to 1,000 to ensure you don't exceed the free 1,000 free calls you can make per day.

**Comment by saxobroko** [comment]
Is there an issue with WeatherUnderground or other PWS services?

**Comment by shamoon** [comment]
We added openmeteo for just this reason, it’s always free: https://gethomepage.dev/en/widgets/openmeteo/

**Comment by saxobroko** [comment]
As far as I can tell Open Meteo doesn't support PWS and also has inaccurate temperature results for my area around 5°C
