### ISSUE TITLE
[Bug] Komga request error

### ISSUE THREAD

**Issue by matthewdias** [benphelps/homepage#1126]
### Description

The komga widget errors saying that the user agent header must be passed to the /libraries endpoint.
![CleanShot 2023-03-20 at 01 29 14](https://user-images.githubusercontent.com/3302524/226263732-7df45c3b-ce7e-41c8-8d64-18c7ea0a1710.png)

### Steps to reproduce

1. Enable the komga widget
2. See error

### homepage version

v0.6.10 (af2566c, Feb 28, 2023)

### Installation method

Docker

### Browser Logs

The /series and /books endpoints also fail but with message "Invalid data", not sure if this is an effect of the /libraries failure or a separate issue.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Can't reproduce with `v0.165.0-master`

<img width="495" alt="Screenshot 2023-03-19 at 11 56 37 PM" src="https://user-images.githubusercontent.com/4887959/226268256-ccf1632a-c9ce-418c-b9a9-78c2e5207904.png">

**Comment by shamoon** [comment]
https://github.com/gotson/komga/commit/cb07581daa850cc38902304e4d2ac8717e1f8696
