### ISSUE TITLE
[Bug] Widget/API can pull local disk info but not network disk info

### ISSUE THREAD

**Issue by VestedDeveloper** [benphelps/homepage#1131]
### Description

Widget/API can pull local disk info but not network disk info
![image](https://user-images.githubusercontent.com/128421649/226448560-a874199e-7e58-4a9d-9a24-fdee786ea4be.png)

### Steps to reproduce

1. Verified disk path on Proxmox cluster (/mnt/pve/NAS-vm)
2. Copy/paste into config
3. Refresh; API error
4. Updated to remove "/NAS-vm" 
5. Refresh, API error
6. Confirmed on Proxmox host that diskspace is reported

### homepage version

v0.6.10 (af2566c)

### Installation method

Docker

### Configuration

```yaml
- resources:
    cpu: true
    memory: true
    disk: /mnt/pve/
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
You need to mount the volume to the container
