### ISSUE TITLE
[Bug] CPU usage incorrect

### ISSUE THREAD

**Issue by RoelvandeWiel** [benphelps/homepage#1158]
### Description

CPU usage is scuffed when you compare the total cpu usage with the cpu usage of the different running services.

![image](https://user-images.githubusercontent.com/12953572/228655628-f0594be7-e3c9-4568-960b-591ea7c0768d.png)

### Steps to reproduce

1. Open my dashyboard
2. Open then container information

### homepage version

v0.6.10 (af2566c, Feb 28, 2023)

### Installation method

Docker

### Container Logs

No specific logs found after refreshing the dashboard.

### Browser Logs

No weird logs found.

### Other

All my containers are on the latest version according to Watchtower.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Hmm, these values come from the docker API. Im assuming you've compared these values to `docker stats CONTAINER`? Seem OK for me.

In your network tab you'll see calls like `http://HOMEPAGEURL/api/docker/stats/CONTAINER/SERVER`, can you paste the output here for one of the offending containers?

**Comment by shamoon** [comment]
To clarify, the calculation is the same one from the docker client: https://github.com/moby/moby/blob/eb131c5383db8cac633919f82abad86c99bffbe5/cli/command/container/stats_helpers.go#L175-L188

**Comment by RoelvandeWiel** [comment]
> Hmm, these values come from the docker API. Im assuming you've compared these values to `docker stats CONTAINER`? Seem OK for me.
> 
> In your network tab you'll see calls like `http://HOMEPAGEURL/api/docker/stats/CONTAINER/SERVER`, can you paste the output here for one of the offending containers?

I'll do this when i get home from work.
