### ISSUE TITLE
[Bug] Prowlarr widget - Unable to display field "enableIndexer"

### ISSUE THREAD

**Issue by Nindohana** [benphelps/homepage#1164]
### Description

Since the latest update, the Prowlarr widget doesn't display the "enableIndexer" field anymore.

![image](https://user-images.githubusercontent.com/49897838/229000550-a5803059-48bc-4b35-84f9-e2ee60321c66.png)

![image](https://user-images.githubusercontent.com/49897838/229000567-1162ba10-c9af-4c77-87fe-b75c9d8b51d7.png)

### Steps to reproduce

Add the Prowlarr widget and display all fields, the "enableIndexer" one can't be seen.

### homepage version

0.6.10

### Installation method

Docker

### Configuration

```yaml
widget:
            type: prowlarr
            fields: ["enableIndexer","numberOfGrabs"]
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I corrected the documentation, `enableIndexer` is not an actual field

**Comment by shamoon** [comment]
Just what’s in the docs currently. And the number of fields is capped to 4
