### ISSUE TITLE
[Bug] Invalid memory usage reported after update to v0.6.11

### ISSUE THREAD

**Issue by dejanstojanovic** [benphelps/homepage#1173]
### Description

Hi,

I am runnig homepage on QNAP TS-433 as a container configured inside Portainer.
All worked fine, but after updating to v0.6.11 I am getting invalid memory usage reported. I compared it to QTS and numbers do not add up, not even close

![image](https://user-images.githubusercontent.com/7481783/229701505-b1680559-c32a-494c-80a6-26f577a7e5c4.png)

![image](https://user-images.githubusercontent.com/7481783/229701591-e5b55228-889c-4d67-aac8-33691c080661.png)

I checked the documentation but could not find anything that mentiones any new configuration to be set for resources widget specifically

### Steps to reproduce

1. Login to Portainer
2. Locate Homepage stack
3. Go to "Editor" tab
4. Click "Update the stack" button
5. In popup dialog check "Re-pull image and redeploy"
6. Click "Update" button

### homepage version

v0.6.11

### Installation method

Docker

### Configuration

```yaml
- resources:
    cpu: true
    memory: true
    expanded: true
    disk: /
    cputemp: true
    uptime: true
    units: metric
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
What's the output of your `/api/widgets/resources?type=memory` call (check network tab)? Thinking we should use active / available instead
