### ISSUE TITLE
[Bug] Can't build 0.6.13 on arm

### ISSUE THREAD

**Issue by vladaurosh** [benphelps/homepage#1180]
### Description

Not able to build 0.6.13 from source (previous versions were fine) on Arm SBC. Getting this error:

> npm ERR! code EBADPLATFORM
> npm ERR! notsup Unsupported platform for osx-temperature-sensor@1.0.8: wanted {"os":"darwin"} (current: {"os":"linux","arch":"arm"})
> npm ERR! notsup Valid OS:    darwin
> npm ERR! notsup Valid Arch:  undefined
> npm ERR! notsup Actual OS:   linux
> npm ERR! notsup Actual Arch: arm

### Steps to reproduce

Run npm build

### homepage version

v0.6.13

### Installation method

Source

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Closed by 364c7ce1838702185d78b5c27755093924265d64

Ah gotcha, can you try against the current `main` branch?

**Comment by vladaurosh** [comment]
Looking good now on 0.6.14. Thanks.
