### ISSUE TITLE
[Bug] support optional media counts in jellyfin / emby widgets

### ISSUE THREAD

**Issue by Magelo** [benphelps/homepage#1181]
### Description

Since version v0.6.11, this feature [#1101 ]( https://github.com/benphelps/homepage/pull/1101) introduced a bug. 

A bug besides, "blocks boolean evaluation" which was fixed with v.0.6.13.

The Now Playing appears only if there is one stream playing, if a second stream start, the Now Playing disappear completely. If either stream stops, the other still playing is shown.

Before, both streams were shown. I can't say how many were shown before, I never tested the limit, but two were definitely possible before.

I have Emby Server v4.8.0.28, this bug was introduced with v0.6.11.

### Steps to reproduce

- Emby:
        icon: emby.png
        href: url
        description: Media manager
        widget:
          type: emby
          url: url
          key: xxxxxxxxx
          enableBlocks: true
          enableNowPlaying: true

Open Homepage:
![image](https://user-images.githubusercontent.com/10362303/229927453-2b354703-5aaa-4844-8fe4-ebd80f19c490.png)

Start one stream:
![image](https://user-images.githubusercontent.com/10362303/229928327-f487e984-0f02-4b83-977c-10005ab03f95.png)

Start second stream:
![image](https://user-images.githubusercontent.com/10362303/229928486-b559b59f-dc17-4e96-9129-afc1e70c1657.png)

Stop the first stream:
![image](https://user-images.githubusercontent.com/10362303/229928687-c4b93cd2-9b18-4836-9ea4-3fd83c76d577.png)

### homepage version

0.6.13

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Thanks, I'll sort it out. Would you mind sending the output of the API call to e.g. /api/services/proxy?type=emby&group=Testing&service=jellyfin&endpoint=Sessions...

**Comment by shamoon** [comment]
Nevermind about the sample, I can reproduce so I'll sort it out
