### ISSUE TITLE
Password Obsfucation

### ISSUE THREAD

**Issue by karmarcharger** [benphelps/homepage#119]
For widgets that require password in the config file, perhaps the password should be hidden with (https://argon2.online/) or something rather then being stored as plain text, as certain widgets would grant access to critical infrastructures.

**Comment by benphelps** [comment]
None of the API keys are exposed to the frontend API, only the widget type and it's group.

API keys and other passwords are read from the backend API only.

**Comment by karmarcharger** [comment]
I meant in the case someone gets access to the config files somehow.

**Comment by benphelps** [comment]
It would simply be obfuscation, and if they had access to the config file, they'd have access to any other secret used to obfuscate the sensitive data.  So it wouldn't add any extra protection and only make setting things up more complicated than it needs to be.

The config files are securely outside of the public web directory, and the APIs use a whitelist of safe configuration values to pass to the frontend.  So I feel like its already as secure as it could be.

You have to remember, the API keys and passwords sent to the backing APIs, has to be sent as plain text.  So any operation we could make, would have to be reversible, so the added security is very minimal.

**Comment by karmarcharger** [comment]
Ah yea if it’s sent as plain text that would be pretty pointless.
