### ISSUE TITLE
[Bug] Docker image stuck on unhealthy and homepage wont load

### ISSUE THREAD

**Issue by mendoncart** [benphelps/homepage#1190]
### Description

Hi!
I was going to open this issue yesterday, but deleting the whole config folder, image and recreating all from start worked, but I can't do that every time I need to upgrade the image or reboot my docker host...

It all started when I tried to upgrade from v0.5.7 to any version above. The container stuck on unhealthy, and the portainer log of the container showed nothing. I deleted everything related to the homepage container and tried pulling the image again and it worked. Now I just rebooted my docker host and the same problem appeared again...

My docker compose
```python
homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
    ports:
      - 3000:3000
    volumes:
      - /opt/homepage/config:/app/config
```

Docker version: 23.0.3, build 3e7cbfd
Portainer version: Business Edition 2.17.1
Host OS: TurnKey GNU/Linux 16.1 (Debian 10/Buster)

Screenshot of inspecting container:
![image](https://user-images.githubusercontent.com/62950083/230106898-cfd0f20e-75f7-4f85-ac62-a1ca32ec463a.png)

I don't know why isn't able to connect to itself.

### Steps to reproduce

A - Try to upgrade the version:
1. Open the terminal to the host
2. Run the command 'docker compose up -d'
3. Wait for the command to pull the new images and recreate the containers

B - Rebooting the host
1. With the homepage fully functioning, reboot the host OS.
2. Wait for the reboot to complete and all systems to boot up.

### homepage version

v0.6.12

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by mendoncart** [comment]
Funny enough, after about 10 minutes up, the homepage came back online.
I don't know what is making it take so long to load...
Now I don't know if I close this, or if I get some assistance to investigate it further...
It's up to you guys.

**Comment by shamoon** [comment]
Well I can’t reproduce this, presumably most of our other many users can’t so it doesn’t sound particularly like a bug in our codebase, so I’ll close this. If you do figure it out feel free to update here, or of course if you can narrow this down to a true bug

**Comment by giacomocerquone** [comment]
This is happening to me too with docker on a Raspberry Pi 2.
Even though the rasp is just a toy, printing the processes (with something like `top`) it's not under a particularly heavy load.
It took more than 20 minutes for homepage to be available.

**Comment by benphelps** [comment]
Make sure you're using the correct docker image as well,

We've moved, it's now `ghcr.io/gethomepage/homepage:latest`.

**Comment by giacomocerquone** [comment]
> Make sure you're using the correct docker image as well,
> 
> We've moved, it's now `ghcr.io/gethomepage/homepage:latest`.

yes, that's the image on the readme of the repo.
I also noticed that while being unhealthy, issuing a `docker container restart` sometimes spins up the app very quickly 🤷
