### ISSUE TITLE
[Feature Request] Widget for Kuma

### ISSUE THREAD

**Issue by PotatoPTT** [benphelps/homepage#123]

**Comment by ShlomiPorush** [comment]
Add me to this request

**Comment by ItsJustMeChris** [comment]
I will look into this over the weekend if there's nobody else interested in taking it on. 

Never really looked into AdGuard Home so I can't guarantee it will be done quickly, but I will try 😅

**Comment by benphelps** [comment]
@eugenehw08 @PotatoPTT 

Added Adguard Home widget in the latest release.

**Comment by eugenehw08** [comment]
hi,

can you update the information section in Service Widgets page?

**Comment by benphelps** [comment]
Updated, https://github.com/benphelps/homepage/wiki/Service-Widgets#adguard-home

**Comment by JazzFisch** [comment]
@ItsJustMeChris I didn't notice that you were interested on working on qBittorrent as well.  I was glossing over the titles and didn't read in to see your interest.  Sorry about that.

**Comment by r0m1CH** [comment]
A widget for Kuma would be perfect

**Comment by schnaxelhubr** [comment]
Being able to monitor the Uptime Kuma probes via a widget would be a very valuable addition

Alternatively - having a widget with a true IGMP ping would be also great.

**Comment by IIIdefconIII** [comment]
would be very nice to have!

**Comment by Jinxtrr** [comment]
+1 for uptime kuma as well!

**Comment by NelsonDane** [comment]
Another +1 for uptime kuma

**Comment by IIIdefconIII** [comment]
+1!

**Comment by ozdeadmeat** [comment]
+4!!!!

**Comment by joeryanh** [comment]
+1

**Comment by ivybowman** [comment]
Extra +1 for uptime kuma

**Comment by shamoon** [comment]
Appreciate all the interest but know that Kuma doesnt offer a JSON API yet which is almost a non-starter for this, until things change...

**Comment by codeman1o1** [comment]
https://github.com/louislam/uptime-kuma/blob/a17084f75d1e5239ca2daf917d8a5002ef4953a8/server/routers/status-page-router.js#L29-L60
https://github.com/louislam/uptime-kuma/blob/a17084f75d1e5239ca2daf917d8a5002ef4953a8/server/routers/status-page-router.js#L62-L108
Could this be useful?

**Comment by shamoon** [comment]
That doesnt look like something that could be used externally

See https://github.com/louislam/uptime-kuma/issues/118

In general, I would ask that folks up-vote with the reactions instead of adding "+1" comments, aware there is demand for this. If you have other information to add please comment.

**Comment by r0m1CH** [comment]
Maybe by using a third party api like https://github.com/MedAziz11/Uptime-Kuma-Web-API we could achieve one or two metrics (number of sensor and number of error) ?

**Comment by shamoon** [comment]
Thanks, I'll look into all this at some point

**Comment by divemasterjm** [comment]
👍

**Comment by shamoon** [comment]
Big thanks to @chain710 for initial work (@codeman1o1 those endpoints were helpful after all, I'm not a kuma user so didn't really get the structure when I looked at it).

Until a formal API is added this seems like as good solution.
