### ISSUE TITLE
Feature Request - Disk space units.

### ISSUE THREAD

**Issue by phillipsjamesg** [benphelps/homepage#13]
For the disk space. I would like to change the units. I passed in my main storage which is about 35TB. right now it shows: 
```
20421 GB free
16918 GB used
```
Haven't at least two decimals and TB would be nice to see.

**Comment by benphelps** [comment]
I've updated the resource widget, it'll now report in the correct units depending on the size.

**Comment by phillipsjamesg** [comment]
Thank you. I tried pulling the latest update and it's giving me an error. Stating that it either does not exist or needing a docker login. Trying to pull the latest in portainer. Using `ghcr.io/benphelps/homepage:main`

**Comment by benphelps** [comment]
I was able to pull it myself from my RasPi box, maybe you have a typo or bad copy/paste.

**Comment by phillipsjamesg** [comment]
I just tried it again and it worked. I guess you threatened it enough. 

Thanks the units look great
