### ISSUE TITLE
[Bug] Container not honoring TZ

### ISSUE THREAD

**Issue by sithadmin** [benphelps/homepage#1329]
### Description

When passing the TZ environment variable to the container on Unraid, the container date/time is still set to UTC.

### Steps to reproduce

1. Install Docker image via Unraid interface using prebuilt template
2. TZ variable is built into the template
3. Open a shell to the running container
4. date command will return UTC

### homepage version

v0.6.15

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Date and time comes from the browser

**Comment by sithadmin** [comment]
That is not the behavior I am seeing in Firefox
![Screenshot 2023-04-09 152406](https://user-images.githubusercontent.com/578874/230792588-2b49d5a0-7815-48ab-a32b-9c6edaf5c14a.png)

widget config:
- datetime:
    text_size: md
    format:
        timeStyle: short
        dateStyle: short

**Comment by sithadmin** [comment]
My apologies, this was a vpn plugin turning on fingerprinting security.
