### ISSUE TITLE
[Bug] Ghostfolio instructions wrong

### ISSUE THREAD

**Issue by NickSChristiansen** [benphelps/homepage#1347]
### Description

According to the instructions in the [homepage wiki for Ghostfolio](https://gethomepage.dev/en/services/ghostfolio/) you're supposed to be able to get a bearer token from Ghostfolio by using the URL, replaced with the relevant values.
However, it seems the bearer token has either moved to a different endpoint or no longer exists, as a 404 will be thrown when trying to fetch the token.

![ghostfolio](https://user-images.githubusercontent.com/44038652/231205964-f85b1f2e-9aa6-4aba-aee6-5a6705c837ab.png)

### Steps to reproduce

1. Follow the instructions for getting the Bearer token from Ghostfolio

### homepage version

v0.6.16 (0ae13d8)

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
This comes from their docs... https://github.com/ghostfolio/ghostfolio#authorization-bearer-token

**Comment by shamoon** [comment]
Ha, your timing is funny, looks like they updated the readme minutes after I posted, looks like it did change https://github.com/ghostfolio/ghostfolio/commit/7d2d1d971ab91ec469fadcf2cd7972e97ec9cf17

**Comment by NickSChristiansen** [comment]
According to the updated readme from Ghostfolio it's now a POST with the token in the body - meaning the homepage documentation is still wrong, as it's not possible (natively) to do a POST request from a browser with a body.

**Comment by NickSChristiansen** [comment]
Yeah, but as per the readme it's deprecated, meaning it will, most likely, be removed soon. But I guess if you're okay with using deprecated functionality, there is no need to update the instructions.

**Comment by shamoon** [comment]
nvm I got it
