### ISSUE TITLE
[Bug] Significant CPU usage of resource widget

### ISSUE THREAD

**Issue by Mega-Volti** [benphelps/homepage#1359]
### Description

Since the CPU temp and update functionalities were added, the resource widgets does consome significantly more CPU time than before. Even when only showing disk space, significant CPU time is used, although less than when using temp and uptime info as well. This is particularly noticable on low-power systems (e.g. RPi).

I assume this is unintended behavior? If the CPU load is necessary to provide temp / uptime info and can't be avoided, an option to reduce the poll frequency (which then automatically reduces CPU usage) would also fix the issue. Right now, it seems like the resource widget polls every 1-2 seconds, which seems excessive.

### Steps to reproduce

1. Deactivate resource widget
2. Check docker stats for Homepage CPU usage
3. Activate resource widget
4. Check docker stats for Homepage CPU usage

### homepage version

v0.6.16

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Not seeing this. After initial load I get very minimal usage, I would be surprised if uptime or temp are significantly affecting this (vs before).

If youre not happy with CPU usage with resources widget you can disable it, no?

<img width="1108" alt="Screenshot 2023-04-13 at 3 56 58 PM" src="https://user-images.githubusercontent.com/4887959/231900646-afc21a8e-d126-47ad-bac0-3df2b01770da.png">

**Comment by Mega-Volti** [comment]
Percentage depends on the CPU used of course. The little "hills" with about 2% CPU usage in your graph spike up to about 25% for my system.

Yes, disabling it is an option. But before temp/uptime functionalities were added, simply activating the HDD free space resource widget didn't produce significant CPU spikes. Now it does, even with temp/uptime deactivated, and with those two activated it spikes even higher.

I assume when temp/uptime were added, somehow the base CPU load for this widget increased as well? Or is that not possible?

Either way, a reduced polling rate would fix this as well.

**Comment by shamoon** [comment]
Sounds like a FR, respectfully. Perhaps you might want to try out the glances widget

**Comment by Mega-Volti** [comment]
Yes, the "reduce polling frequency" would be more of a FR indeed.

But maybe I didn't phase the part of why I thought it was a bug correctly: Before temp/uptime were introduced in the resources widget, using the resources widget to display HDD space did not cause these large CPU usage spikes, After temp/uptime were included in the resource widget, even when only using the HDD part of it, I still see significant CPU spikes, much more than before.
That's why I thought there has to be a bug of some sort. Sorry if that was wrong.
