### ISSUE TITLE
[Bug]  Color shift when using Firefox Mobile

### ISSUE THREAD

**Issue by MitoG** [benphelps/homepage#1382]
### Description

The color schema somehow is shifted to red when using Firefox mobile.
Neither Vivaldi Mobile nor Chrome Mobile exhibit this behavior.

Firefox: 
- Version: 111.11.1 (Build #2015941331), 7ca9e3119b+
- GV: 111.0.1-20230321111920
- AS: 96.4.0

Homepage:
- Version: v0.6.16 (0ae13d8, Apr 8, 2023)

![homepage_red-shift](https://user-images.githubusercontent.com/6368249/233032202-ee664472-1be9-48e7-90a0-924ce3ac69d0.jpeg)

### Steps to reproduce

Open homepage in Firefox Mobile

### homepage version

v0.6.16 (0ae13d8)

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by benphelps** [comment]
This is due to a "dark mode" extension you have installed.

**Comment by MitoG** [comment]
alrigh, gonna book that under learning experience.

thank you.
