### ISSUE TITLE
[Bug] Tautulli integration play pause symbols backwards

### ISSUE THREAD

**Issue by richardphi1618** [benphelps/homepage#140]
maybe just a me thing but the "pause" symbol is shown next to the item that is actively playing and the "play" symbol is next to the stream that is actively paused. Not sure if my brain just isn't gripping this properly or if this is indeed backwards. Thought I would say something regardless. 

![image](https://user-images.githubusercontent.com/38547621/189753247-cfeba61d-5db0-43d2-b13b-8cabb8a40522.png)
*The image is probably not super helpful as you can't see state but I thought I would add it anyways to help point in the right direction

**Comment by benphelps** [comment]
You're correct, on Emby and Jellyfin widgets, the button has an action attached to it (so it is presented in the same way the player presents it, ie. clicking it will pause).

For Tautulli, it needs to be reverse since it's only showing a state.

I'll get this updated.

**Comment by C8opmBM** [comment]
After re-working the widget, plex/tautulli will no longer tell us if the stream is transcoded or not. Could you somehow integrate that back? It's very important to know the state of the stream. 
Thank you! Amazing amount of work done on this app in such a small timeframe. Awesomeness!!!

**Comment by benphelps** [comment]
Icons have been fixed and transcoding information added.
