### ISSUE TITLE
[Bug] Can't fetch image from server

### ISSUE THREAD

**Issue by flow23** [benphelps/homepage#1421]
### Description

# docker image pull ghcr.io/benphelps/homepage
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/benphelps/homepage/manifests/latest": Get "https://ghcr.io/token?scope=repository%3Abenphelps%2Fhomepage%3Apull&service=ghcr.io": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### Steps to reproduce

# docker image pull ghcr.io/benphelps/homepage
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/benphelps/homepage/manifests/latest": Get "https://ghcr.io/token?scope=repository%3Abenphelps%2Fhomepage%3Apull&service=ghcr.io": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### homepage version

N/A

### Installation method

Docker

### Configuration

```yaml
N/A
```

### Container Logs

N/A

### Browser Logs

N/A

### Other

N/A

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by flow23** [comment]
This is the response from the server:

```
{
"errors": [
{
"code": "UNAUTHORIZED",
"message": "authentication required"
}
]
}
```

**Comment by shamoon** [comment]
I'm sure this is https://www.githubstatus.com/incidents/vsc464zj7gv4

Though that is supposedly resolved now
