### ISSUE TITLE
[Bug] PiHole icon 404

### ISSUE THREAD

**Issue by thegabriele97** [benphelps/homepage#1469]
### Description

Unable to retrieve PiHole logo, the following link: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pihole.png doesn't exist. It should be https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pi-hole.png.

![image](https://user-images.githubusercontent.com/35406071/236669542-6acd15a0-e252-4626-9193-324264c9d693.png)

### Steps to reproduce

1. Instantiate the PiHole block

### homepage version

v0.6.17 (f692e71, May 1, 2023)

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by Spazholio** [comment]
I don't know if I should re-open this or start a new issue, but the Pihole icon is still 404'd for me.  The link is https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pihole.png and I'm running v0.6.17 (f692e71).  Please let me know if there's anything else you need from me to diagnose/debug.
