### ISSUE TITLE
GIF background broke after update

### ISSUE THREAD

**Issue by karmarcharger** [benphelps/homepage#147]
Was using the config below before the update, worked fine, after update the image does not load
![image](https://user-images.githubusercontent.com/10364143/189896324-856289ed-b916-4abe-9380-a310217a17e4.png)

settings.yaml

title: Home
background: https://i.pinimg.com/originals/09/24/4c/09244c7f7dd4d17b0484370f32db6641.gif
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

**Comment by richardphi1618** [comment]
I ran into a similar issue where recreating my container with the latest image broke the background (using a url to a gif as well https://wallpaperaccess.com/full/6604090.gif). I was able to hit the refresh button and recover. Just fyi.

**Comment by benphelps** [comment]
Nothing has changed that could have caused a background image to not load.  I just tested with your background and it's loading fine.  I'd take @richardphi1618's advice and try doing a hard refresh or clearing the site cache.
