### ISSUE TITLE
[Bug] Podman support

### ISSUE THREAD

**Issue by cmh716** [benphelps/homepage#1476]
### Description

I deployed a container on Podman with this compose information:

version: "3"
services:
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /home/$USER/Containers/homepage:/app/config 
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - /home/$USER/Containers/uptime-kuma/data:/app/data
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
    restart: always
    ports:
      - "3001:3001"
    labels:
      - homepage.group=Networking
      - homepage.name=Utime Kuma
      - homepage.icon=uptime-kuma
      - homepage.href=http://192.168.0.229:3001
      - homepage.description=Service Monitor
      - homepage.widget.type=uptimekuma
      - homepage.widget.slug=homepage
      - homepage.widget.url=http://192.168.0.229:3001
      - homepage.target=_self
      - homepage.ping=http://192.168.0.229:3001

homepage correctly fetches the dashboard information from the socket and displays the following:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/3275478/236912387-93156e52-afee-4044-ba4e-0c0406523652.png">

But when I click on "Running" I get:

<img width="859" alt="image" src="https://user-images.githubusercontent.com/3275478/236912733-963e4de2-069e-4e90-8261-f18bb31d43c9.png">

It worked fine on docker.  Maybe this is a Podman incompatibility? 

### Steps to reproduce

see error above

### homepage version

v0.6.17 (f692e71, May 1, 2023)

### Installation method

Docker

### Troubleshooting

See above

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
> Troubleshooting
Please include output from your [troubleshooting tests](https://gethomepage.dev/en/more/troubleshooting/#service-widget-errors). If this is a service widget issue and you do not include any information here your issue will be closed. If it is not, indicate e.g. 'n/a'
