### ISSUE TITLE
[Bug] NodeRed icon broken in latest release

### ISSUE THREAD

**Issue by chall3ng3r** [benphelps/homepage#1482]
### Description

NodeRed Widget icon is not rendered.

The filename in Dashicons for nodered.png is updated to node-red.png, the latest build still uses the old nodered.png which returns 404 error.

### Steps to reproduce

1. Add NodeRed widget
2. Save and refresh page 

### homepage version

v0.6.17 (f692e71, May 1, 2023)

### Installation method

Docker

### Troubleshooting

Fix: Update the Dashicons filename request from nodered.png to node-red.png

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
That has nothing to do with this repo…
