### ISSUE TITLE
[Bug] Pi-hole icon not showing in widget

### ISSUE THREAD

**Issue by RoelvandeWiel** [benphelps/homepage#1483]
### Description

The pi-hole icon from walkxcode/dashboard-icons is not showing in the widget.
![image](https://github.com/benphelps/homepage/assets/12953572/8a060813-067f-473b-8fa1-530cc7603331)

### Steps to reproduce

- Add the pi-hole widget
- Open homepage
- no icon

### homepage version

v0.6.17

### Installation method

Docker

### Troubleshooting

This is the url which the widget uses [https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pihole.png](url)
And from what i checked if we replace "pihole.png" with "pi-hole.png" it should work again most likely.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
https://github.com/benphelps/homepage/discussions/1365

**Comment by naziris** [comment]
change the end of the link from pihole.png to pi-hole.png

**Comment by RoelvandeWiel** [comment]
Yh i know, i was an idiot.
