### ISSUE TITLE
[Bug] Pihole icon is 404'd

### ISSUE THREAD

**Issue by Spazholio** [benphelps/homepage#1497]
### Description

Description
Icon link is broken: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pihole.png.

<img width="327" alt="image" src="https://github.com/benphelps/homepage/assets/18452263/ba950d82-de0b-427d-80e7-1989ad627772">

### Steps to reproduce

Set up a Pihole block

### homepage version

v0.6.17 (f692e71, May 1, 2023)

### Installation method

Docker

### Troubleshooting

n/a

### Other

I saw that there was another issue opened and closed about this, stating it was fixed but I don't believe it is.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please read the other issue. The icons have to do with this repo
