### ISSUE TITLE
Unifi API error [Bug] 

### ISSUE THREAD

**Issue by dwhitnall** [benphelps/homepage#1498]
### Description

I'm trying to get te UniFi widget to work, however I'm using a UDMPro which has a different API end point.
Is it possible to add a setting so it can be changed.
Currently its set to api/stat/sites but UDMPro needs to be proxy/network/api/stat/sites
I've tried to edit the container directly to reflect this but I've been unable to.

### Steps to reproduce

Added the widget to the widgets.yaml following the documentation but it is pointing to the incorrect api address for the UDMPro

### homepage version

v0.6.17 (f692e71, May 2, 2023)

### Installation method

Docker

### Configuration

```yaml
- unifi_console:
    url: https://192.168.*.*
    username: homepage
    password:**********
```

### Container Logs

[2023-05-14T07:57:21.430Z] error: <unifiProxyHandler> HTTP 500 getting data from Unifi endpoint https://192.168.*.*/api/stat/sites. Data: { error: [Object] }

### Troubleshooting

I can connect to the UDMPro from the container

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
> Troubleshooting
> Please include output from your [troubleshooting tests](https://gethomepage.dev/en/more/troubleshooting/#service-widget-errors). If this is a service widget issue and you do not include any information here your issue will be closed.

There are many people using UDMPs, myself included, the widget has logic for this. Id be willing to bet the issue is homepage connecting to the udmp at all. Please search through existing issues about this as well.

**Comment by shamoon** [comment]
https://github.com/benphelps/homepage/issues/862
https://github.com/benphelps/homepage/discussions/628
https://github.com/benphelps/homepage/issues/612
https://github.com/benphelps/homepage/pull/341#issuecomment-1272244930
