### ISSUE TITLE
[Bug] settings.xml layout should be a list and not an object

### ISSUE THREAD

**Issue by Skaronator** [benphelps/homepage#1546]
### Description

The layout sorting config uses an object to define the order of the layout. This setting should be a list because:

> An object is an **unordered collection** of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.

https://stackoverflow.com/a/7214312

https://gethomepage.dev/en/configs/settings/#sorting

### Steps to reproduce

Probably not the easiest to reproduce for this specific case but I think there is no reproduction nessecary to fix this.

I'm using terraform to deploy the community helm chart in my kubernetes cluster.

My terraform config looks this:

![image](https://github.com/benphelps/homepage/assets/2886913/294a3221-7a10-4ac0-8149-85bd4afff689)

The deployed ConfigMap looks like this:

![image](https://github.com/benphelps/homepage/assets/2886913/4952e077-809c-4d60-b9ba-34251ece5f8a)

(Noticed that the order completly flipped because Kubernetes or etcd sorts its alphabetically) 

### homepage version

v0.6.20

### Installation method

Other (please describe above)

### Troubleshooting

N/A

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
On the one hand its kind of annoying that this feels like terraform doing things unconventionally where most other tools seem to preserve the object's ordering. On the other hand, RFC.

The `main` image with the fix for this is currently building but should be done in a few minutes and then you can give it a test with however terraform supports arrays (or wait for the release).

**Comment by Skaronator** [comment]
Yup, works now - awesome! Thanks for the quick fix.

![image](https://github.com/benphelps/homepage/assets/2886913/79160dfc-61f9-4120-9f1c-be4d8e2aa442)

:)
