### ISSUE TITLE
[Bug] qBittorrent widget fails to log in when the password contains special characters

### ISSUE THREAD

**Issue by PeaceKin** [benphelps/homepage#1547]
### Description

My password for qBittorrent UI contains a `+` sign, and the widget gets `Fails` instead of `OK` response from qbittorrent (see container logs).
However, when I remove the `+` sign from my password, the widget starts working.

Using curl to log in seems to work fine, even when the password contains special characters:
```shell
curl -i --header 'Referer: http://192.168.1.10:8080' --data 'username=user&password=some+pwd' http://192.168.1.10:8080/api/v2/auth/login
```
```shell
HTTP/1.1 200 OK
connection: keep-alive
content-length: 3
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self';
content-type: text/plain; charset=UTF-8
date: Sun, 28 May 2023 13:30:51 GMT
referrer-policy: same-origin
set-cookie: SID=f5AKUyETMW9VzSUMWi+75d0eqgHuCxwc; HttpOnly; path=/
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```

### Steps to reproduce

1. Set qBittorrent UI password to `some+pwd`
2. Try to log in via the widget
3. Receive a `Fails` response

### homepage version

v0.6.20 (6046f79, May 20, 2023)

### Installation method

Docker

### Configuration

```yaml
- qBittorrent:
	href: http://192.168.1.10:8080
	description: asdf
	icon: qbittorrent
	server: omv-docker
	container: qbittorrent
	widget:
		type: qbittorrent
		url: http://192.168.1.10:8080
		username: user
		password: some+pwd
```

### Container Logs

[2023-05-28T13:21:40.122Z] debug: <qbittorrentProxyHandler> qBittorrent is rejecting the request, logging in.
[2023-05-28T13:21:40.329Z] error: <qbittorrentProxyHandler> Error logging in to qBittorrent: Data: Fails.

### Browser Logs

API Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
![qb_20230528](https://github.com/benphelps/homepage/assets/134851380/04daeba5-cb7e-4d99-899c-17b1a18f2b29)

### Troubleshooting

N/A, see troubleshooting steps in the description

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Thanks, fix for this will be in the `main` image in a few minutes after it builds, and in the next release.
