### ISSUE TITLE
[Bug] Cannot access Immich URL from the server container service

### ISSUE THREAD

**Issue by budimanjojo** [benphelps/homepage#1585]
### Description

Currently, I can't seem to access `immich` api url locally from the `immich-server` container.
To access `immich` api server locally, the right url should be: `http:immich-server:3001/server-info/stats`.
But the current url is harcoded to `/api/server-info/stats`:
https://github.com/Zlendy/homepage/blob/fb15f5dbc9273a3a024bfd70edad4544ebfe9208/src/widgets/immich/widget.js#L4

That url is right if accessing from external URL where the ingress is set to access the `immich-server` service from `/api` subpath.

### Steps to reproduce

Use local IP and port of `immich-server` service on `immich` service widget. It will fail to get the information.

### homepage version

v0.6.20 (6046f79, May 20, 2023)

### Installation method

Docker

### Troubleshooting

ERROR
```
/app # curl -L -X GET 'immich-server:3001/api/server-info/stats' -H 'Accept: application/json' -H 'x-api-key: apikeyapikey'
{"statusCode":404,"message":"Cannot GET /api/server-info/stats","error":"Not Found"}/app #
```
SUCCESS
```
/app # curl -L -X GET 'immich-server:3001/server-info/stats' -H 'Accept: application/json' -H 'x-api-key: apikeyapikey'
{"photos":66,"videos":6,"usage":394904392,"usageByUser":[{"userId":"1cb1d16e-e4fb-4d61-855e-09aaf7553821","userFirstName":"Budiman","userLastName":"Jojo....."
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I assume you are referring to a Kubernetes deployment? I dont understand why it would be different but there is no issue with this in docker installs

**Comment by budimanjojo** [comment]
Yes this is a kubernetes deployment

**Comment by shamoon** [comment]
So what's the solution? Why doesn't this happen with every other service we support?

Supporting kubernetes is proving to be a bit of a drag

**Comment by budimanjojo** [comment]
Can we don't hardcode the `/api` and let users to add `/api` at the end of the url instead?

**Comment by shamoon** [comment]
That will break every single user's installation

**Comment by budimanjojo** [comment]
Or maybe add another key for `accessfromserver: true`

**Comment by shamoon** [comment]
And pardon my ignorance, but are you able to setup the ingress route to work via /api? I dont understand why this app would work differently in docker vs k8s

**Comment by budimanjojo** [comment]
yeah right now I already have ingress routing `/api` to `immich-server` endpoint: https://github.com/budimanjojo/home-cluster/blob/98630b1549155886a130427f8e7936ef47d4404f/cluster/apps/default/immich/base/web/helmrelease.yaml#L57-L61

But I need to access the external URL which is very slow compared to local URL

**Comment by shamoon** [comment]
Again, I dont know kubernetes but theres no way to setup a similar route for local traffic?

**Comment by budimanjojo** [comment]
Actually I don't know too. I'll find out. But how is the `docker` version different when accessing from the server instead of the web container?

**Comment by budimanjojo** [comment]
Maybe it's because I'm not running the immich-proxy container. I'll see what I can do

**Comment by shamoon** [comment]
I haven't really looked at it much but their docker compose uses a proxy container and thats what you hit with the homepage url https://github.com/immich-app/immich/blob/b7d42e7e8e6f60122c846e502500fc3700d457d1/docker/docker-compose.yml#L80

**Comment by budimanjojo** [comment]
I'll close this now as this is not really a bug.

**Comment by simone-viozzi** [comment]
Hi, I have the same problem / want to do the same thing.

Just to wrap things:
- the `/api` is embedded into the request
- if you want to use the API from inside the docker network, you must not include the `/api`
- from the outside I have traefik to strip the `/api`

relevant `docker-compose` section: https://github.com/simone-viozzi/my-server/blob/14466e2c1c49a36b11a1bf848e15d7343dfb9bb5/immich/docker-compose.yml#L24-L46

If I hit the external url for the widget, it works fine: `homepage.widget.url: https://${IMMICH_DOMAIN}`
But this is routed by traefik, I would avoid if possible.

@budimanjojo How did you solve it?
