### ISSUE TITLE
[Bug] Unifi Controller Widget doesn't reload

### ISSUE THREAD

**Issue by fdcastel** [benphelps/homepage#1591]
### Description

Unlike the [Service Widget](https://gethomepage.dev/en/services/unifi-controller/) the Unifi Controller [Information Widget](https://gethomepage.dev/en/widgets/unifi_controller/) requires a full service restart to reload. 

This behavior is not documented in the [widget documentation page](https://gethomepage.dev/en/widgets/unifi_controller/). It may cause a burden to new users (like me).

Related: https://github.com/benphelps/homepage/issues/612

### Steps to reproduce

1. Add an [Unifi Controller Information Widget](https://gethomepage.dev/en/widgets/unifi_controller/) to `widgets.yaml` **with wrong parameters (e.g. invalid password)**;
2. Reload the page. It will display "Api error";
3. Fix the wrong parameter in `widgets.yaml`;
4. Reload the page. The "Api error" will persist;
5. Restart docker container.
6. Reload the page. The widget is now working correctly.

### homepage version

v0.6.20 (6046f79, May 19, 2023)

### Installation method

Docker

### Troubleshooting

Not needed.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Yes, login info is cached, you already described what to do to resolve it. I can add a note to the docs.
