### ISSUE TITLE
Overseerr shows 2 pending while there is nothing

### ISSUE THREAD

**Issue by pasc17** [benphelps/homepage#1595]
### Description

Hi everyone,

So I set up homepage recently, and added overseerr. But it seems there is a bug and can't figure what's wrong. Overseerr shows 2 pending but when I check directly on overseerr there is nothing.

https://ibb.co/MD4ScdD

I was thinking maybe it was a "declined" , but I deleted the declined from overseerr.

Any idea ?

Thanks

### Steps to reproduce

1. install homepage
2. add overseerr
3. receive pending requests waiting for approval.
4. after approval still shows pending in homepage but nothing in overseerr

### homepage version

v0.6.20

### Installation method

Docker

### Configuration

```yaml
docker run -d --name homepage -p 3000:3000 -v /volume1/docker/homepage/config:/app/config -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/benphelps/homepage:latest
```

### Troubleshooting

So I set up homepage recently, and added overseerr. But it seems there is a bug and can't figure what's wrong. Overseerr shows 2 pending but when I check directly on overseerr there is nothing.

https://ibb.co/MD4ScdD

I was thinking maybe it was a "declined" , but I deleted the declined from overseerr.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
This data is pulled directly from their API https://github.com/benphelps/homepage/blob/2fabaa700b9e7794cf7711e66875166b982e1f6f/src/widgets/overseerr/widget.js#LL9C1-L9C1

It is not going to be a homepage bug.

**Comment by pasc17** [comment]
I mean overseerr shows 0 record.
![image](https://github.com/benphelps/homepage/assets/130509361/e20c9485-ca4d-46d7-aca5-40597467eca5)

So what's wrong ?

**Comment by shamoon** [comment]
Try calling the actual API `{url}/api/v1/request/count` , if the results are 0 then perhaps try re-creating your homepage container but homepage doesn't manipulate that data in any way, as you can see above, so its not going to be a "bug"

**Comment by pasc17** [comment]
Ok I created the container, it's fixed.

Thank you
