### ISSUE TITLE
[Bug] Homepage Docker Container crashes w/ "Error: unexpected end of file"

### ISSUE THREAD

**Issue by hacustom** [benphelps/homepage#1609]
### Description

I've been running Homepage as a Docker container for some time now, and recently it's started crashing after running <1 minute. 

My log file doesn't have much to go on:
2023-06-13T20:06:45.348Z] error: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
[2023-06-13T20:06:45.350Z] error: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)

There had been some additional errors in the log about an API response >4MB from Radarr, so I removed that service widget and am still getting this error.

I've recreated the container, re-pulled the image, restarted the host machine, no luck.

### Steps to reproduce

docker-compose start homepage

homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage

    ports:
      - 3000:3000
    volumes:
      - /home/username/docker/homepage:/app/config
      - /home/username/docker/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
      - /media/usbdrive:/data:ro
      ##- /media/usbold:/olddata:ro

### homepage version

v0.6.21 (3e01fc1, Jun 12, 2023)

### Installation method

Docker

### Configuration

```yaml
I can provide my services yaml file but need to clean it up first to remove any sensitive information.
```

### Container Logs

2023-06-13T20:06:45.348Z] error: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
[2023-06-13T20:06:45.350Z] error: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)

### Troubleshooting

Restarted host
Restarted container
Removed service widgets
Recreated container

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by Inch-high** [comment]
+1 to this, having what seems to be a similar issue post updating to yesterdays build. The dashboard was working fine, and now its crashing post having started. 
![image](https://github.com/benphelps/homepage/assets/2678325/62cc19e4-89fc-495d-864f-21c393a14d42)

**Comment by chazqc** [comment]
Can confirm this exact issue as of yesterday. 

![image](https://github.com/benphelps/homepage/assets/134228185/e18a3699-4d5d-41a8-a9b7-b91edbcdc751)

**Comment by shamoon** [comment]
Hmm, Im not seeing this but certainly related to #1575

Looks like this might only happen with certain responses from the server

**Comment by Inch-high** [comment]
Is there some way to enable debug? Happy to provide logs. As an FYI I'm running on Unraid.

**Comment by shamoon** [comment]
Not so easy to debug / reproduce. Presumably if someone could isolate which URL is causing it and then I could try to hit that same URL, but...

In the meantime, I tried something that Im not sure if it will fix but if anyone would like to test the `main` image 🤞

**Comment by chazqc** [comment]
> Not so easy to debug / reproduce. Presumably if someone could isolate which URL is causing it and then I could try to hit that same URL, but...
> 
> In the meantime, I tried something that Im not sure if it will fix but if anyone would like to test the `main` image 🤞

Still having the same issue unfortunately. 

![image](https://github.com/benphelps/homepage/assets/134228185/0a8e2d03-082b-4693-91a9-14ffe845b59e)

**Comment by hacustom** [comment]
I'm going to start pulling out services 1 by 1 out of my main yaml and see if I can get to a point where it works.

**Comment by hacustom** [comment]
I've removed Home Assistant, Jellyfin, Jellyfin Accounts Go, Jellyseer, Vaultwarden, Bookstack, Tandoor and their Service Widgets, no luck.  I removed the Service Widgets for Radarr, Sonarr, Bazarr and Tdarr, also with no luck.

I have columns in my services.yaml.  Services, Media Tools and Infra.  I had Jellyfin, HA, etc under the Services section along with entries for the 3 main instances of WLED in our house.  I removed the 3 WLED links...and it's been running for 5 minutes now, multiple refreshes, etc.

These are the entries I had for the WLED instances:

- WLED_One:
        href: http://wledone.domain.com
        ping: http://wledone.domain.com
        icon: wled.png
    - WLED_Two:
        href: http://wledtwo.domain.com
        ping: http://wledtwo.domain.com
        icon: wled.png
    - WLED_Three:
        href: http://wledthree.domain.com
        ping: http://wledthree.domain.com
        icon: wled.png


I've obfuscated the hostnames. These 3 hosts are not behind a reverse proxy, they are not exposed to the internet, and their are internal DNS entries setup for each of them on my internal DNS server (Pi-Hole).  

I'm going to start adding my other services back in and see if I can get them all in minus WLED.

**Comment by hacustom** [comment]
K, reloaded my backup services.yaml and deleted the entries for WLED, everything worked great.  I added the entries for WLED back in and removed the ping: lines from each entity...it's still working great.  It appears it was the ping configs for my WLED instances that were causing my problems all of a sudden...not sure why, but I've removed them for now.

**Comment by hacustom** [comment]
So far so good, added the service widgets for Radarr, Sonarr and Prowlarr back in so now my Homepage is fully back up and running!

<img width="914" alt="image" src="https://github.com/benphelps/homepage/assets/99961447/28e93480-7bb1-4404-98a6-56e2c8a4ca5f">

**Comment by shamoon** [comment]
Yea this will only happen when a server returns content encoding of `gzip` or `deflate` and then presumably is returning a malformed (truncated) response. I suspect it's the kind of thing that browsers or other software doesn't mind but the zlib library doesn't tolerate.

Is WLED this: https://kno.wled.ge ? Unfortunately I need something I can e.g. spin up my own version of (or a publicly-accessible server) that does this.

**Comment by shamoon** [comment]
No worries, don’t expose it. Better would be to see if there’s an easy piece of software (dockerized ideally) out there that does this

I’ll poke around when I have some time

**Comment by hacustom** [comment]
Works for me.  If there are diagnostic tools I could use to grab the responses you are looking for, I can do that too.  Would curl or postman help?  I'm not familiar with the issue you are working around but happy to help get you any info you need.  I do this kind of stuff for a living, I enjoy it :)

**Comment by chazqc** [comment]
> I've removed Home Assistant, Jellyfin, Jellyfin Accounts Go, Jellyseer, Vaultwarden, Bookstack, Tandoor and their Service Widgets, no luck. I removed the Service Widgets for Radarr, Sonarr, Bazarr and Tdarr, also with no luck.
> 
> I have columns in my services.yaml. Services, Media Tools and Infra. I had Jellyfin, HA, etc under the Services section along with entries for the 3 main instances of WLED in our house. I removed the 3 WLED links...and it's been running for 5 minutes now, multiple refreshes, etc.
> 
> These are the entries I had for the WLED instances:
> 
>     * WLED_One:
>       href: http://wledone.domain.com
>       ping: http://wledone.domain.com
>       icon: wled.png
>       
>       * WLED_Two:
>         href: http://wledtwo.domain.com
>         ping: http://wledtwo.domain.com
>         icon: wled.png
>       * WLED_Three:
>         href: http://wledthree.domain.com
>         ping: http://wledthree.domain.com
>         icon: wled.png
> 
> 
> I've obfuscated the hostnames. These 3 hosts are not behind a reverse proxy, they are not exposed to the internet, and their are internal DNS entries setup for each of them on my internal DNS server (Pi-Hole).
> 
> I'm going to start adding my other services back in and see if I can get them all in minus WLED.

THANK YOU FOR THIS!! This was my exact issue. Removing the pings to WLED has resolved this issue.

**Comment by SpeakinTelnet** [comment]
Just to add, in my case the culprit was my Asus server iKVM, strangely it only started to crash homepage after I last updated it last week.

**Comment by shamoon** [comment]
Yea a recent change is the culprit, it’s just that I haven’t figured out an easy way to reproduce this (without buying some random LEDs :) and thus, fix it, which I would like to do since it causes an actual crash

**Comment by SpeakinTelnet** [comment]
I was able to resolve the error on my side by adding the "accept-encoding" params and removing the whole block handling the gzip/deflate headers. It's a start but I'm not proficient enough in JS to know if another issue might come from it.

``` javascript
export async function httpProxy(url, params = {}) {
  const constructedUrl = new URL(url);

  let request = null;
  if (constructedUrl.protocol === "https:") {
    const httpsAgent = new https.Agent({
      rejectUnauthorized: false,
    });

    request = httpsRequest(constructedUrl, {
      agent: httpsAgent,
      'accept-encoding': 'gzip,deflate',
      ...params,
    });
```

**Comment by shamoon** [comment]
That is basically reverting https://github.com/benphelps/homepage/pull/1575 so yes, that will fix it but the goal is not to do that...

**Comment by SpeakinTelnet** [comment]
Makes sense, from what I could test it seems that the error really comes from the zlib library, I could handle the same request from python, Julia and curl without issue. 

It's a little late here but I'll check various request libraries tomorrow in case one of them can handle this error.
