### ISSUE TITLE
[Bug] CPU Temp Bar is always essentially full

### ISSUE THREAD

**Issue by bennyd87708** [benphelps/homepage#1619]
### Description

The CPU temperature bar always stays close to mostly full, regardless of the actual CPU temperature.
![image](https://github.com/benphelps/homepage/assets/6503310/ca9669d1-83b9-4d37-ba40-5e99c6b527dd)

### Steps to reproduce

1. Use the temperature widget

### homepage version

v0.6.21

### Installation method

Docker

### Configuration

```yaml
- resources:
    label: Temperature
    cputemp: true
    units: metric
```

### Troubleshooting

Tried fahrenheit and celcius, but both seem to have the same issue regardless of temperature

### Other

If I had to guess from just a quick skim of what appears to be the relevant code: https://github.com/benphelps/homepage/blob/bc2695323c582e9f32671fbe4f6183faf8e17978/src/components/widgets/resources/cputemp.jsx#L40
It looks like the percentage of the bar is being calculated based on the ratio between the main cpu temp and the max cpu temp, which I can only assume would be the hottest core. If true, I argue that calculating the percentage of the temp bar in this way not useful information to convey, as it is always just mostly full. Perhaps it would make more sense to use a flat max temp like 90 degrees celcius or similar.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Temps vary significantly between hardware so we cant just use a static number. Id guess your cpu is reporting a max that is either the same or very close to the current temp. There’s not much we can do if that’s the case, you can check the output yourself

**Comment by LeviSnoot** [comment]
Fair enough, but can we make the min-max values user configurable? That way the default behaviour can stay as it is right now, but if users find it odd, they can at least define their own values.
