### ISSUE TITLE
[Bug] Cannot have more than 1 Deluge widgets

### ISSUE THREAD

**Issue by mmarfil** [benphelps/homepage#1652]
### Description

Title says it all but basically, I'm unable to have 2 Deluge widgets (e.g. Local + Seedbox remotely). The first one takes precedence and even though the title is respected, the widget details are mirrored from the first one set:

<img width="830" alt="CleanShot 2023-07-02 at 11 10 51@2x" src="https://github.com/benphelps/homepage/assets/8507602/02a0de43-0149-483d-84b6-a7a9bbcbaadb">

### Steps to reproduce

Just add 2 different deluge widgets, with of course different urls

### homepage version

v0.6.21 (3e01fc1, Jun 12, 2023)

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Give them different names
