### ISSUE TITLE
[Bug] Proxmox widget doesn't work for latest Proxmox (Proxmox 8.0.3)

### ISSUE THREAD

**Issue by cinderblockgames** [benphelps/homepage#1668]
### Description

```
fields: ["vms", "resources.cpu", "resources.mem"]
```

![image](https://github.com/benphelps/homepage/assets/79210192/3b37a21c-f4ce-4e7e-ba6c-60f276215073)

### Steps to reproduce

Add service widget for Proxmox.

### homepage version

v0.6.20

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please follow the template

**Comment by draeron** [comment]
removing "Privilege Separation" solved this problem, so either fix it or update the widget documentation.
