### ISSUE TITLE
custom background issue

### ISSUE THREAD

**Issue by C8opmBM** [benphelps/homepage#168]
I've successfully mapped the folder for custom images and icons, but every time I rebuild/restart the container, the image is not cached, I am shown the old solid color one. I need to refresh the button. This would not be a problem in itself,  but this also appears in the log every time so I wonder if I do something wrong:

```
Failed to update prerender cache for /index [Error: EACCES: permission denied, open '/app/.next/server/pages/index.html'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/.next/server/pages/index.html'
}
```

**Comment by benphelps** [comment]
Make sure you're running the latest version, and see if it still gives this error.

**Comment by C8opmBM** [comment]
Running the :latest tag, I still have the same behaviour, but only the first time after I recreate the container.
It spawns with solid color background and no error log. After I hit refresh button (down), the background changes successfully  and the docker log shows the above error.

**Comment by bat1939** [comment]
I am also having an issue with my custom background image. I mounted the drive and moved my .jpg file to the folder. I see it in the docker cli but it doesnt load on the page.

**Comment by benphelps** [comment]
You need to restart the container any time you add new images, this is a limitation of the Next.js static site server.

**Comment by stayupthetree** [comment]
> You need to restart the container any time you add new images, this is a limitation of the Next.js static site server.

Can this be added into the docs? This little nugget of info would've prevented so much trouble shooting trying to figure out why my images weren't working.

**Comment by shamoon** [comment]
> Can this be added into the docs? This little nugget of info would've prevented so much trouble shooting trying to figure out why my images weren't working. 

Sure
