### ISSUE TITLE
[Bug] Security Issue with Docker Socket Proxy example 

### ISSUE THREAD

**Issue by Gugi264** [benphelps/homepage#1686]
### Description

The example for [Docker Socket Proxy ](https://gethomepage.dev/en/configs/docker/#using-docker-socket-proxy) opens it for access from the internet, so everyone can run docker commands remotely. Which obviously is a big security risk.

Change example compose file to:
```
ports:
        - 127.0.0.1:2375:2375
```
With this change the docker-compose still works perfectly fine.

### Steps to reproduce

Documentation problem

### homepage version

latest

### Installation method

Docker

### Troubleshooting

Documentation issue

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
- This is about a bug
- This is not the docs repo
- It is the responsibility of the user to ensure they setup the socket-proxy container safely and that project clearly recommends you don't expose it to the internet, in which case this is not an issue.
- Feel free to PR the docs with a link to their security notes.

**Comment by shamoon** [comment]
Sorry I see why you opened it here because of the compose file, that would be fine

**Comment by Gugi264** [comment]
- This is not the docs repo

  Did not know there was one. Just wanted to help point out an obvious security issue.
  
- It is the responsibility of the user to ensure they setup the socket-proxy container safely and that project clearly recommends you don't expose it to the internet, in which case this is not an issue.

 Fair point. But the socket-proxy also only exports the port to localhost and not the internet. Also I would consider it best practice to not introduce security flaws with the documentation for no reason.
 
- Feel free to PR the docs with a link to their security notes.

 If you do not find it important enough to fix it because I posted in on the wrong bug tracker, that's fine. It's also not important enough for me to do everything correctly to help prevent security issues.

**Comment by shamoon** [comment]
Edit: nope, not here

**Comment by shamoon** [comment]
Yes sorry for the curt reply. I already fixed it, thanks.
