### ISSUE TITLE
[Bug] Logo oversized in 0.6.22

### ISSUE THREAD

**Issue by Fufs** [benphelps/homepage#1697]
### Description

The homepage logo is suddenly giant after update.

![image](https://github.com/benphelps/homepage/assets/42976807/224984ef-9073-40b5-b4a7-4bc9bb53b8e0)

### Steps to reproduce

1. Update to v0.6.22
2. Go to your homepage

### homepage version

v0.6.22

### Installation method

Docker

### Configuration

```yaml
in widgets.yaml

- logo:
...
```

in settings.yaml
```yaml
...
headerStyle: boxed
...
```

### Troubleshooting

Not applicable

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
https://github.com/benphelps/homepage/pull/16031
