### ISSUE TITLE
v.0.6.23 Release breaks service widgets and layout

### ISSUE THREAD

**Issue by jaytrickett1** [benphelps/homepage#1702]
### Description

I just updated to version 0.6.23, and the page now has a number of problems:
1. every service widget gives a widget error: "TypeError: m.some is not a function"
2. The layout is broken. Every category is now a single column
3. My header style isn't working anymore
4. When I go to my Homepage, it initially appears as a spinning wheel indefinitely. It only opens up when I hit refresh.
I've attached a screenshot
![screenshot](https://github.com/benphelps/homepage/assets/22974933/cb331269-2d80-41d7-97ae-b3a72dc3c1ef)

### Steps to reproduce

1. browse to [my Homepage URL]

### homepage version

v0.6.23 (82c54f1, Jul 20, 2023)

### Installation method

Docker

### Container Logs

Logfile just lists a series of "(error: undefined)" entries. No additional detail.

### Browser Logs

Logs show reference to "m.some" in js code, which appears to be a function call (I'm not much of a coder).

### Troubleshooting

1. Confirmed no trailing "/"
2. Ping Test:
USER@SERVER:/opt/docker$ sudo docker exec homepage ping nzbget
PING nzbget (IPADDR): 56 data bytes
64 bytes from IPADDR: seq=0 ttl=64 time=0.257 ms
64 bytes from IPADDR: seq=1 ttl=64 time=0.109 ms
64 bytes from IPADDR: seq=2 ttl=64 time=0.099 ms
64 bytes from IPADDR: seq=3 ttl=64 time=0.111 ms
64 bytes from IPADDR: seq=4 ttl=64 time=0.111 ms
64 bytes from IPADDR: seq=5 ttl=64 time=0.103 ms
^C

3. Curl Test:
USER@SERVER:/opt/docker$ sudo docker exec homepage curl nzbget:6789/xmlrpc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<?xml version="1.0"?>
<methodResponse>
<fault><value><struct>
<member><name>faultCode</name><value><i4>1</i4></value></member>
<member><name>faultString</name><value><string>Invalid procedure</string></value></member>
</struct>
</value></fault>
100   262  100   262    0     0   267k      0 --:--:-- --:--:-- --:--:--  255k

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Can you copy & paste the full output of the error?

**Comment by shamoon** [comment]
This could be related to https://github.com/benphelps/homepage/pull/1560 but I cant reproduce.

<img width="753" alt="Screenshot 2023-07-20 at 12 12 55 PM" src="https://github.com/benphelps/homepage/assets/4887959/205adb8d-2338-447a-ba18-68ef600575f7">

Can you post your configuration as well?

**Comment by shamoon** [comment]
Also try re-creating the container.

**Comment by LostInFlux** [comment]
Same issue, for Plex in particular. Also doesn't seem to be pulling in background image/config files.

![image](https://github.com/benphelps/homepage/assets/140139785/8a9aaaff-b4cf-415d-bfe2-96213ba1af4c)

Have tried re-creating the docker container.

Only output in the Docker logs:
`Listening on port 3000`

Output from error within the dashboard itself:

```
Something went wrong.
TypeError: m.some is not a function

u@http://192.168.1.200:3000/_next/static/chunks/pages/index-ff58e1dddecc35a1.js:1:3888
i@http://192.168.1.200:3000/_next/static/chunks/8140.f4c307457b935f2a.js:1:1130
9571/v/h<@http://192.168.1.200:3000/_next/static/chunks/3230-b883356d05e3ebb1.js:1:35307
n@http://192.168.1.200:3000/_next/static/chunks/pages/index-ff58e1dddecc35a1.js:1:13883
E@http://192.168.1.200:3000/_next/static/chunks/pages/index-ff58e1dddecc35a1.js:1:25547
div
li
D@http://192.168.1.200:3000/_next/static/chunks/pages/index-ff58e1dddecc35a1.js:1:28553
ul
T@http://192.168.1.200:3000/_next/static/chunks/pages/index-ff58e1dddecc35a1.js:1:32183
div
4966/C<@http://192.168.1.200:3000/_next/static/chunks/3230-b883356d05e3ebb1.js:1:43931
div
l@http://192.168.1.200:3000/_next/static/chunks/3230-b883356d05e3ebb1.js:1:69973
3966/M<@http://192.168.1.200:3000/_next/static/chunks/3230-b883356d05e3ebb1.js:1:62758
3966/k<@http://192.168.1.200:3000/_next/static/chunks/3230-b883356d05e3ebb1.js:1:61615
l@http://192.168.1.200:3000/_next/static/chunks/3230-b883356d05e3ebb1.js:1:69973
4966/L<@http://192.168.1.200:3000/_next/static/chunks/3230-b883356d05e3ebb1.js:1:41888
div
z@http://192.168.1.200:3000/_next/static/chunks/pages/index-ff58e1dddecc35a1.js:1:32564
div
div
se@http://192.168.1.200:3000/_next/static/chunks/pages/index-ff58e1dddecc35a1.js:1:48493
n@http://192.168.1.200:3000/_next/static/chunks/pages/index-ff58e1dddecc35a1.js:1:13883
6747/Y<@http://192.168.1.200:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:88960
oe@http://192.168.1.200:3000/_next/static/chunks/pages/index-ff58e1dddecc35a1.js:1:46500
div
div
div
de@http://192.168.1.200:3000/_next/static/chunks/pages/index-ff58e1dddecc35a1.js:1:52734
a@http://192.168.1.200:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:15089
s@http://192.168.1.200:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:15647
u@http://192.168.1.200:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:14522
6747/Y<@http://192.168.1.200:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:88960
4384/t.default<@http://192.168.1.200:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:13803
l@http://192.168.1.200:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:1460
n@http://192.168.1.200:3000/_next/static/chunks/pages/_app-8985fbb6b5c333d7.js:1:6031
r@http://192.168.1.200:3000/_next/static/chunks/main-28f0bf55ce641aab.js:1:6947
Y@http://192.168.1.200:3000/_next/static/chunks/main-28f0bf55ce641aab.js:1:9184
ie@http://192.168.1.200:3000/_next/static/chunks/main-28f0bf55ce641aab.js:1:11824
```

**Comment by LostInFlux** [comment]
Confirming v0.6.22 also shows the same issues. v0.6.21 works as intended.

**Comment by shamoon** [comment]
A can you post your config

**Comment by LostInFlux** [comment]
Yep I can do, but I'm a bit of a noob - just to be clear are you after the docker-compose setup, or some particular file within /config like settings.yaml?

**Comment by shamoon** [comment]
Whatever you used to setup the plex widget, either docker labels or the entry in your services.yaml

**Comment by LostInFlux** [comment]
I've just noticed there's a space after homepage.widget.url=. I'll try removing the space to see if that makes a difference.

```
    labels:
      - homepage.group=Media 
      - homepage.name=Plex 
      - homepage.icon=plex.png 
      - homepage.href=http://192.168.1.200:32400 
      - homepage.description=Stream media 
      - homepage.widget.type=plex 
      - homepage.widget.url= http://plex:32400 #http://emby.home
      - homepage.widget.key=${PLEX_TOKEN} #yourembyapikeyhere
      - homepage.widget.fields=["streams", "movies", "tv"] # optional
      - homepage.weight=1 
      - homepage.server=my-docker 
      - homepage.container=plex 
```

**Comment by shamoon** [comment]
Got it thanks

**Comment by shamoon** [comment]
The image is [building right now](https://github.com/benphelps/homepage/actions/runs/5619173864) but when its complete you can test this out with the `main` image

**Comment by ipawelek** [comment]
This resolved the problem for me.

**Comment by LostInFlux** [comment]
Confirming the main build fixed the issue and the background image + widget render correctly 

Thanks for jumping on this so quickly!!! 👏 

![image](https://github.com/benphelps/homepage/assets/140139785/7b900fd2-c84c-403f-afb5-faf8c81810d2)
