### ISSUE TITLE
[Bug] Icon/Greeting Spacing Missing

### ISSUE THREAD

**Issue by My-Random-Thoughts** [benphelps/homepage#1728]
### Description

There is no spacing between the page icon and greeting message

![image](https://github.com/benphelps/homepage/assets/21334396/47ea9b57-b030-4278-b60f-e318fb6ac3b7)

### Steps to reproduce

    - logo:
        icon: homepage

    - greeting:
        text_size: 4xl
        text:   Network Management Dashboard

### homepage version

v0.6.23 (82c54f1, Jul 20, 2023)

### Installation method

Docker

### Troubleshooting

N/A

### Other

I feel that a 10-15px gap should be between title bar widgets.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
#1720
