### ISSUE TITLE
[Bug] PiHole Service Widget throws TypeError

### ISSUE THREAD

**Issue by dankao** [benphelps/homepage#1731]
### Description

PiHole: Docker Tag [2023.05.2](https://github.com/pi-hole/docker-pi-hole/releases/2023.05.2) Pi-hole [v5.17.1](https://github.com/pi-hole/pi-hole/releases/v5.17.1) FTL [v5.23](https://github.com/pi-hole/FTL/releases/v5.23) Web Interface [v5.20.1](https://github.com/pi-hole/AdminLTE/releases/v5.20.1)
homepage: v0.6.23 (82c54f1, Jul 19, 2023)

When attempting to add the Service Widget for PiHole, an error occurs. The API is not password protected (public). I receive the error `TypeError: Cannot read properties of undefined (reading 'toPrecision')`

![image](https://github.com/benphelps/homepage/assets/18122316/d014ccac-ec7e-4973-a010-f928dfd06572)

### Steps to reproduce

1. Add Service Widget as documented at https://gethomepage.dev/en/services/pihole/.
2. Try to see Service Widget.
3. Gives error.

### homepage version

v0.6.23 (82c54f1, Jul 19, 2023)

### Installation method

Docker

### Troubleshooting

I've tested to make sure the API is open/public and it responds `{"status":"enabled"}` at the `api.php?status` URL and the `api.php?summaryRaw&auth=` URL returns proper JSON as follow:

`{"domains_being_blocked":673240,"dns_queries_today":232660,"ads_blocked_today":17212,"ads_percentage_today":7.39792,"unique_domains":32081,"queries_forwarded":43327,"queries_cached":171043,"clients_ever_seen":47,"unique_clients":38,"dns_queries_all_types":232660,"reply_UNKNOWN":832,"reply_NODATA":52446,"reply_NXDOMAIN":58855,"reply_CNAME":21860,"reply_IP":96201,"reply_DOMAIN":722,"reply_RRNAME":2,"reply_SERVFAIL":675,"reply_REFUSED":0,"reply_NOTIMP":0,"reply_OTHER":0,"reply_DNSSEC":0,"reply_NONE":0,"reply_BLOB":1067,"dns_queries_all_replies":232660,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1690088109,"relative":{"days":4,"hours":16,"minutes":42}}}`

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Just to clarify, did you test the pihole api from inside the homepage container?

**Comment by dankao** [comment]
> Just to clarify, did you test the pihole api from inside the homepage container?

Ah. In the container it was just sending back `[]` empty square brackets. I then gave it the API key and it started to work. Sorry for the troubles. Thanks!
