### ISSUE TITLE
[Bug] UrBackup widget

### ISSUE THREAD

**Issue by Nonoss117** [benphelps/homepage#1766]
### Description

Thanks for the widget, I like it. Just a little thing.

If an UrBackup client is configured with the flag "image_disabled = true", the widget consider this client as outdated. I think it should'nt be the case.
The detailled discussion can be read here: https://github.com/benphelps/homepage/discussions/1733#discussion-5452063

### Steps to reproduce

1. configure an UrBackup client with "image_disabled = true"
2. check the visual of the widget for outdated clients

### homepage version

main (fab9750, 3 août 2023)

### Installation method

Docker

### Browser Logs

response of the browser receives from the homepage backend:

Désactiver le cache
2 requêtes
2,30 Ko / 0 o transférés
Terminé en : 13,93 s
DOMContentLoaded: 400 ms
load: 2,35 s

clientStatuses [ {…}, {…}, {…}, {…}, {…} ]
0 Object { client_version_string: "2.5.23", file_ok: true, id: 2, … }
client_version_string "2.5.23"
delete_pending ""
file_ok true
groupname ""
id 2
image_disabled true
image_ok false
ip "-"
last_filebackup_issues 0
lastbackup 1690881534
lastbackup_image 0
lastseen 1690897265
name "LENOVO-MAMAN"
online false
os_simple "windows"
os_version_string "Microsoft Windows 11 Famille (build 22621), 64-bit"
processes []
status 0
uid "hwYRGvrZNdsYiDle"
1 Object { client_version_string: "2.5.23", file_ok: true, id: 1, … }
client_version_string "2.5.23"
delete_pending ""
file_ok true
groupname ""
id 1
image_disabled true
image_ok false
ip "192.168.1.32"
last_filebackup_issues 0
lastbackup 1690923588
lastbackup_image 0
lastseen 1690952184
name "PORT-PAPA"
online true
os_simple "windows"
os_version_string "Microsoft Windows 11 Professionnel (build 22621), 64 bits"
processes []
status 0
uid "txTysjhP5bpEjCuD"
2 Object { client_version_string: "2.5.24", file_ok: true, id: 10, … }
client_version_string "2.5.24"
delete_pending ""
file_ok true
groupname ""
id 10
image_disabled true
image_not_supported true
image_ok false
ip "172.18.0.39"
last_filebackup_issues 0
lastbackup 1690908285
lastbackup_image 0
lastseen 1690952184
name "UNRAID_ADMINISTR"
online true
os_simple "linux"
os_version_string "Debian GNU/Linux 10 (buster); Kernel 6.1.38-Unraid x86_64"
processes []
status 0
uid "zdCAV2bZCcDIDAk5"
3 Object { client_version_string: "2.5.24", file_ok: true, id: 9, … }
client_version_string "2.5.24"
delete_pending ""
file_ok true
groupname ""
id 9
image_disabled true
image_not_supported true
image_ok false
ip "172.18.0.40"
last_filebackup_issues 0
lastbackup 1690788393
lastbackup_image 0
lastseen 1690952184
name "UNRAID_APPDATA"
online true
os_simple "linux"
os_version_string "Debian GNU/Linux 10 (buster); Kernel 6.1.38-Unraid x86_64"
processes []
status 0
uid "W0MvPDWvO0wZiXuj"
4 Object { client_version_string: "2.5.24", file_ok: true, id: 7, … }
client_version_string "2.5.24"
delete_pending ""
file_ok true
groupname ""
id 7
image_disabled true
image_not_supported true
image_ok false
ip "172.18.0.41"
last_filebackup_issues 0
lastbackup 1690836147
lastbackup_image 0
lastseen 1690952184
name "UNRAID_PHOTOS"
online true
os_simple "linux"
os_version_string "Debian GNU/Linux 10 (buster); Kernel 6.1.38-Unraid x86_64"
processes []
status 0
uid "6DQbCMFpT6i2Y0FU"
diskUsage false
maxDays 500

### Troubleshooting

see browser output

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Seems straightforward but since Im basing the fix on sample data provided it would be good to verify this works, you (or anyone else) can do so with the `main` image [once the current build finishes](https://github.com/benphelps/homepage/actions/runs/5752936257)

If not, obviously we can re-address.

**Comment by Nonoss117** [comment]
Thanks @shamoon the widget is ok with my UrBackup configuration

![image](https://github.com/benphelps/homepage/assets/79055577/7b159e2a-9ff6-4b78-88b6-e395bd596fe2)
