### ISSUE TITLE
[Bug] Image latest not found

### ISSUE THREAD

**Issue by fferraro87** [benphelps/homepage#1778]
### Description

Hi,
i'm tryng to use you image, but 
ERROR: Error: image benphelps/homepage:latest not found

### Steps to reproduce

docker-compose up -d
```
Pulling homepage (ghcr.io/benphelps/homepage:latest)...
Trying to pull repository ghcr.io/benphelps/homepage ... 
Pulling repository ghcr.io/benphelps/homepage
ERROR: Error: image benphelps/homepage:latest not found
```

### homepage version

v0.6.28

### Installation method

Docker

### Troubleshooting

```
Pulling homepage (ghcr.io/benphelps/homepage:latest)...
Trying to pull repository ghcr.io/benphelps/homepage ... 
Pulling repository ghcr.io/benphelps/homepage
ERROR: Error: image benphelps/homepage:latest not found
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by Gugi264** [comment]
Maybe try again? Works for me on two different machines

**Comment by fferraro87** [comment]
ok right from another machine it works i'm closing it
