### ISSUE TITLE
[Feature Request] set width of services column

### ISSUE THREAD

**Issue by GertJanH** [benphelps/homepage#179]
I would like to have an option to be able to set the width of the column.

see screenshot, Network monitoring same width as home lab.

maybe width 1,2,3 and 4
![2022-09-15 234942](https://user-images.githubusercontent.com/22355768/190515259-8e997a78-d09c-4005-85f2-02cd494aef07.jpg)

**Comment by LilTrublMakr** [comment]
This could possibly tie in with  #154

**Comment by benphelps** [comment]
> This could possibly tie in with #154

Possibly, and it's already been implemented to some degree, see here: https://github.com/benphelps/homepage/wiki/Settings#layout

**Comment by GertJanH** [comment]
I wanted something more like this, that the bottom 2 columns are the same width as the top row
![2022-09-16](https://user-images.githubusercontent.com/22355768/190633104-fa93cd8f-f7f2-42c8-9d40-71592ccf9560.jpg)

this is a edit in paint

**Comment by benphelps** [comment]
I see, that could be done as well, I'll put this in with the rest of the layout options group request

**Comment by benphelps** [comment]
In consolidation of layout and presentation issues, please use #235 to continue discussion.  This issue will be noted in the continuing thread.
