### ISSUE TITLE
[Bug] Bookmarks with url containing "@" symbol fail to render

### ISSUE THREAD

**Issue by reederda** [benphelps/homepage#1798]
### Description

If a bookmark address contains an "@" symbol (such as for a Mastodon user like https://mastodon.social/@Mastodon) the bookmark fails to render with an error.
![image](https://github.com/benphelps/homepage/assets/7991086/5d89a005-719f-497e-88e8-bf80f1efc3ac)

### Steps to reproduce

1. Open bookmarks.yaml for editing
2. Add an href for https://mastodon.social/@Mastodon
3. Save, and refresh the webpage

### homepage version

v0.6.28

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Im gonna guess your config is off

<img width="1126" alt="Screenshot 2023-08-10 at 7 37 47 PM" src="https://github.com/benphelps/homepage/assets/4887959/ab390668-909f-4be8-ba74-69d8702d62ab">
