### ISSUE TITLE
[Bug] Gluetun ghost widget on screen

### ISSUE THREAD

**Issue by C0ffeL0Ve** [benphelps/homepage#1815]
### Description

Yesterday while I was configuring Gluetun widget url this "ghost app" appeared and won't go away even with a docker restart and a blank services.yaml file.

Screenshot with everything in dashboard;
https://ibb.co/HGD4Ppj
Blank services.yaml;
https://ibb.co/GkG2cwP
When Inspecting(F12) the API error button, it shows this(browser);
https://ibb.co/7z2RL28

### Steps to reproduce

1. Go to services.yaml
2. Duplicate another app(deluge) config and insert on top
3. edit duplicated app to gluetun proprieties and widget and put wrong URL lots of time (with an wrong container name configured(deluge))
4. When i saw the error i deleted the app config that i made and then i discovered that the widget wouldn't go away
5. after 2-3 hours i did everything again and configured my gluetun widget to work and created its own category on top

### homepage version

v0.6.28 (63a5622, Aug 4, 2023)

### Installation method

Docker

### Troubleshooting

https://pastecode.io/s/rq4j3a4n

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Im not clear if youre saying you solved this in the end but I'd bet a container re-create (not restart) would do it

**Comment by C0ffeL0Ve** [comment]
sorry for my bad explaination, but upon recreating the container the bug still shows, i tried recreating the config files from 0 but when i add my  ip address on docker.yaml to connect to my dockerproxy the API error shows again, even if i didn't configure anything on services.yaml

**Comment by shamoon** [comment]
I honestly cannot follow your steps to reproduce. If reproducing this requires erroneous entries in the config then that’s kind of the answer. If it happens with a valid config (and / or docker labels on any of your containers), please post it here.
