### ISSUE TITLE
[Bug] Set weight in docker labels

### ISSUE THREAD

**Issue by Emporea** [benphelps/homepage#1860]
### Description

I described it in this question already, but now i am just more confused if its even impemented or not.

https://github.com/benphelps/homepage/discussions/1805

I wanted to set weight to labels of docker containers directly in a docker-compose file. The person who answered on my question said its implemented, but i cant get it to work.

### Steps to reproduce

https://github.com/benphelps/homepage/discussions/1805

### homepage version

0.6.19 docker

### Installation method

Docker

### Troubleshooting

https://github.com/benphelps/homepage/discussions/1805

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
You didn’t really provide much detail but this is implemented and I confirmed is working fine 

https://github.com/jameswynn/homepage/blob/main/src/utils/config/api-response.js#L19


```
- meaile
...
- calibre-web
...
```
<img width="749" alt="Screenshot 2023-08-26 at 12 10 43 PM" src="https://github.com/benphelps/homepage/assets/4887959/9fcfde83-316b-4f86-9d61-3fe6c0252cf7">


```
- meaile
...
    homepage.weight=1
- calibre-web
...
    homepage.weight=2
```
<img width="745" alt="Screenshot 2023-08-26 at 12 18 56 PM" src="https://github.com/benphelps/homepage/assets/4887959/90129f00-e579-4c0f-9510-9b9a6e662a1d">
