### ISSUE TITLE
[Bug] Kavita Widget not available

### ISSUE THREAD

**Issue by InnocentRain** [benphelps/homepage#1880]
### Description

The Kavita Widget is not being displayed. 
Error: "Missing Widget Type: kavita"

### Steps to reproduce

Add widget "kavita" to service

- Kavita:
    icon: kavita
    widget:
            type: kavita
            url: kavita.url
            username: Username123
            password: Passw0rd

### homepage version

v0.6.29

### Installation method

Docker

### Troubleshooting

As there is no actual error the only troubleshooting i did was verify that the service widget was indeed supported which it is, see https://gethomepage.dev/en/services/kavita/ and that it worked with other widget types.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
<img width="754" alt="Screenshot 2023-08-29 at 6 50 57 AM" src="https://github.com/benphelps/homepage/assets/4887959/0e6b9ed1-a6db-4526-9fd0-46775f6b63dc">

Make sure you updated properly

**Comment by InnocentRain** [comment]
A bit embarassing but you were right, i did indeed miss to update the image manually after automatic updates failed.
Thank you for your help!!
