### ISSUE TITLE
[Feature Request] Deluge widget

### ISSUE THREAD

**Issue by Dictynna-PHA** [benphelps/homepage#190]
Not urgent but would be nice to have a deluge BitTorrent widget.

Great work so far Ben, I have homepage running alongside dashy and it feels somewhat faster/lighter.

**Comment by LostInInaka** [comment]
Was just going to come in and ask for the same thing!

**Comment by trythatagain** [comment]
Same here, I use both qbittornet and deluge, so would be nice to see both widgets.

**Comment by irlam** [comment]
Any update on this please Ben?

**Comment by BHMath** [comment]
I'd like it too please

**Comment by Nindohana** [comment]
+1 here

**Comment by lsaadeh** [comment]
+1

**Comment by gonjat** [comment]
+10 ;-)

**Comment by ido1990** [comment]
+1

**Comment by geodose** [comment]
also interested in Deluge support, +1!

**Comment by tezgno** [comment]
Also interested in support. +1
