### ISSUE TITLE
When adding openmediavault intgreation, homepage shows a "Missing Widget Type: openmediavault" error[Bug] 

### ISSUE THREAD

**Issue by tj31moll** [benphelps/homepage#1912]
### Description

I configured the plugin/integration as indicated in the documents:

- OpenMediaVault:
    - Services:
        widget:
          type: openmediavault
          url: http://192.168.1.33
          username: admin
          password: 123
          method: services.getStatus
    - S.M.A.R.T.:
        widget:
          type: openmediavault
          url: http://192.168.1.33
          username: admin
          password: 123
          method: smart.getListBg
    - Downloader Plugin:
        widget:
          type: openmediavault
          url: http://192.168.1.33
          username: admin
          password: 123
          method: downloader.getDownloadList

### Steps to reproduce

Utilize documents to config in services.yml.

### homepage version

v0.6.29

### Installation method

Docker

### Troubleshooting

N/A

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Make sure you’ve updated your install properly

https://github.com/benphelps/homepage/blob/9713a16e1fad9ae52fb6bceb262d0eee9f857698/src/widgets/components.js#L66

**Comment by tj31moll** [comment]
thanks. I had sworn i pulled the most recentimage but it was very old. All good now. Appreciate it.
