### ISSUE TITLE
[Bug] Layout regression (4 col x 1 row -> 3 col x 2 rows)

### ISSUE THREAD

**Issue by tikibozo** [benphelps/homepage#1919]
### Description

I have a script to pull container updates each night, and last night I pulled a homepage update that regressed my layout from 4 columns (in one row) to 3 columns and the 4th column in a 2nd row (regardless of browser width).

I'm not sure which information is relevant - but I happen to have a sanitized mirror of my config [here](https://github.com/tikibozo/plexarr/tree/main/media/homepage). You can see the expected layout on the [main page](https://github.com/tikibozo/plexarr) of the repo.

Happy to provide additional info, thanks for reading.

### Steps to reproduce

Update container, reload page.

### homepage version

latest/ef97761081f7

### Installation method

Docker

### Configuration

```yaml
Seeing the problem in main/latest -- 0.6.29 does not have the problem.

ghcr.io/benphelps/homepage              main                ef97761081f7   18 hours ago    220MB
ghcr.io/benphelps/homepage              v0.6.29             6714b52cb966   11 days ago     220MB
```

### Troubleshooting

Reload with v0.6.9 and refresh, no issue, reload with latest, see issue.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Can you send a screenshot of what it looks like now? How about if you remove your [`layout`](https://github.com/tikibozo/plexarr/blob/b2199c670c72ec950587d8d5ab6ce3f72d2b9e34/media/homepage/settings.yaml#L9) block completely? Which, btw, doesnt need the `style: column` (thats default)

But with minimal reproducer Im not seeing this

**Comment by tikibozo** [comment]
Removing my style block resolved it, thank you! I had played with a few layouts before arriving back at... apparently what you do by default haha.
