### ISSUE TITLE
[Bug] JDownloader Widget Remaining Always the Same

### ISSUE THREAD

**Issue by L4ma** [benphelps/homepage#1926]
### Description

Hi,
I have just inserted the widget for JDownloader and noticed that the "Remaining" field always remains the same. It does not adapt to the downloads or it does not become less.

![Bildschirmfoto 2023-09-08 um 11 47 06](https://github.com/benphelps/homepage/assets/26965333/2f0c5077-4012-4c5b-9b7b-bc1185fe5496)

### Steps to reproduce

Add the JDownloader widget and download something

### homepage version

v0.6.29

### Installation method

Docker

### Troubleshooting

I didn't make a mistake with this topic, because I only have to enter the login data for the widget and the connection works. That's why I can see the rest. 

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by benphelps** [comment]
The standard widget does not refresh on its own automatically.  It'll fetch the data once when the page is rendered and then again any time the page gains focus.

If you want to force a widget to refresh automatically, you can set the `refreshInterval` property for that widget.

```yaml
widget:
    type: deluge
    url: http://172.16.1.10:8112
    fields: ["download", "upload"]
    refreshInterval: 1000
```

**Comment by L4ma** [comment]
Thanks for the tip, but all the other fields like "Speed" or "Size" work. The only field that does not refresh is really "Remaining". 
I have now added a refreshInterval anyway and see if it works. 

I'll post an update here in a few minutes.

**Comment by L4ma** [comment]
Update: 
Unfortunately, it still does not work. Size, queue, speed change but "remaining" remains permanently the same or always changes with the "size". I don't know if it has anything to do with this, but I suspect that it retrieves the same data for both fields.

**Comment by benphelps** [comment]
Does look like a bug indeed.  I don't have jDownloader, but I'm pretty sure I can fix it.

**Comment by L4ma** [comment]
Thank you!
