### ISSUE TITLE
[Feature Request] Custom CSS

### ISSUE THREAD

**Issue by AmadeusGraves** [benphelps/homepage#193]
**Is your feature request related to a service? Please describe.**
Apart from the .yml files that exist in the configuration folder, a css class could also be instantiated to allow editing of the page style. This way the developer will be more free from design issues like on certain wallpapers with certain colours, it is not possible to read the data displayed on the screen.

**Is your feature request related to a problem? Please describe.**
On certain wallpapers with certain colours, it is not possible to read the data displayed on the screen.

**Additional context**
![image](https://user-images.githubusercontent.com/18572939/190837977-839c83e4-9a58-4169-a16c-1c87d9cb3756.png)

**Comment by benphelps** [comment]
In consolidation of layout and presentation issues, please use #235 to continue discussion.  This issue will be noted in the continuing thread.
