### ISSUE TITLE
[Bug] Plex Widget Too Large

### ISSUE THREAD

**Issue by x86txt** [benphelps/homepage#1942]
### Description

The Plex widget drops too far to the bottom, throwing off the visual balance of all the other widgets. Would it be possible to just change the text to say either "Active" or "Streams" so the text doesn't wrap, causing the widget's space to drop down so low?

![image](https://github.com/benphelps/homepage/assets/34278354/fbd4075c-2ebb-412f-8279-a0c80b62371c)

### Steps to reproduce

Add Plex widget, align it beside any of the other widgets.

### homepage version

v0.6.29 (fc7e73e, Aug 26, 2023)

### Installation method

Docker

### Troubleshooting

N/A

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by Jaxel** [comment]
The problem is the words "Active Streams". The word "active" is extraneous and not needed. Should just be "streams"

**Comment by shamoon** [comment]
There are FR to have equal height, otherwise things are dynamic. Make your screen wider and this is "solved"

**Comment by Jaxel** [comment]
Personally, I use Greasemonkey/Tampermonkey to add the following CSS to my Homepage:

```
      body {
        white-space: nowrap;
      }
```

This stops all line-breaks, and makes the entire system look better.
