### ISSUE TITLE
Container exits after sometime

### ISSUE THREAD

**Issue by Coggi** [benphelps/homepage#195]
Hi,

i've got the homepage set up inside portainer.
Everything works but suddenly after a while i find the container stopped.
Here's the log :

`  500,

  Error: socket hang up

      at connResetException (node:internal/errors:711:14)

      at Socket.socketOnEnd (node:_http_client:518:23)

      at Socket.emit (node:events:525:35)

      at endReadableNT (node:internal/streams/readable:1359:12)

      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {

    code: 'ECONNRESET'

  }

]

[

  500,

  Error: socket hang up

      at connResetException (node:internal/errors:711:14)

      at Socket.socketOnEnd (node:_http_client:518:23)

      at Socket.emit (node:events:525:35)

      at endReadableNT (node:internal/streams/readable:1359:12)

      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {

    code: 'ECONNRESET'

  }

]

[

  500,

  Error: read ECONNRESET

      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {

    errno: -104,

    code: 'ECONNRESET',

    syscall: 'read'

  }

]`

Thank you

**Comment by benphelps** [comment]
These errors don't help at all to understand what the problem could be.

What device are you running it on and what tag are you pulling from?

**Comment by Coggi** [comment]
Sorry

It's running on a raspberry pi 4 and pulling from the main tag

**Comment by benphelps** [comment]
Pull from `latest` as `main` can have bugs, it's where live development happens.

**Comment by Coggi** [comment]
ok, pulled from latest.

I'll report back if the issue arise again. Thanks

On a side note, every time I restart the container the first time I access the homepage some settings are not loaded it seems, like the title or the background color sometimes. If I manually press the refresh button in the bottom right of the page then it loads correctly.

**Comment by Coggi** [comment]
Can confirm it happened again today with the latest tag.
This morning i found the container exited again.

Is there anywhere I can look for logs to see what went wrong and provide some info?

Thanks

**Comment by benphelps** [comment]
All logs are sent to the containers logs.

I would need to see the full logs, formatted correct, to even start go make guesses.

**Comment by Coggi** [comment]
This morning found stopped again, here's what portainer says about it :

![immagine](https://user-images.githubusercontent.com/10145448/190984680-b863bb77-39ed-4022-85a9-f800bf1ef73c.png)
![immagine](https://user-images.githubusercontent.com/10145448/190984742-17194210-a6e7-48fc-8bdd-c36bbd6200f6.png)

Don't know if this can be of any help, if not please let me know how I can extract more logs or something that can point to the solution and i'll be glad to help

Thanks

**Comment by JazzFisch** [comment]
Can you share your docker-compose.yml or docker run command?

**Comment by Coggi** [comment]
Sure, i'm using compose inside portainer, here it is : 

**version: '3.3'
services:
    homepage:
        image: ghcr.io/benphelps/homepage:latest
        container_name: homepage
        ports:
            - 5555:3000
        volumes:
            - /configs/homepage/config:/app/config
            - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations**

**Comment by JazzFisch** [comment]
@Coggi there's been some logging improvements in the latest release.  Can you check your config/logs folder for homepage.log and see if there is any additional information there the next time this occurs?

**Comment by xenogear74** [comment]
@JazzFisch btw I've found the same errors in my logs:

```
 [2022-09-24T21:47:28.042Z] error: [
  500,
  Error: socket hang up
      at connResetException (node:internal/errors:711:14)
      at Socket.socketOnEnd (node:_http_client:518:23)
      at Socket.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  }
]
[2022-09-24T21:47:28.168Z] error: [
  500,
  Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
]
```
Per your suggestion I also find the following in my logs: 
```
[2022-09-24T21:47:34.672Z] error: Failed to discover services, please check docker.yaml for errors or remove example entries.
[2022-09-24T21:47:34.673Z] error: undefined
```
I went into the docker.yaml and found I hadn't commented out the IP portion. It's now commented out with just the socket uncommented. I'll report back if the stop happens again (the only way for me to fix is to recreate the container) but figured I'd chime in since I'm seeing similar errors. For reference my docker.yaml now shows:

```
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Docker-Integration

#my-docker:
  #host: 127.0.0.1
  #port: 2375

my-local-docker:
  socket: /var/run/docker.sock
```

**Comment by Coggi** [comment]
@JazzFisch Monitored the situation for a couple days, the issue still persists (i'm on 3.71)

Same behaviour as always, checked homepage.log inside logs folder but it is completely empty..

**Comment by shamoon** [comment]
OP please re-open if this is still an issue
