### ISSUE TITLE
[Bug] Ping specifying port 3000 seems broken

### ISSUE THREAD

**Issue by attzonko** [benphelps/homepage#1960]
### Description

I am running docker, homepage ping works for all my other services except wikijs, which is running on port 3000

Looking at the log from the homepage container when the ping is set to `http://wikijs:3000` there is no log generated but the frontend shows HTTP error 500:
<img width="337" alt="image" src="https://github.com/benphelps/homepage/assets/4975715/3b5baec6-cb8a-46f3-8cb6-1bb599f990a8">

If I change the port to any other number I see a log correctly showing unable to access that port.

### Steps to reproduce

Try and ping a service running in docker on port 3000

### homepage version

v0.6.29

### Installation method

Docker

### Configuration

```yaml
- Wiki JS:
        icon: wikijs.png
        href: https://wikijs.example.com
        ping: http://wikijs:3000
        server: my-docker
        container: wikijs
```

### Container Logs

This is the log when I set the port to 3001:
`
[2023-09-11T05:55:00.394Z] error: <httpProxy> Error calling http://wikijs:3001/...
[2023-09-11T05:55:00.394Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 172.18.0.24:3001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.18.0.24',
    port: 3001
  }
]
`

### Troubleshooting

I created an Ubuntu docker container and ran `curl -s -I http://wikijs:3000` and got a 200 response

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
```yaml
...
      - homepage.name=wikijs
      - homepage.ping=http://wikijs:3000
```
<img width="378" alt="Screenshot 2023-09-10 at 11 30 30 PM" src="https://github.com/benphelps/homepage/assets/4887959/ba67ca40-de34-4277-84da-9b3f9d69bdd5">

Sorry, cant reproduce this and no reason why it would fail assuming hostname resolution is working etc. Its just making an http call to another host, it doesnt really care what port...

https://github.com/benphelps/homepage/blob/b39c79bea1dac2327d9580f81d1b81fda1962ac8/src/pages/api/ping.js#L38

Perhaps youre confusing yourself with ports or something.

**Comment by attzonko** [comment]
Thanks for the quick response. I understand what you are saying and that you can't seem to reproduce it. 

I confirmed that from inside the 'homepage' container the ping url works:

<img width="590" alt="image" src="https://github.com/benphelps/homepage/assets/4975715/31cd4315-a5d5-4602-8a44-20bfffef3b3e">

Is it possible there is some other issue in my environment? 

I tried to enable LOG_LEVEL=debug but there doesn't seem to be any debug info logged:
<img width="665" alt="image" src="https://github.com/benphelps/homepage/assets/4975715/86b3824f-c6d8-49a6-afa6-eb81a17b1568">

Any ideas on how to debug this further would be appreciated.
