### ISSUE TITLE
Docker statistics an ping result in service is not available with v0.6.30

### ISSUE THREAD

**Issue by RK62** [benphelps/homepage#1997]
### Description

on services:
- The ping statistic will not shown on "mouse over". 
See behavior in v0.6.29:
![image](https://github.com/benphelps/homepage/assets/39200469/5b6481c9-0a8e-4316-aefe-34ff60df33e7)
- The docker-statistics are no longer click- and foldable, 
An click on the docker-status will open the applikation instead of showing docker-stats for the container

Both points works fine in v.0.6.29

### Steps to reproduce

- Move Mouse about ping-value
- Click on docker-status in a service

### homepage version

v0.6.30

### Installation method

Docker

### Troubleshooting

Not a widget malfunktion

### Other

Tried out with Edge and Safari

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by sahara101** [comment]
Same here
