### ISSUE TITLE
[Bug] Transmission widget downloading number error

### ISSUE THREAD

**Issue by xp9477** [benphelps/homepage#2006]
### Description

The downloading number always shows 11, but the actual value is 0

### Steps to reproduce

Transmission widget

### homepage version

v0.6.33 

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Recreate the container
