### ISSUE TITLE
[Bug] Kubernetes discovery broke between 0.6.29 and 0.6.33

### ISSUE THREAD

**Issue by MikaelElkiaer** [benphelps/homepage#2012]
### Description

After upgrading from 0.6.29 to 0.6.33 I am unable to see Kubernetes-based widgets.

My exact set-up can be seen here: https://github.com/MikaelElkiaer/flux-twr/tree/main/default/homepage

I basically have a bunch of Ingresses, as well as a single IngressRoute (traefik.io).
Seeing the logs below, it seems something broke in the handling of IngressRoutes, causing the overall Kubernetes discovery to fail.

### Steps to reproduce

1. Use my config
2. Go to homepage in browser

### homepage version

0.6.33

### Installation method

Other (please describe above)

### Container Logs

```
[2023-09-17T16:43:45.611Z] error: Failed to discover services, please check kubernetes.yaml for errors or remove example entries.
[2023-09-17T16:43:45.612Z] error: TypeError: traefikIngressListIo is not iterable
[2023-09-17T16:47:40.139Z] error: <service-helpers> TypeError: traefikIngressListIo is not iterable
    at servicesFromKubernetes (/app/.next/server/chunks/7586.js:265:67)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async servicesResponse (/app/.next/server/chunks/5876.js:121:127)
    at async handler (/app/.next/server/pages/api/services.js:84:12)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:252:36)
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:365:29)
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:303:20)
```

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
k8s integration seems to be drama, and frustratingly I dont have it to test. It seems this was broken by https://github.com/benphelps/homepage/pull/1875 although your error is slightly different. But see #2003 

What does the api call to /traefik.containo.us/v1alpha1/ingressroutes return? Looking at the code at least, yours has to be returning nothing to explain the above error.

Can you try the current image of `main` and let us know if that solves it.

**Comment by MikaelElkiaer** [comment]
`main` did not resolve it - same error.

It seems that it is retrieving the ingressroutes in the `traefik.io`  group that causes this, based on the `traefikIngressListIo` variable name in the error message `TypeError: traefikIngressListIo is not iterable`.

**Comment by MikaelElkiaer** [comment]
My suspicion lies here: https://github.com/benphelps/homepage/blob/a72a27a8b5b8428a1786c2b1a9930945dde2151d/src/utils/config/service-helpers.js#L199

I wonder if the function here: https://github.com/benphelps/homepage/blob/a72a27a8b5b8428a1786c2b1a9930945dde2151d/src/utils/config/service-helpers.js#L184
actually returns an object, as that would cause this error - and also explain why the null coalesce did not work.

Tiny example:

```javascript
$ node
> [...{},...[]]
Uncaught TypeError: {} is not iterable
```

**Comment by MikaelElkiaer** [comment]
Ah, so they are objects.

Perhaps a patch like this would do the trick:

```diff
diff --git a/src/utils/config/service-helpers.js b/src/utils/config/service-helpers.js
index 921d3ef6..3b326d96 100644
--- a/src/utils/config/service-helpers.js
+++ b/src/utils/config/service-helpers.js
@@ -166,7 +166,7 @@ export async function servicesFromKubernetes() {

     const traefikIngressListContaino = await crd
       .listClusterCustomObject("traefik.containo.us", "v1alpha1", "ingressroutes")
-      .then((response) => response.body ?? [])
+      .then((response) => response.body)
       .catch(async (error) => {
         if (![403, 404].includes(error.statusCode)) {
           logger.error(
@@ -182,7 +182,7 @@ export async function servicesFromKubernetes() {

     const traefikIngressListIo = await crd
       .listClusterCustomObject("traefik.io", "v1alpha1", "ingressroutes")
-      .then((response) => response.body ?? [])
+      .then((response) => response.body)
       .catch(async (error) => {
         if (![403, 404].includes(error.statusCode)) {
           logger.error(
@@ -196,9 +196,9 @@ export async function servicesFromKubernetes() {
         return [];
       });

-    const traefikIngressList = [...traefikIngressListContaino, ...traefikIngressListIo];
+    const traefikIngressList = [...traefikIngressListContaino?.items ?? [], ...traefikIngressListIo?.items ?? []];

-    if (traefikIngressList?.items?.length > 0) {
+    if (traefikIngressList.length > 0) {
       const traefikServices = traefikIngressList.items.filter(
         (ingress) => ingress.metadata.annotations && ingress.metadata.annotations[`${ANNOTATION_BASE}/href`]
       );
```

**Comment by shamoon** [comment]
That would probably work. I do wonder if #2003 is the better solution overall

could you send me the json of what those objects from the api look like?

**Comment by janpfischer** [comment]
I think we have two scenarios here. My bug report yesterday #1998 occurred because I do not have traefik resources on my cluster. This was fixed by @shamoon with 3cd441a4. For me this fixed the error, but it seems that there is one follow-up error if traefik resources are in place. 

As I can see in the Repo from @MikaelElkiaer he uses traefik and has this CRDs in place. So the current check is not returning a 404 or 403 because he has a rbac role in [place](https://github.com/MikaelElkiaer/flux-twr/blob/main/default/homepage/homepage.ClusterRole.yaml) and there is likely an error after that check.

The `traefikIngressListContaino` should return a 403 though because you do not have rbac permissions for `traefik.containo.us`. I am sure you do not need them in your cluster, but could you add permissions on that just for a test and see if something changes?

My MR #2003 would introduce a check in the first place if a CRD exists, but I think this bug it would not prevent because the check would be successful here.

**Comment by shamoon** [comment]
Yes I think his patch above would solve his problem just frustrating I can't test myself.

If anyone wants to send me the relevant json output it would be nice to be able to 'mock these'

Anyway, it sounds like a combo of these two will be best

**Comment by janpfischer** [comment]
I can not because I do not have traefik set up on my side. 

Maybe we can have some build which debug logs the body of the response when not 404 or 403 and then @MikaelElkiaer could send it over easily.

**Comment by shamoon** [comment]
It would be awesome to somehow be able to test this quickly with e.g. http://labs.play-with-k8s.com/ Sadly I dont even know how to spin that up.

If you can test with `main` when its done building ( https://github.com/benphelps/homepage/actions/runs/6216533762 ), we've applied your patch above

**Comment by MikaelElkiaer** [comment]
If I get the time I could set up a GitHub workflow using [KIND](https://github.com/helm/kind-action).
Should be possible to set up a fairly simple scenario with Traefik and homepage and then try to load homepage while watching for server-side errors.

**Comment by janpfischer** [comment]
That would be great. Maybe we could add two widgets. One statically over the configuration yaml and one with an annotation. We should pick a service which has a simple widget integration to test that as well. 

If you test the new main keep in mind that you will need the new RBAC permission as stated in #2003. If not there should be errors leading you in the right direction anyways.

**Comment by shamoon** [comment]
I saw the k3d dir yesterday, got a little further today (at least it looked like it was all working).
Had to change serversMemory to `MiB` and it seems :6443 is used by docker so changed `hostPort` to 6444, scripts tell me everything is working but:
<img width="1001" alt="Screenshot 2023-09-18 at 2 35 58 PM" src="https://github.com/benphelps/homepage/assets/4887959/de4726ec-1455-406d-a1a3-cbab7d80ba70">
<img width="1453" alt="Screenshot 2023-09-18 at 2 37 40 PM" src="https://github.com/benphelps/homepage/assets/4887959/0281926e-476d-4943-966d-54faa62dff4b">

It seems docker doesnt translate much to k8s

**Comment by shamoon** [comment]
Im amazed people manage to figure out kubernetes, the learning curve feels insanely steep. Just running these k3d scripts I have run into:

https://stackoverflow.com/questions/75703476/k3d-kubernetes-registry-fails-with-no-such-host
https://github.com/k3d-io/k3d/issues/143 which I think I havent successfully fixed because I end up with https://github.com/kubernetes/kubernetes/issues/63128

**Comment by shamoon** [comment]
Well it wasn't easy but I finally got the k3d cluster running!
<img width="415" alt="Screenshot 2023-09-19 at 1 50 08 PM" src="https://github.com/benphelps/homepage/assets/4887959/d8821bcd-8e4a-4e73-9914-179d40cb6c18">

But where the heck can I find the homepage logs??

**Comment by janpfischer** [comment]
Have you access to the cluster via kubectl with k3d? If yes you can do "kubectl get pods" to find the pod name of homepage and then "kubectl get logs <pod-name>" for logs.

**Comment by shamoon** [comment]
Amazing, thanks! Ok finally I can play with things a bit...
