### ISSUE TITLE
[Bug] settings.yaml configurations no longer take effect

### ISSUE THREAD

**Issue by alejandrosnz** [benphelps/homepage#2013]
### Description

I have a settings.yaml file defined for a while with a custom web name, favicon... that used to work perfectly, but after the last update, everything got back to default

### Steps to reproduce

1 - Define any configuration in the file settings.yaml, for ex.: 
title: MyLAB
2 - Restart the application
3- The web title should have changed, but it does not anymore

### homepage version

v0.6.33

### Installation method

Docker

### Configuration

```yaml
title: MyLAB
favicon: images/favicon/android-icon-192x192.png

headerStyle: clean
hideVersion: true
```

### Container Logs

Listening on port 3000
17/09/2023 22:15:16
[2023-09-17T20:15:16.638Z] error: Error: EROFS: read-only file system, copyfile '/app/src/skeleton/custom.css' -> '/app/config/custom.css'
17/09/2023 22:15:16
    at copyFileSync (node:fs:2969:3)
17/09/2023 22:15:16
    at checkAndCopyConfig (/app/.next/server/chunks/4574.js:53:55)
17/09/2023 22:15:16
    at /app/.next/server/pages/api/hash.js:74:78
17/09/2023 22:15:16
    at Array.map (<anonymous>)
17/09/2023 22:15:16
    at handler (/app/.next/server/pages/api/hash.js:73:26)
17/09/2023 22:15:16
    at Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:366:15)
17/09/2023 22:15:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
17/09/2023 22:15:16
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:481:9)
17/09/2023 22:15:16
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:741:37)
17/09/2023 22:15:16
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:252:36)
17/09/2023 22:15:16
[2023-09-17T20:15:16.690Z] error: undefined

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
> '/app/src/skeleton/custom.css' -> '/app/config/custom.css'

create that file manually, and presumably custom.js too and recreate the container

**Comment by MFYDev** [comment]
I just met the same problem, I just added title: name to it and it is not taking effect, I tried to delete the container or restart it and nothing works

**Comment by shamoon** [comment]
If your error is the same as above, follow the instructions above and create the missing files

**Comment by MFYDev** [comment]
Hi @shamoon thank you for the quick reply. The problem on my side is that the container does not even have any error log, all the log is just Listening on port 3000.

I changed services.yaml just to test, and it took effect immediately, only settings is not taking any effect

**Comment by shamoon** [comment]
Make sure you delete any docker volumes and  the containers and recreate (not restart)

**Comment by MFYDev** [comment]
I did not use any volumes, as I directly use local folders as the config folder. And I can confirm only the container got created when I run docker compose up -d. I double confirmed this just several secs ago

**Comment by wisdomdevil** [comment]
> Make sure you delete any docker volumes and the containers and recreate (not restart)
> 
> Edit: this was solved by creating custom.css and custom.js manually

This is not correct behavior, i have installed it in my kubernetes cluster and i dont have any persistent volumes, only configmaps, if i will create it manually and delete pod, i will need  do it every time by my hands

**Comment by wisdomdevil** [comment]
And i think this is main problem of discovery ingresses in kubernetes,  pod just cant update any files in his directory.
