### ISSUE TITLE
[Feature Request] TPLink Omada Widget

### ISSUE THREAD

**Issue by madkatz01** [benphelps/homepage#202]
TPLink Omada is a becoming popular home networking hardware (similar to Ubiquiti's UniFi system) and they have a pretty extensive API for retrieving information on the network status. Would be awesome to have this added as a widget. 

Here is a link to their published API for their current v5.0+ controllers: https://static-community.tp-link.com/attach/8/2/2022/78d3f067ac0c491d931426e040188632.zip

**Comment by darrylgibbs** [comment]
I second this!

**Comment by Oupsman** [comment]
I'm working on it (I've ported an prometheus exporter to Influxdb). All I have to do is call the controller endpoint (after authentication) with the following parameters : 

{
        "method": "getGlobalStat",
}

but as I'm no JS developer, I don't understand how to do it.

**Comment by Oupsman** [comment]
After 2 hours of struggle (I'm no JS developper) I have a working widget that display the number of active AP and the number of clients connected to the wifi.

because I only use Omada soft controler (version 3.2.17) with 4 AP

**Comment by aidzer0** [comment]
Thats amazing work! I look forward to the commit.

_Get this man a beer and a JS developer!_

**Comment by Oupsman** [comment]
For now, I am really not ready for the pull request, my code is really ugly (even to my low standards) and I can't get the labels to display properly. 
![DeepinScreenshot_select-area_20221205213623](https://user-images.githubusercontent.com/11260343/205741275-aeef7740-24cd-46cd-a28e-e697d8e710cd.png)

**Comment by aidzer0** [comment]
> For now, I am really not ready for the pull request, my code is really ugly (even to my low standards) and I can't get the labels to display properly.
> ![DeepinScreenshot_select-area_20221205213623](https://user-images.githubusercontent.com/11260343/205741275-aeef7740-24cd-46cd-a28e-e697d8e710cd.png)

Oh for sure no rush, it’s awesome someone is looking into this, it’s a huge leap forward from nothing haha, I for one have no clue how to do any of that.. so you are miles ahead of me.

**Comment by shamoon** [comment]
If you post it somewhere accessible someone (yes maybe me) might have some time to look. only if you want to, of course.

Also, since I dont have one of these would need some help getting fake API output from the device

**Comment by Oupsman** [comment]
Let me first try to find out how I could possibly have fucked the translation system up on my local copy and I get back to you. 

The code is here : [https://github.com/Oupsman/homepage](url)

**Comment by shamoon** [comment]
It doesnt look so bad =)

For translation files you only edit `en`, the rest come through a translation service we use.

And for displaying those strings it should look like `<Block label="omada.connectedAp" value={t("common.number", { value: omadaData.connectedAp })} />` like you had it before

**Comment by Oupsman** [comment]
Thanks. 

I added the translations in both en and fr (because I'm French). I've removed the translations from the french file but I still have problems : 
![DeepinScreenshot_select-area_20221205223725](https://user-images.githubusercontent.com/11260343/205747799-51678db3-d382-457f-9e77-0d59dd565a1b.png)

I'll try to fix it tomorrow.

**Comment by Oupsman** [comment]
I have fixed the code this morning, and it seems to work fine on my old controller. But I've tested it against a modern one and it doesn't work. So for now, no PR because I don't think anyone else uses an old controller.

**Comment by aidzer0** [comment]
I reckon you do, I don’t know though, if you’re confident with the code, I don’t see why not.

**Comment by Oupsman** [comment]
The Omada API is hell on earth ! Between versions, the fields needed for stats are changing. 
So I closed my pull request until I have a code working on the three versions I can test on. 

Sorry

**Comment by aidzer0** [comment]
No worries mate, don’t be sorry :) getting it working on 3 different versions sounds light a nightmare!

**Comment by Oupsman** [comment]
@shamoon could you please give me your feedback on the code I pushed on my repo ? 

PS : I setup a few controllers for me to test on : I've deployed 2 controllers, one in 4.4.8 and one in 5.7.4 so I can have real tests.

**Comment by shamoon** [comment]
Wow, I see what a pain it is to support the two APIs. Not sure when I'll have time to test, youre saying they can be easily deployed as docker containers (I dont have the hardware ofc)?

Also, what does a widget with 8 blocks look like?

**Comment by Oupsman** [comment]
A widget with 8 blocks is quite difficult to read, but I think that all data can be important. Maybe create two widgets and filter the fields ? I've tested it because on a V3 controller, all fields are not available.

**Comment by Oupsman** [comment]
Here is a screenshot of my homepage : 
![DeepinScreenshot_select-area_20221210173120](https://user-images.githubusercontent.com/11260343/206865123-7bec730b-1c09-4c80-961f-0a137a48822b.png)

**Comment by Oupsman** [comment]
To deploy an omada controller as a docker container : https://github.com/mbentley/docker-omada-controller

**Comment by shamoon** [comment]
yea messy. So youre trying to support v3, v4 and v5?


Yea 8 blocks is too much =)

**Comment by Oupsman** [comment]
I want to support v3 to v5, yes. Because I'm still using v3 :) 

Do you think I should split the blocks in two lines ?

**Comment by Oupsman** [comment]
I may have another idea, and I'd like feedback : I can also divide the widget in two parts : one for WLAN and the other one pour LAN/WAN. Because I think most people are interested in WLAN metrics. 

What do you all think about that ?

**Comment by darrylgibbs** [comment]
Splitting into WLAN/LAN/WAN would be amazing!

**Comment by Oupsman** [comment]
Ok, I've split the widget in two, the tests are good so far. 
![DeepinScreenshot_select-area_20221213092629](https://user-images.githubusercontent.com/11260343/207264419-c6e048b0-8261-499a-97dc-25713688d641.png)

@shamoon : I did not duplicate the code, did not touch anything in the omada widget (except removing the unwanted fields). The omadalan widget imports the proxy from the omada widget. But I'm not sure that's the best way to do so, so feel free to give me ANY feedback you see fit.

**Comment by shamoon** [comment]
TBH I would just choose the 4/5 stats you think are most important. If not, make it a configuration option on the widget instead of two separate widgets.

**Comment by Oupsman** [comment]
> TBH I would just choose the 4/5 stats you think are most important. If not, make it a configuration option on the widget instead of two separate widgets.

Why make a configuration option when the user can select the wanted fields ? I mean, the code will be the same, because all the data are collected with a single API call.

**Comment by shamoon** [comment]
Because the widget should work "out-of-the-box" and not be unusable if the user doesnt specify anything

**Comment by Oupsman** [comment]
OK then, a setting "mode" with two choices : WLAN and LAN and a default value of WLAN. That seems to be the less bad option to me.

**Comment by Oupsman** [comment]
Thanks, I took inspiration from the unifi widget and my code will display the number of connected switches and the number of connected gateways only if there is something to display (aka, the number is greater than 0)

When I first opened the PR, you mentioned minor issues with the code, could you please give them to me so I can correct my code ?

**Comment by shamoon** [comment]
> When I first opened the PR, you mentioned minor issues with the code, could you please give them to me so I can correct my code ?

Your code has increased in complexity quite a bit since then with the supporting of multiple versions etc. and it won’t be trivial to test (don’t have hardware, have to spin up multiple containers etc). The last time I looked it seemed it now needs a bit more but I don’t have specifics. Please get the PR to where you are happy with it and when we have time one of us will review, not sure exactly when.
