### ISSUE TITLE
[Bug] Custom JS didn't run

### ISSUE THREAD

**Issue by libook** [benphelps/homepage#2022]
### Description

Custom JS didn't run.

My custom.js:
```javascript
console.log('here!');

```

The loaded HTML:
![2023-09-19_11-56](https://github.com/benphelps/homepage/assets/3395610/e6fb61dc-7c59-419f-bbb9-45cf5574e6d1)

The console:
![2023-09-19_11-57](https://github.com/benphelps/homepage/assets/3395610/8b92f149-3f0e-46fa-b9c6-1177cb6cdbaf)

It seems that the JS code is successfully loaded, but didn't run.

### Steps to reproduce

1. Write `console.log('here!');` into custom.js .
2. Refresh the homepage.
3. Check the console, there is no expected output.

### homepage version

v0.6.33

### Installation method

Docker

### Troubleshooting

n/a

### Other

Tested browser:
Firefox 117.0.1 64bit Linux
Chrome 117.0.5938.62 64bit Linux

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Great point. @TheRolfFR , any thoughts?

**Comment by shamoon** [comment]
I think #2023 will fix this

**Comment by shamoon** [comment]
You can test this out in the current `main` image
