### ISSUE TITLE
[Bug] Bookmark groups do not display if their name matches a service group

### ISSUE THREAD

**Issue by mzrimsek** [benphelps/homepage#2038]
### Description

If you have a bookmarks group with the same name as a services group, the bookmarks will not appear. They will still appear as expected when you search. Simply modifying name of the bookmark group with the duplicate name will have it render again as you would expect.

I haven't updated my config in a while and just noticed this recently. My container updates automatically so not sure exactly when it started.

### Steps to reproduce

1. Add a bookmarks group with the same name as one of the services groups
2. See it not render after a refresh 
3. Add a "2" to the end of the bookmarks group (or anything for that matter a along as it doesn't match)
4. See it render after a refresh 

### homepage version

v0.6.35 (d4a3929)

### Installation method

Docker

### Troubleshooting

N/A

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I can appreciate how this is a bit annoying but for now the answer is going to have to be “change the name of one of the groups”. It probably should be noted in the docs

it is a consequence of the fact that now you can mix and match bookmarks and services and apply layout settings to both. So overall I think it’s a worthwhile trade off

But I can imagine a solution that lets you set an id on a group which would allow this. That of course would require config changes (well, additions) so it won’t be automagical

**Comment by mzrimsek** [comment]
Yep that's exactly what I did to fix it before submitting and for the record I think an update to the docs to call out that the names all have to be unique is a perfectly acceptable solution.

Appreciate all the work y'all do on this!
