### ISSUE TITLE
[Wiki] Nginx Proxy Manager widget is missing

### ISSUE THREAD

**Issue by GertJanH** [benphelps/homepage#204]
i Found this code in src/skeleton/services.yaml, and its a working widget, but i can not find this widget on de wiki page,

`        widget:
          type: npm # npm for NGINX Proxy Manager
          url: http://localhost:81 # no slash at the end
          username: aidenpwnz@proton.me # your email
          password: AidenProxy1994! # your password`

**Comment by C8opmBM** [comment]
can't help you with this, but you should change your password now :)

**Comment by GertJanH** [comment]
> can't help you with this, but you should change your password now :)

it's not my password and username, this is the example that was given in the code on github.

**Comment by benphelps** [comment]
Updated: https://github.com/benphelps/homepage/wiki/Service-Widgets#nginx-proxy-manager
