### ISSUE TITLE
[Bug] Quick Launch is triggered by Arrow Keys & Pg Keys

### ISSUE THREAD

**Issue by chxseh** [benphelps/homepage#2054]
### Description

Using the Arrow Keys and/or Page Up/Down Keys to attempt to scroll inside Homepage causes the Quick Launch to open.

Could be a regression from #2044.

### Steps to reproduce

1. Open Homepage
2. Press Arrow Down
3. Observe Quick Launch Being Triggered

### homepage version

v0.6.35

### Installation method

Docker

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
That PR hasn't been released yet, its available in `main`
