### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'drive')

### ISSUE THREAD

**Issue by rayansailani** [benphelps/homepage#2056]
### Description

When starting the application in local with `pnpm dev` it was seen that while rendering the homepage, I encountered an error 
TypeError: Cannot read properties of undefined (reading 'drive'). |
![image](https://github.com/benphelps/homepage/assets/54993789/a91b8a19-a37b-44a9-89b1-17dae1bab109)

### Steps to reproduce

git clone 
pnpm install
pnpm dev

### homepage version

v0.6.35

### Installation method

Source

### Configuration

```yaml
n/a
```

### Container Logs

TypeError: Cannot read properties of undefined (reading 'drive')

### Browser Logs

TypeError: Cannot read properties of undefined (reading 'drive')

### Troubleshooting

TypeError: Cannot read properties of undefined (reading 'drive')

### Other

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by rayansailani** [comment]
I would like to take this up as it seems like a simple empty object check that could be fixed by using lodash.

**Comment by rayansailani** [comment]
https://github.com/benphelps/homepage/pull/2057 - have PR for this issue.

**Comment by shamoon** [comment]
This code hasn't changed in ages and it's not something reported a lot, rather than adding random checks, I'd like to figure out why it's happening first. If you've incorrectly specified a drive or the si dependency is returning empty data or what.

And re your second PR, what is the even-more specific situation where it would return data.drive but drive is actually empty??
