### ISSUE TITLE
[Feature Request] Homebridge Widget

### ISSUE THREAD

**Issue by benphelps** [benphelps/homepage#208]
### Discussed in https://github.com/benphelps/homepage/discussions/197

<div type='discussions-op-text'>

<sup>Originally posted by **hunkyn** September 17, 2022</sup>
Is it possible to add a widget for Homebridge? Current I check every few days if there is an update to the plugins and update them. Thinking this widget to show count of plugin updates available, status of child bridges if they are running or not.</div>

**Comment by FWeinb** [comment]
I replaced my home dashboard with homepage today and build this widget for myself. It currently displays the status of the main bridge instance, available plugin updates, and the status of each child bridge (can be configured).

<img width="457" alt="Newly created widget for homebridge displaying the status and number of available plugin updates" src="https://user-images.githubusercontent.com/1250430/191086394-f1a2caa8-db8c-481b-9d04-af662663381b.png">

I am using the [Homebridge UI API](https://github.com/oznu/homebridge-config-ui-x/wiki/API-Reference) and wrote a custom widget and proxy for that. 

Are you interested in a PR for this feature?

**Comment by hunkyn** [comment]
> I replaced my home dashboard with homepage today and build this widget for myself. It currently displays the status of the main bridge instance, available plugin updates, and the status of each child bridge (can be configured).
> 
> <img alt="Newly created widget for homebridge displaying the status and number of available plugin updates" width="457" src="https://user-images.githubusercontent.com/1250430/191086394-f1a2caa8-db8c-481b-9d04-af662663381b.png">
> 
> I am using the [Homebridge UI API](https://github.com/oznu/homebridge-config-ui-x/wiki/API-Reference) and wrote a custom widget and proxy for that.
> 
> Are you interested in a PR for this feature?

This looks good to me and serves my purpose.  @benphelps has to make the final decision.

**Comment by Magelo** [comment]
I'm interested in this widget. Avaiable soon?
