### ISSUE TITLE
[Bug] Concise description of the issue

### ISSUE THREAD

**Issue by mirhunter** [benphelps/homepage#2083]
### Description

https://gethomepage.dev is not working at all.
![broken](https://github.com/benphelps/homepage/assets/46880793/e59e1cad-355d-483f-869c-81a3653a70bf)

### Steps to reproduce

1. Navigate to [gethomepage.dev](https://gethomepage.dev/en/installation/docker/)
2. Get `404 error`

### homepage version

current

### Installation method

Docker

### Troubleshooting

I do not have / want access to trouble shoot this...

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
We’re migrating the docs
