### ISSUE TITLE
[Feature Request] TrueNas Service Widget 

### ISSUE THREAD

**Issue by benphelps** [benphelps/homepage#209]
### Discussed in https://github.com/benphelps/homepage/discussions/188

<div type='discussions-op-text'>

<sup>Originally posted by **bat1939** September 16, 2022</sup>
Just wanted to request TrueNAS for the service widgets. </div>

**Comment by bat1939** [comment]
I am not sure if it would help, but Heimdall has the TrueNAS API working.

**Comment by mokshmridul** [comment]
+1

**Comment by NightShaman** [comment]
+1

**Comment by shamoon** [comment]
Closed by #451
