### ISSUE TITLE
[Feature Request] Disk space from other servers

### ISSUE THREAD

**Issue by benphelps** [benphelps/homepage#210]
### Discussed in https://github.com/benphelps/homepage/discussions/22

<div type='discussions-op-text'>

<sup>Originally posted by **chrisg991** August 27, 2022</sup>
Feature Request:
Please would you add the ability to report free disk space from other servers on the network. Homepage currently displays the disk space, cpu and memory usage of my Docker VM but it would be useful to see those same measures (particularly disk space) for the physical servers on my network.

Thank you </div>

**Comment by ShlomiPorush** [comment]
you need to mount those disk to the docker vm (in you situation)
i mounted my NASs via smb.

![image](https://user-images.githubusercontent.com/5992161/190923022-49014486-6138-45d8-83e0-1887d9e8197d.png)

**Comment by Smiggel** [comment]
How can I mount drives using the stack? Tried it, but getting errors all the time that it's not allowed.

**Comment by benphelps** [comment]
Pretty much every feature and configuration option needed is documented in the wiki, you can find info about the disk resource widget here: https://github.com/benphelps/homepage/wiki/Information-Widgets#resources

**Comment by Smiggel** [comment]
Doesn’t say how to mount the drive/folder using the stack in docker.

**Comment by ShlomiPorush** [comment]
You need to mount the remote drive on the host server and then add it to homepage container

Add your folder mount to docker-compose.yml
```
    volumes:
      - /mnt/media1:/mnt/media1:ro
      - /mnt/media2:/mnt/media2:ro
```
And in widgets.yaml

```
- resources:
    label: Media1
    disk: /mnt/media1

- resources:
    label: Media2
    disk: /mnt/media2

```

**Comment by Smiggel** [comment]
Hmm ok. I will give it a try. Didn’t work for me before. Thanks.

**Comment by Smiggel** [comment]
> You need to mount the remote drive on the host server and then add it to homepage container
> 
> Add your folder mount to docker-compose.yml For example
> 
> ```
>     volumes:
>       - /mnt/media1:/mnt/media1:ro
>       - /mnt/media2:/mnt/media2:ro
> ```
> 
> And in widgets.yaml
> 
> ```
> - resources:
>     label: Media1
>     disk: /mnt/media1
> 
> - resources:
>     label: Media2
>     disk: /mnt/media2
> ```

Thanks. Got it to work now. :-)

**Comment by JazzFisch** [comment]
Thanks for all of the great suggestions everyone.  I'm closing.

**Comment by MortRainey** [comment]
And how do i get CPU and Memory from host. I have running hompage inside a lxc container on proxmox.

**Comment by tautomer** [comment]
> And how do i get CPU and Memory from host. I have running hompage inside a lxc container on proxmox.

I more or less got this worked in a really ugly way.
First, you need mount `/proc` to your lxc, like what is suggested in the post below
https://www.linuxquestions.org/questions/linux-server-73/using-web-monitor-within-lxc-to-monitor-core-server-4175646014/
Unfortunately, unlike netdata, I don't think you can customize the data source in homepage. They are hardcoded, like 

```javascript
 cpuinfo = fs.readFileSync('/proc/cpuinfo', { encoding: 'utf8' }).toString().split('\n');
```
So I directly mounted the host's `/proc` to the lxc's `/proc`.
Then another issue kicked in https://github.com/lxc/lxd/issues/2238. Directly mounting `/proc` to the lxc will make it unbootable.
At the end, my whole workaround is

```shell
# mount /proc to /mnt/proc
mount -t proc proc /mnt/proc
```
then modify the lxc settings to mount /mnt/proc

```conf
lxc.mount.entry: /mnt/proc proc none bind,create=dir
```
![image](https://github.com/benphelps/homepage/assets/15900605/f288c3a0-8cc6-4514-85fb-f2ba2f138a9c)
![image](https://github.com/benphelps/homepage/assets/15900605/65d39332-81f6-4d41-8422-62d9b96aeaf3)

CPU, RAM, and up time are all from the host.

**Comment by swarshah** [comment]
> And how do i get CPU and Memory from host. I have running hompage inside a lxc container on proxmox.

Better approach here would be to use `glances` https://gethomepage.dev/v0.7.0/widgets/info/glances/

**Comment by cocomango1** [comment]
@ShlomiPorush 
I still have a questioin on this:

I am on Synology with Docker-compose.
I have 2 Volumes on Synology
Docker is located on Volume 1
But I can not get the size of Volume2

I am adding folder to docker-compose.yml:

```
volumes:
   - /volume1:/mnt/media1:ro
   - /volume2:/mnt/media2:ro
```
and my widgets.yaml point inside container to
```
- resources:
    label: Media1
    disk: /mnt/media1

- resources:
    label: Media2
    disk: /mnt/media2
```
I also tried only mount volume2 without success
(incl. mount my volume1, I get no size at all)
Any suggestion?
