### ISSUE TITLE
[Bug] Plex Widget double lines

### ISSUE THREAD

**Issue by drag0n141** [benphelps/homepage#220]
Hi,

when i am have only one plex stream then it shows it as two lines.

![chrome_19 09 2022-135](https://user-images.githubusercontent.com/44865095/190988594-f36a6326-ef19-40be-ad5b-2af6e727f518.png)

**Comment by ShlomiPorush** [comment]
same here.. and i cant see the icon in my page is different

![image](https://user-images.githubusercontent.com/5992161/191069195-42dcc726-0b7f-4320-a9ed-c3fdb05c872c.png)

**Comment by benphelps** [comment]
That's by design, it splits into two lines, one showing the content name and status icons, one showing the play state.

This keeps it the same height as all other widgets, while showing more information that the compact view does.
