### ISSUE TITLE
[Bug] qBittorrent leech counts paused

### ISSUE THREAD

**Issue by ShlomiPorush** [benphelps/homepage#221]
**Describe the bug**
the widget also counts the any torrents that are not active (paused)

**Screenshots**
![image](https://user-images.githubusercontent.com/5992161/191003988-6af19aea-ecaf-4b3c-9a1f-044aa733ce7d.png)

**Comment by ShlomiPorush** [comment]
also qBittorrent is not in wiki 
https://github.com/benphelps/homepage/wiki/Service-Widgets

**Comment by ShlomiPorush** [comment]
Another bug, for some reason I get an error API ERROR
After restarting the container it works for a while and it returns to API error after some time.

![image](https://user-images.githubusercontent.com/5992161/191069713-6cb01f0b-571d-4ac9-9882-859d2f2f9ab1.png)

**Comment by JazzFisch** [comment]
When you get that API error, could you post the container logs to this issue?  I think it might be related to the auth token expiring and not getting refreshed.

With regards to the leech count, I wonder what the correct approach is here?  It is showing the count of incomplete torrents regardless if they are paused or waiting on peers.  Are you expecting that only active incomplete torrents are displayed in leech?

**Comment by ShlomiPorush** [comment]
whare are the logs /vat/log is empty.

The widget should reflect the situation as it is, and save having the time needs to login and check the status. so in my opinion paused / errored should be excluded. torrents with no peers are still active..

**Comment by JazzFisch** [comment]
> also qBittorrent is not in wiki https://github.com/benphelps/homepage/wiki/Service-Widgets

Just added an entry.  Thanks for letting us know.

**Comment by JazzFisch** [comment]
> whare are the logs /vat/log is empty.
> 
> The widget should reflect the situation as it is, and save having the time needs to login and check the status. so in my opinion paused / errored should be excluded. torrents with no peers are still active..

I'll have to think on this.  There are a lot of stats that a torrent can have.  See: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-list.  I agree though that having a better representative number would be helpful for "at a glance" information.

Regarding logs, if you are using docker, run `docker logs homepage` or however you set your container name.  That should give you the log output.

**Comment by ShlomiPorush** [comment]
This is all the log in `docker logs homepage`

> last Sunday at 21:26:12Listening on port 3000
last Sunday at 21:26:12(node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
last Sunday at 21:26:12(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by JazzFisch** [comment]
Are you comfortable with the browser dev tools?  Can you identify the qBittorrent details request from your browser to the homepage service?  I'm really curious that there's no log produced when you see an API error.

**Comment by ShlomiPorush** [comment]
Im familiar with Dev Tools but not an expert..
So, the only response i can see is Forbidden. Unless you tell me where to look

![image](https://user-images.githubusercontent.com/5992161/191180256-0ee3af27-70c6-4e9f-a864-ce8a31f0c71b.png)

![image](https://user-images.githubusercontent.com/5992161/191180377-6708c147-f0f5-4021-ad95-9345e5b11e30.png)

**Comment by ShlomiPorush** [comment]
i found a temporary solution.
i added dockers ip to `Bypass authentication for clients in whitelisted IP subnets`

![image](https://user-images.githubusercontent.com/5992161/191219820-b7291966-5c0d-478d-823c-0d43acd408ee.png)

**Comment by benphelps** [comment]
@JazzFisch could this have something to do with the login step getting bunged up?

**Comment by JazzFisch** [comment]
> @JazzFisch could this have something to do with the login step getting bunged up?

That, or the cookie expires and we don't correctly re-authenticate.  I'm going to need to add some additional logic and logging I think.  People should be required to turn off auth for specific subnets.

@ShlomiPorush can you check your qBittorrent docker logs when the API Error happens as well?  You should see clear messages about incorrect login and potentially auto-denying all requests from your IP after enough failures.

**Comment by ShlomiPorush** [comment]
> @ShlomiPorush can you check your qBittorrent docker logs when the API Error happens as well? You should see clear messages about incorrect login and potentially auto-denying all requests from your IP after enough failures.

The only thing a log relevant to login is below. there are no errors.
```
(N) 2022-09-19T14:04:29 - WebAPI login success. IP: ::ffff:10.10.10.10
(N) 2022-09-19T20:03:04 - WebAPI login success. IP: ::ffff:10.10.10.10
(N) 2022-09-19T20:03:09 - WebAPI login success. IP: ::ffff:10.10.10.10
(N) 2022-09-19T20:03:23 - WebAPI login success. IP: ::ffff:10.10.10.10
(N) 2022-09-19T20:05:00 - WebAPI login success. IP: ::ffff:10.10.10.10
(N) 2022-09-19T20:05:08 - WebAPI login success. IP: ::ffff:10.10.10.10
(N) 2022-09-20T00:46:21 - WebAPI login success. IP: ::ffff:10.10.10.10
(N) 2022-09-20T09:39:33 - WebAPI login success. IP: ::ffff:10.10.10.10
(N) 2022-09-20T10:56:25 - WebAPI login success. IP: ::ffff:10.10.10.10
```

**Comment by shamoon** [comment]
I think this issue is resolved, if not OP or others please let us know
