### ISSUE TITLE
NZBGET showing in Mbps not MB/s 

### ISSUE THREAD

**Issue by angelgtc87** [benphelps/homepage#226]
Nzbget is showing Mbps not MB/s , SabNZBd is showing correctly

**Comment by benphelps** [comment]
Not a bug, expected behaviour.  SABnzbd is the one that's wrong here, as all transfer speeds should be shown in Mbps.

The generally accepted convention is, data at rest is bytes, data in transit is bits.  Therefor, transfer speed is shown as bits per second, not bytes.

**Comment by angelgtc87** [comment]
Understood, so technically if I'm downloading at 200MB/S in NZBget I should see 1600Mbps , but I see 200Mbps in the widget

**Comment by angelgtc87** [comment]
![Screen Shot 2022-09-19 at 12 52 03 PM](https://user-images.githubusercontent.com/28854275/191071631-e12163c9-fc05-4f6d-bdd3-96b242da1f37.png)

**Comment by benphelps** [comment]
Yep, I'll get these all fixed to show the same metrics.

**Comment by benphelps** [comment]
This has all been normalized now as of the v0.4 release.

**Comment by angelgtc87** [comment]
Updated, however still seeing Mbps as MB/s
<img width="464" alt="Screenshot 2022-10-09 at 8 11 00 AM" src="https://user-images.githubusercontent.com/28854275/194756307-419f1103-d205-4bc4-87f8-f877d9ecab2f.png">
<img width="200" alt="Screenshot 2022-10-09 at 8 10 55 AM" src="https://user-images.githubusercontent.com/28854275/194756308-94f0b846-be70-41cd-9a3b-a1edb4c4c6b4.png">
