### ISSUE TITLE
[Help Wanted] - RESOLVED

### ISSUE THREAD

**Issue by MauricioNaderKalil** [benphelps/homepage#227]
**Describe the bug**
Hello all.

I am trying to install normally via docker-compose.yml

But its not pulling the files to config file.

I am doing everything right as usual. but Idk why its not pulling the files to the container  config directory.

**Screenshots**
![Captura de tela de 2022-09-19 15-52-35](https://user-images.githubusercontent.com/4604002/191093768-1b30cdcd-c4c9-405a-85ea-ec2905010be6.png)
![Captura de tela de 2022-09-19 15-55-25](https://user-images.githubusercontent.com/4604002/191094078-4b2394da-d25c-4537-b19f-21fde9889ee1.png)
![Captura de tela de 2022-09-19 15-57-18](https://user-images.githubusercontent.com/4604002/191094380-59d062bb-e801-4c6b-ae14-970307bd6df3.png)
![Captura de tela de 2022-09-19 15-58-34](https://user-images.githubusercontent.com/4604002/191094663-0357b73b-c4eb-4c2d-a99e-5f4b60493f68.png)

Thanks in advance.

**Comment by JazzFisch** [comment]
After the container starts, the mapped folder `/opt/homepage/config` is empty?  What does your container logs show?

**Comment by doc-jay** [comment]
Just go to the website and the config files will appear in your mapped folder.

**Comment by benphelps** [comment]
You need to click the refresh button in the bottom right of the page. Changes to settings.yaml are applied to the statically generated file, so you need to regenerate the static files.

This is mentioned in the first line of the settings doc, https://github.com/benphelps/homepage/wiki/Settings

**Comment by MauricioNaderKalil** [comment]
Thank you all for the responses.

My main issue is that: When I do a compose  up -d, the folders are not been filled with any files.

And my log ends here: 
`Listening on port 3000
(node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)` 

I am trying right now again. and bring back the feedback to you.

**Comment by benphelps** [comment]
You need to visit the page at least once for the files to be generated.

**Comment by MauricioNaderKalil** [comment]
Guys, I figured why it wasnt working.

I do not know why but, using the default container_name: homepage wasnt working.

I changed it to container_name: home

And now its working.
