### ISSUE TITLE
[Feature Request] Plex, tubearchivist, nginx reverse proxy, nvidia-smi/intel_gpu_top

### ISSUE THREAD

**Issue by thisisawesome1994** [benphelps/homepage#258]
**Is your feature request related to a service? Please describe.**
A clear and concise description of what you would like to see from this service.
I would like to see support for plex in widgets, tubearchivist and intel/nvidia gpu utilisation (intel_gpu_top/nvidia_smi)
I would also like support for nginx reverse http proxy, and a config file to achieve this.
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I would like it if [...]
No, it is a feature request.
**Additional context**
No, I think I was clear in the text above.

**Comment by thisisawesome1994** [comment]
Maybe add realtime network usage (speed & vnstat)

**Comment by benphelps** [comment]
Plex is already supported, see: https://github.com/benphelps/homepage/wiki/Service-Widgets#tautulli-plex

NGINX is supported via Nginx Proxy Manager, see: https://github.com/benphelps/homepage/wiki/Service-Widgets#nginx-proxy-manager

GPU stats has already been discussed here: https://github.com/benphelps/homepage/issues/68

**Comment by thisisawesome1994** [comment]
So that leaves open tubearchivist

**Comment by thisisawesome1994** [comment]
I just did. This can be closed
