### ISSUE TITLE
[Feature Request] Service-Widget - DelugeVPN/Deluge

### ISSUE THREAD

**Issue by irlam** [benphelps/homepage#269]
Could you please implement a service widget for.....
DelugeVPN it is a torrent client similar to
ruTorrent
qBittorrent

https://deluge-torrent.org/
https://github.com/ebrianne/docker-deluge-openvpn

**Comment by JazzFisch** [comment]
We have issue #190 tracking this widget request already.  Please redirect any further feedback there.
