### ISSUE TITLE
[Bug] speedtest-tracker widget wrong values

### ISSUE THREAD

**Issue by Nonoss117** [benphelps/homepage#272]
**Describe the bug**
Values displayed in widget are not the same if I switch language between `en` and `fr`

**Screenshots**
`en`

![image](https://user-images.githubusercontent.com/79055577/192167374-89f222cd-f4a9-4ae9-91f4-2df293bb5bad.png)

`fr`

![image](https://user-images.githubusercontent.com/79055577/192167402-15f16b36-e47f-4634-896f-bbbdc3bc4fee.png)

speedtest-tracker:
![image](https://user-images.githubusercontent.com/79055577/192167444-1034f977-e2e9-400b-b1ab-64c446750252.png)

Homepage version : v0.3.71 (latest). Same thing with main version.

The correct values are with `en`. Values with `fr` language are wrong
Is such a thing possible ?

**Comment by benphelps** [comment]
That's very odd... I'll take a look.

**Comment by benphelps** [comment]
This will be fixed in the next release

**Comment by Nonoss117** [comment]
Works fine with `main` tag
Thanks
