### ISSUE TITLE
Homepage not loading because of a client-side exception error

### ISSUE THREAD

**Issue by 2ndwonder** [benphelps/homepage#276]
**Describe the bug**
Homepage is not loading

**Expected behavior**
I'm getting the error ''Application error: a client-side exception has occurred (see the browser console for more information).''

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/24813161/192201286-51dfd4e2-42d1-4584-b1a3-a715a33ce3b9.png">

I'm using Main tag, did something change?

**Comment by JazzFisch** [comment]
Which version of the container did you install?

**Comment by 2ndwonder** [comment]
> Which version of the container did you install?

I'm on Main tag. Latest main tag version.

**Comment by kerwindouglas** [comment]
I'm having the same issue. on the latest main tag version.

**Comment by vykng** [comment]
Same issue.

**Comment by tupcakes** [comment]
Same.

**Comment by 2ndwonder** [comment]
After the latest main tag version which is updated, I can confirm that I don't have this error anymore

**Comment by JazzFisch** [comment]
This is fixed in the nightly build here https://github.com/benphelps/homepage/commit/b280e1865189eb20857748cbff4433b7374f8331.  It'll take a bit to reach main.

**Comment by kerwindouglas** [comment]
working now with latest main. Thanks.
