### ISSUE TITLE
Portainer How to get apikey

### ISSUE THREAD

**Issue by CnSuperYoung** [benphelps/homepage#279]
Portainer How to get apikey
![image](https://user-images.githubusercontent.com/6590372/192250209-e545227a-3020-4490-af53-0a965d3f18c1.png)

**Comment by NICHX** [comment]
portainer-ee

**Comment by Nonoss117** [comment]
This tutorial may help:
[https://docs.portainer.io/v/ce-2.11/api/access](https://docs.portainer.io/v/ce-2.11/api/access)

**Comment by JazzFisch** [comment]
I have updated the wiki documentation to reflect this guide.
