### ISSUE TITLE
[Feature Request] improved localization of open weather api displayed weather

### ISSUE THREAD

**Issue by karmarcharger** [benphelps/homepage#280]
![C4884CE0-0D40-4EB5-B72F-43872E2C90B4](https://user-images.githubusercontent.com/10364143/192273103-e7aff5e0-6fa6-489c-b13c-ed03097c7c3b.jpeg)
![02647816-2726-47AA-B99F-2E7E40F62B05](https://user-images.githubusercontent.com/10364143/192273124-44ec8eb1-acb3-49ac-85bc-7024d3c9e573.jpeg)
The naming of weather is abit strange, perhaps heavy intensity rain could be heavy rain, and broken clouds could be cloudy?

**Comment by benphelps** [comment]
This is given from the weather provider, so it's not something we can change :(
