### ISSUE TITLE
[Bug] [Mobile] Layouts not showing and info widgets changes position continously.

### ISSUE THREAD

**Issue by luckkmaxx** [benphelps/homepage#287]
**Describe the bug**
In mobile version, the layouts arent sown. Maybe because logically is a smaller screen, but maybe we could control zooming?
And for info widgets its similar issue. We cant divide data like:
[top] cpu & ram
[new row] disk1 & disk2
[new row] disk 3
[new row] searchbar
At least in spanish and my android setup, the content  of whole row of resources is continously moving to a second row depending on the lenght of text shown on each refresh.

**Comment by JazzFisch** [comment]
Can you provide a screenshot of the issue you are seeing?

**Comment by luckkmaxx** [comment]
sure!
![Screenshot_20220927-180329_Firefox_Nightly](https://user-images.githubusercontent.com/14180594/192589157-15c0ae30-aec1-4493-be5f-c84828bee6b7.png)
![Screenshot_20220927-180252_Firefox_Nightly](https://user-images.githubusercontent.com/14180594/192589158-c0d924a8-d04f-428e-b13b-fe19667c2ec3.png)

**Comment by luckkmaxx** [comment]
About info widget it can be managed with large labels to force change a block to the next row.
Just like:
![Screenshot_20220927-212641_Firefox_Nightly](https://user-images.githubusercontent.com/14180594/192618110-ea309195-e828-4cb0-b552-62e8c8b5bb38.png)

or  this:
![Screenshot_20220927-212709_Firefox_Nightly](https://user-images.githubusercontent.com/14180594/192618164-7ffbecd7-9036-448d-b6f6-6a5556c8370f.png)

**Comment by benphelps** [comment]
This has been fixed to some degree and the translations keys have been shortened for that section.

**Comment by luckkmaxx** [comment]
Hi! Maybe I should to set a different issue for both problems.
Regarding Layouts, do you think is it possible to make it work on mobile devices? Just want to be able to have two columns, altough we need to set a short title for each service
