### ISSUE TITLE
weather widget language

### ISSUE THREAD

**Issue by lutao114** [benphelps/homepage#299]
Can I change the language of the weather widget ？

**Comment by benphelps** [comment]
The weather widget language uses the same language as set on the homepage, depending on the provider, it may not have that language supported and falls back to English.

**Comment by lutao114** [comment]
I found a help document and need to add a parameter

- openweathermap:
    label: XXX #optional
    lang: zh #Language for the weather widget
    latitude: XX.XXX
    longitude: XXX.XXX
    units: metric
    apiKey: XXXXXXX

[https://www.likecs.com/ask-350392.html?sc=1400](url)
