### ISSUE TITLE
[Feature Request] Add Font Awesome Icons

### ISSUE THREAD

**Issue by Estradamis** [benphelps/homepage#305]
**Is your feature request related to a service? Please describe.**
Add Font awesome to the Dashboard so Groups can add Font Awesome Icons in title

**Is your feature request related to a problem? Please describe.**
No, just feature request

**Comment by joevaughan** [comment]
I think this is 2 feature requests in one. 

1. Please add 'icons' capability to Group Titles 
2. Please allow font-awesome icons anywhere we have "icon:" 

e.g. 

- Group B:
    icon: fa-sharp fa-solid fa-object-group
    - Radarr:
        icon: radarr.png
        href: http://radarr.host/
        description: Movie management

or something like that.

**Comment by danielwerner86** [comment]
Seconded. I would love this, especially for bookmarks instead of only supporting abbreviations.

**Comment by Mega-Volti** [comment]
Now that Material Design Icons and group icons for services were added, should this be considered done/closed or is adding Font Awesome in addition to MDI still relevant? Personally, I don't see a point in having both.

**Comment by shamoon** [comment]
Agree
