### ISSUE TITLE
[Bug] Resources cannot display externally mounted disk information?

### ISSUE THREAD

**Issue by bverkron** [benphelps/homepage#308]
**Describe the bug**

When I try to show free space for an externally mounted HDD I get an API error

**Expected behavior**
I would expect it to be able to show the available space on the external drive

**Screenshots**
![image](https://user-images.githubusercontent.com/19174503/193178962-9a49561d-94f0-4631-95e1-4cc40582612e.png)

**Configuration**

```
- resources:
    label: External
    disk: /media/ext_storage
```

**Additional context**

If I set the disk proper to just `/media/` or anything else that I've tried it works. I assume this because `ext_storage` is a mounted external drive?
```
$ ls -alh /media/
total 16K
drwxr-xr-x  4 root    root 4.0K Feb  3  2022 .
drwxr-xr-x 23 root    root 4.0K Sep 21 06:57 ..
drwxrwxrwx  5 root    root 4.0K Dec 13  2021 ext_storage
```

```
$ cat /proc/mounts | grep ext_storage
/dev/sdb2 /media/ext_storage ext4 rw,relatime,data=ordered 0 0
```

**Comment by jeremyjohn** [comment]
Are you using docker? If you are, you need to add it as a volume in the docker compose file.

**Comment by bverkron** [comment]
Ah that did it! Thanks!

**Comment by bverkron** [comment]
On mobile so can’t get the exact syntax but basically, under the volumes section…

`- /path/to/volume/on/host/:/path/in/container/`

**Comment by adves34** [comment]
Worked ! Thanks for your help

Le 3 nov. 2022 à 16:15, bverkron ***@***.***> a écrit :



On mobile so can’t get the exact syntax but basically, under the volumes section…

- /path/to/volume/on/host/:/path/in/container/

**Comment by adves34** [comment]
worked ! thanks for your help
