### ISSUE TITLE
[Feature Request] Open tab in same window

### ISSUE THREAD

**Issue by Facinorous-420** [benphelps/homepage#314]
**Is your feature request related to a service? Please describe.**
It would be cool if there was an option to make certain services/bookmarks open in the same window, rather than opening a new tab always.

**Comment by benphelps** [comment]
You can change this, https://github.com/benphelps/homepage/wiki/Settings#link-target

**Comment by Facinorous-420** [comment]
> You can change this, https://github.com/benphelps/homepage/wiki/Settings#link-target

I appreciate the link! I saw this previously, but I could not seem to figure out how to make this work for only a specific bookmark/service which lead me to create this issue. I am sorry, I should have been more specific that I was talking about individual bookmarks/services rather than them all.
