### ISSUE TITLE
Sonarr widget false information

### ISSUE THREAD

**Issue by 2ndwonder** [benphelps/homepage#315]
Sonarr says there are still series wanted but I already have everything

<img width="404" alt="image" src="https://user-images.githubusercontent.com/24813161/193421917-68997564-bc9e-4468-96fd-f026e8f11c19.png">

**Comment by benphelps** [comment]
It's showing missing episodes, the data comes directly from Sonor.  If you think the data is wrong, you'd have to consult with the Sonor project about that.

**Comment by 2ndwonder** [comment]
Never mind.. I forgot Sonarr was monitoring a new show. Thought it was already downloaded. My bad
