### ISSUE TITLE
[Feature Request] Hide user options

### ISSUE THREAD

**Issue by AdrienVIN** [benphelps/homepage#318]
**Is your feature request related to a service? Please describe.**
Option to hide settings

**Additional context**
a boolean in settings.yaml to hide those info : 
![image](https://user-images.githubusercontent.com/85898436/193432086-4d15ae4c-df76-49ed-bcea-4a944d972897.png)

**Comment by benphelps** [comment]
If you set the values in your `settings.yaml` file, the controls will be hidden.

https://github.com/benphelps/homepage/wiki/Settings#theme
