### ISSUE TITLE
Disk Resources Widget doesn't work for samba mount

### ISSUE THREAD

**Issue by devcircus** [benphelps/homepage#32]
Great work! This is an awesome homepage/dashboard app. Going to log a couple of issues. Put it on the back burner if you wish, just wanted to log the behavior I am seeing. Thanks again.

## Expected Behavior
If I use the following config, I expect to see the disk information for the chosen mount:

```yaml
- resources:
    disk: /mnt/myMount

```

## Actual Behavior
It shows the information for the primary disk, mounted at "/", instead

## Steps to Reproduce the Problem

  1. mount a samba share on your system
  2. write widget config to show information for this mount

## Specifications

  - Version: First release
  - Device/OS: RPI4 - Ubuntu 22.04 aarch64

**Comment by benphelps** [comment]
Hey, thanks for reporting!

I am able to mount a Samba share locally, so I'll check this out.

**Comment by Trever123** [comment]
I had the same problem at first. If you are running this in docker, make sure you also mount your external mount in docker as well. For example i have a mount on the host under `/mnt/storage` which wasn't being picked up so made sure to add another mount to the docker container under `/mnt/storage` to `/mnt/storage` and it just worked.

**Comment by trackermb** [comment]
Hi I have a smb share and have been able to add it.

I have added it to the environment in the docker compose 
 volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /media:/media
            - /archive:/archive # this is smb share 
Then in the widget yaml I just added 
         - resources:
               label: Archive
               disk: /archive
and it worked perfectly.  Hope this helps.

**Comment by amnesiacsardine** [comment]
> Hi I have a smb share and have been able to add it.
> 
> I have added it to the environment in the docker compose
> 
> volumes: - /var/run/docker.sock:/var/run/docker.sock - /media:/media # **this is a USB drive** /actualmount:/containermount - /archive:/archive # **this is smb share** /actualmount:/containermount
> 
> Then in the widget yaml I just added
> 
> ```
>      - resources:
>            label: Archive
>            disk: /archive
>      - resources:
>            label: Media
>            disk: /media
> ```
> 
> and it worked perfectly. Hope this helps.

I would advise adding :ro (for read-only) at the end of your volume lines. Just in case. Like such `/media:/media:ro`

**Comment by devcircus** [comment]
Facepalm.
Thanks everyone. 

And once again, Great work on this.
