### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by filwall** [benphelps/homepage#321]
The ambiant color is stuck at red on my laptop and desktop and changing settings.yaml does not change thoes two. It is working properly on my mobile.

My laptop is windows 10 and my desktop is kubuntu 22.04

I have tried to clear cookies and incognito mode and the red does not go away

<img width="974" alt="public" src="https://user-images.githubusercontent.com/113920743/193445467-f8762193-2065-4933-bc0f-fc6089a59cf3.png">
<img width="931" alt="private" src="https://user-images.githubusercontent.com/113920743/193445475-d62d95b6-9f89-45af-857e-fb7334da0808.png">

This is my phone

![Screenshot_20221002-103648_Brave](https://user-images.githubusercontent.com/113920743/193445565-61fc8764-6255-49d5-a18e-acd7ede2513f.jpg)

**Comment by C8opmBM** [comment]
Press the refresh button in bottom right corner.

**Comment by fladerfilip** [comment]
I have also tried that

**Comment by benphelps** [comment]
Do you have a dark mode style extension installed?

**Comment by filwall** [comment]
That did the trick, sorry for wasting your time
