### ISSUE TITLE
Lidarr missing in Wiki

### ISSUE THREAD

**Issue by 2ndwonder** [benphelps/homepage#323]
It's not really a bug but just FYI. Lidarr is missing in the Wiki page

<img width="240" alt="image" src="https://user-images.githubusercontent.com/24813161/193468491-bffe7d61-a08d-418c-ab97-a6c997916e27.png">

**Comment by JazzFisch** [comment]
So it is.  Fixed.  See here: https://github.com/benphelps/homepage/wiki/Service-Widgets#lidarr.
