### ISSUE TITLE
Control button in Plex inverted for me !

### ISSUE THREAD

**Issue by Tataukee** [benphelps/homepage#325]
The play button is showing when a content is playing .. shouldn't be the pause button instead ? So I am not able to control it .. No that much howto in the wiki ..

![02Oct2221-18](https://user-images.githubusercontent.com/26170999/193472182-9e19ed27-8180-4214-bf29-b0153ebc2ce4.png)

**Comment by ShlomiPorush** [comment]
Unlike Jellyfin & Emby you can't control the media from Plex via Tautulli. This icon is just for a placeholder.

**Comment by Tataukee** [comment]
Thanks ShlomiPorush . Would love this feature but I guess since it's a Plex via Tautulli that explains everything .

**Comment by benphelps** [comment]
Yeah, sadly Plex doesn't expose an API other than open and close media, and even that requires a Plex Pass.

The icon shows the _state_ instead of the _action_.
