### ISSUE TITLE
Feature request: Hide API keys from API calls

### ISSUE THREAD

**Issue by jackblk** [benphelps/homepage#33]
Awesome work @benphelps :).

This is a simple request but I think it will cost a lot of time & redesign to do, so feel free to consider the feature or just close it if it's not what you plan to do with this project.

Why:

* I want to host the homepage publicly on the internet but I don't want to expose my API keys of my services. Currently if we inspect the network requests we will know all the API keys.
* If I want to only show my homepage publicly but my services are not public, the API call from frontend will fail. For example, I can configure it to call to `http://sonarr:8989`, if it's within the Docker network then it can call, but from my FE it won't be able to.

It would be great if we can use backend to relay the API calls.

**Comment by benphelps** [comment]
Hey, thanks for checking out my project :)

I agree, this is something that really would be needed for any use case outside of an internal network.  I have a few ideas on what could be done but you're right, it would take a bit of reworking.

It might be valid that _all_ requests ultimately end up passing through the backend proxy.

**Comment by benphelps** [comment]
I kept the API requests on the frontend purely for performance, and since I personally intended to run this privately, any proxy functionality that currently exists is to bypass CORS restrictions only.

**Comment by benphelps** [comment]
Alright....  This was a big one.

I've fully refactored the entire widget system to pass all API calls through the backend, using mostly reusable API handlers, along with a few specific ones for the special cases.  No secrets are ever sent to the frontend now, and everything is handled in the services widget proxy endpoint.

I've locally tested every widget, so I'm quite sure everything should still function in the exact same way with no changes on your side.

**Comment by jackblk** [comment]
Great work @benphelps, let me try it out on my setup :).

Is there anything else we need to implement to close the ticket?

**Comment by benphelps** [comment]
Nope, it should all be proxied now.  Just waiting a bit for some other users to test it out to confirm everything is good.

**Comment by jackblk** [comment]
Looking good! I have tested my services and they are working nicely so far (except for Openweathermap, it's still leaking).

I'll close this ticket as implemented!
