### ISSUE TITLE
Transmission widget bug 

### ISSUE THREAD

**Issue by kraizelburg** [benphelps/homepage#336]
**Describe the bug**
Transmission widget dissapears and throws an error after a few min idling 

**Expected behavior**
widget remains open and stable while idling

**Screenshots**
If applicable, add screenshots to help explain your 
<img width="814" alt="transmission widget bug" src="https://user-images.githubusercontent.com/81257448/194002367-9019e1ec-e06a-46d8-9311-3cfa1b688913.png">
problem.

**Configuration**
If applicable,

```yaml
# Please provide your service, widget or otherwise related configuration here
```

**Additional context**
Add any other context about the problem here. This includes things like:
 - Service version or API version
 - Docker version
 - Deployment method
 - Sample YAML configurations

**Comment by kraizelburg** [comment]
Latest stable 3.0 in docker container

Enviado desde mi iPhone

El 5 oct 2022, a las 17:47, Ben Phelps ***@***.***> escribió:

﻿

What version of transmission are you running?

**Comment by JazzFisch** [comment]
@kraizelburg can you please post your docker-compose section for transmission?  I am unable to reproduce locally.

**Comment by kraizelburg** [comment]
> @kraizelburg can you please post your docker-compose section for transmission? I am unable to reproduce locally.

this is my docker compose for transmission:

version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

**Comment by mtklr** [comment]
I realize this is closed, but wanted to mention i was having similar issue - what fixed it for me was this widget config under Transmission service entry in `services.yaml`:

```
widget:
    type: transmission
    url: http://host:9091/transmission/rpc
```

Ref: [transmission rpc spec](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#23-transport-mechanism)

Hope this helps.
