### ISSUE TITLE
[Bug]??? Show Docker Stats on Hompage 

### ISSUE THREAD

**Issue by peterthepeter** [benphelps/homepage#346]
I have installed Homepage on my Unraid server in a Docker Container. I have added a few Docker containers to the home page and I can also see in the Homepage if they are running or not (Dot is green or grey).

Was it not possible to click on the green Dot in an older Homepage version and then see the stats of the container?

That no longer works for me.

**Comment by benphelps** [comment]
What browser are you using?

**Comment by peterthepeter** [comment]
I tryed Safari, Chrome and Edge on my Macbook Pro, and also on my Windows PC.
It didn't work anywhere.

**Comment by Rufmord** [comment]
Had the same problem in #334
