### ISSUE TITLE
[Feature Request] IPhone home page button open homepage as webapp

### ISSUE THREAD

**Issue by karmarcharger** [benphelps/homepage#350]
Some websites (homer/libreddit) when I add them to my homescreen book mark, when I click the button it hides the browser url and back button, homepage does not.
![2433F3FF-4B68-41B2-8647-BAB357708E36](https://user-images.githubusercontent.com/10364143/194688839-db349076-8125-4716-9069-edb0105d5c8f.png)
![C07E6004-6DC9-4E45-B557-6BB2AAA62875](https://user-images.githubusercontent.com/10364143/194688843-8eb118bc-171b-46bc-9e89-ad1bc8446778.png)
 My workaround was to make the homescreen bookmark with homer/libreddit then changing the homepage port to the one that was bookmarked.

**Comment by karmarcharger** [comment]
This is very useful as when you click the links in the web app it opens a separate instance of safari rather then flooding you current safari app with new opened pages.

**Comment by szczottie** [comment]
Great workaround! 

All we need is simple code to make it work without workarounds

<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="apple-touch-icon" href="/icons/apple-icon.png">

**Comment by benphelps** [comment]
The latest changes should now create a very nice iOS bookmark.  Give it a try on `main` if you're brave.

**Comment by benphelps** [comment]
This has been released :)
