### ISSUE TITLE
[Bug] No local favicon with main (94a518f, 8 oct. 2022)

### ISSUE THREAD

**Issue by Nonoss117** [benphelps/homepage#353]
**Describe the bug**
It seems that local favicon isn't working anymore

`settings.yaml`
```yaml
favicon: /images/homepage3bis.ico
```

**Information**
 - main (94a518f, 8 oct. 2022)
 - I share the same `settings.yaml` file with `main (94a518f, 8 oct. 2022)` and `v0.4.4 (88c7743, 5 oct. 2022)`. Local favicon is ok with latest

**Comment by benphelps** [comment]
This is a sad case of the browser preferring the icon at /favicon.ico over the one set in the html meta tag :(

Can you try mounting the icon directly?

```yaml
volumes:
  - /my/images/homepage3bis.ico:/app/public/favicon.ico
```

**Comment by benphelps** [comment]
I'm not even sure that'd work, because it's a case of "can't make everyone happy".  By supplying the proper meta tags and browser config files for supporting app bookmarks, homescreen bookmarks, etc, it has a very high chance of breaking custom favicons.

The browser tends to look everywhere for an alternative source of an image before using the favicon meta tag.

**Comment by Nonoss117** [comment]
I mounted the favicon:
`/mnt/user/appdata/homepage/images/homepage3bis.ico:/app/public/favicon.ico`
I tested with Firefox, Chrome, in a private window.
And you're right, it doesn't work. Still the default favicon showing.
It doesn't matter, it's not very important.

Thanks for your job, and for  your help with all issues from every one, and thanks to [JazzFisch](https://github.com/JazzFisch) too :-)

**Comment by Nonoss117** [comment]
Just one more word, in my container, I mounted each "favicon" image directly :
```
/My/Local/Path/homepage3bis.ico:/app/public/favicon-16x16.png
/My/Local/Path/homepage3bis.ico:/app/public/favicon-32x32.png
```

And my local favicon is back. :-)
Now I will create 2 local images with the right resolution, and mount the right image.

**Comment by benphelps** [comment]
> Just one more word, in my container, I mounted each "favicon" image directly :
> 
> ```
> /My/Local/Path/homepage3bis.ico:/app/public/favicon-16x16.png
> /My/Local/Path/homepage3bis.ico:/app/public/favicon-32x32.png
> ```
> 
> And my local favicon is back. :-) Now I will create 2 local images with the right resolution, and mount the right image.

Yeah, and you might have to create more depending on the browser in use.  Quite annoying how nonstandard something you think is standardized actually ends up being.
