### ISSUE TITLE
Radarr and Sonarr API Error

### ISSUE THREAD

**Issue by 2ndwonder** [benphelps/homepage#37]
For Radarr and Sonarr I'm getting API error.. what could be the reason? I put it like this in the yaml file

    - Radarr:
        icon: radarr.png
        href: url here
        description: Movies Managment
        container: radarr
        widget:
          type: radarr
          url: http://192.168.1.2:7878
          api: apikeyhere

    - Sonarr:
        icon: sonarr.png
        href: url here
        description: Series Managment
        container: sonarr
        widget:
          type: sonarr
          url: http://192.168.1.2:8989
          api: apikeyhere

**Comment by 2ndwonder** [comment]
Nevermind, I fixed it. I had to put host instead of local IP and the API section needs to be key instead of API

**Comment by rnagabhyrava** [comment]
what do you mean by host instead of local IP? can you paste your working services.yaml file? Thanks

**Comment by 2ndwonder** [comment]
Host is if you have it on the web. and local IP is your local IP address on which machine you're running ''homepage''
what you need my services.yaml for :D

**Comment by rnagabhyrava** [comment]
Thanks. Sorry I am new to configuring via yaml files and having trouble configuring, thought having someone's yaml file would be handy to edit.

**Comment by 2ndwonder** [comment]
you have a wiki page for this, I can help you with your yaml file but not sharing mine

**Comment by rnagabhyrava** [comment]
Reading the wiki. Thanks again!
