### ISSUE TITLE
[Bug] Upon loading page it takes a long time to get the Services to display

### ISSUE THREAD

**Issue by jmlc11** [benphelps/homepage#375]
**Describe the bug**
Every time the page loads it only shows the Bookmarks and it takes around a minute to show the Services.

**Expected behavior**
Services should load at the same time as the bookmarks

**Screenshots**
This is what i see during the first 30 to 60 seconds:
![image](https://user-images.githubusercontent.com/6006781/195148407-128a3f9e-341f-4b2b-987b-80514d9cb37b.png)
This is what i see after waiting like 30 or 60 seconds:
![image](https://user-images.githubusercontent.com/6006781/195148702-0f70e96d-341f-4160-84b5-affb0fbecb7f.png)

**Additional context**
This just happened out of nowhere, maybe after one of the updates.

**Comment by JazzFisch** [comment]
Is there anything odd in the browser console window?

**Comment by jmlc11** [comment]
Right now the issue is not happening.

I did not test it locally, so I suspect it had something to do with all the duckdns issues from the las 3 weeks. 
Will give it one day and if it does not happen again I will close this bug.

Thanks.
