### ISSUE TITLE
NZBGet API Error

### ISSUE THREAD

**Issue by 2ndwonder** [benphelps/homepage#38]
Did I miss something? getting API Error

- Download Clients:
    - NZBGet:
        icon: nzbget.png
        href: url here
        description: NZB Download Client
        container: nzbget
        widget:
          type: nzbget
          url: url here
          username: nzbget
          password: tegbzn6789

**Comment by benphelps** [comment]
I'll need more information about what the error was exactly.

**Comment by 2ndwonder** [comment]
I'm not seeing anythings in the log files of "Homepage" I only see "NZBGet API Error" on Homepage itself on the NZBGet service.

https://imgur.com/a/Y3d0qfN

**Comment by 2ndwonder** [comment]
Jellyfin API also not working..

**Comment by ilusi0n** [comment]
Click f12 in your browser and click on the console and check what error is being displayed there.
Would be interesting thinking on some way to save the logs :D

**Comment by 2ndwonder** [comment]
ehh I'm on Mac safari.

**Comment by 2ndwonder** [comment]
here you go

https://pastebin.com/Q5PWj2ZQ

**Comment by 2ndwonder** [comment]
is it because there is 2FA like anthelia behind it?

**Comment by ilusi0n** [comment]
Probally, in my case I don't have nothing behind but my infrastructure is only local. I can't vouch for nzbget but jellyfin it's working.
I had a problem with jellyseerr, not quite like yours but worth to try. If your containers are on the same network, instead of putting your domain url, use the container name like http://jellyfin:8096

**Comment by 2ndwonder** [comment]
yeah I just checked.. it's 2FA what disables it. thanks anyways

**Comment by ilusi0n** [comment]
Probably the project needs something to take that into account. I don't have the knowledge to do it, so I can't help your there.

**Comment by 2ndwonder** [comment]
it's 2FA guys, problem is solved. gonna close this issue. thank you
