### ISSUE TITLE
[Bug] Unraid Docker + Unifi widget = Missing Widget Type: unifi

### ISSUE THREAD

**Issue by kardo22** [benphelps/homepage#382]
**Describe the bug**
No widget seems to be found?

**Configuration**
In services.yaml:

    - Unifi Controller:
        icon: unifi.png
        href: https://10.1.1.30:8443  
        description: Unifi wifi controller
        widget:
          type: unifi
          url: https://10.1.1.30:8443   
          username: myuser
          password: mypass

**Additional context**
Can't get unifi widget to work, read the documentation and i cannot understand what might be wrong, it just tells me "Missing Widget Type: unifi" which inidicates that unifi is the wrong thing to type there, but in the documentation it clearly says to type unifi.

**Comment by Nonoss117** [comment]
May be you are in this case : https://github.com/benphelps/homepage/issues/368#issue-1403055959

**Comment by jay-bowee** [comment]
This project posts a wiki on how to do something and waits days before the actual release of the software that does the thing they wrote it would do. I wasted hours trying to get proxmox to work before finding that out. At least they could advise the version numbers in the wiki on which version actually does what.

**Comment by nimodius** [comment]
You should probably ask for a refund.

C’mon man

**Comment by benphelps** [comment]
> This project posts a wiki on how to do something and waits days before the actual release of the software that does the thing they wrote it would do. I wasted hours trying to get proxmox to work before finding that out. At least they could advise the version numbers in the wiki on which version actually does what.

It's called beta/alpha testing.  If you want the latest cutting edge version, simply change your docker branch to `main` instead of `latest`.

**Comment by benphelps** [comment]
> This project posts a wiki on how to do something and waits days before the actual release of the software that does the thing they wrote it would do. I wasted hours trying to get proxmox to work before finding that out. At least they could advise the version numbers in the wiki on which version actually does what.

By all means, you're free edit the wiki and make these suggested changes :)
