### ISSUE TITLE
[Bug] CoinMarketCap widget pulls data directly from coinmarketapi everytime you visit your homepage.

### ISSUE THREAD

**Issue by kardo22** [benphelps/homepage#383]
**Describe the bug**
Everytime i refresh or visit my local homepage and i have the coinmarketcap widget active it pulls a request from coinmarketcap api.

**Expected behavior**
I expected since its set to refresh every 1 hour that it would pull the data from coinmarketcap api once every hour and display this data statically for that hour.

**Additional context**
Problem with this is that you'll quickly run out of "daily credits" and then your coinmarketcap api will block any incoming requests for the next 24 hours.

**Comment by kardo22** [comment]
On further inspection, perhaps it only pulls everytime you hit refresh icon, i have been fiddling with this alot today, it might not be an issue once you are up and running. Looking at the pulls from the api it looks more like it is everytime i hit the refresh icon and not everytime i actually render the page.

**Comment by benphelps** [comment]
The time selection is for the data range of the price quote, i.e., the average price over the past hour, day, 7 days, etc.  Not how often to refresh the data.

**Comment by kardo22** [comment]
> The time selection is for the data range of the price quote, i.e., the average price over the past hour, day, 7 days, etc. Not how often to refresh the data.

My bad, perhaps a new feature to limit the refreshes from the widget would be good? Most users will not have a paid account and if you set your homepage to be your startpage on your browser and also your new tab page you'll run out of api calls really quick

**Comment by kardo22** [comment]
author explained, working as intended
