### ISSUE TITLE
[Feature Request] Make version indicator a link to the change log

### ISSUE THREAD

**Issue by ysarkain** [benphelps/homepage#391]
**Is your feature request related to a service? Please describe.**
Have the version number in the bottom right corner link to the change log on github

**Is your feature request related to a problem? Please describe.**
No, it would just be nice and a pretty easy thing to change.

**Additional context**
Just think it would be nice so I don't have to google "benphelps homepage" every time there's an update on unraid to see what new features or changes there are!

**Comment by szczottie** [comment]
+1

**Comment by JazzFisch** [comment]
Right now it is a link if you are on the "latest" image and not the "main" image and there is an update for your version.  Do you want it to always be a link?

**Comment by shamoon** [comment]
Actually this was already completed in https://github.com/benphelps/homepage/commit/4ec8fc1350ccff5b1e44d28dfd9ff1a10bd492bd and will be in the next release.
