### ISSUE TITLE
[Bug] Unifi  controller api error

### ISSUE THREAD

**Issue by frozendark01** [benphelps/homepage#393]
**Describe the bug**
 - Unifi widget is returning api error but in services.yml service is working as intended.
 Do i miss something?
![image](https://user-images.githubusercontent.com/42968687/196028512-39cf0d84-4f39-4c66-aaf6-beafb658400f.png)

Widget.yml screenshot
![image](https://user-images.githubusercontent.com/42968687/196029002-17e5b664-2150-4263-88ff-66a8cf22da62.png)

Settings.yml screenshot
![image](https://user-images.githubusercontent.com/42968687/196029137-8c1546f5-4f95-4e46-8c13-6262630b12bf.png)

 
Browser log:

![image](https://user-images.githubusercontent.com/42968687/196029184-2b6d7299-427d-49c5-81d4-0fa2573a4d91.png)
![image](https://user-images.githubusercontent.com/42968687/196029355-d06210c1-5ea1-44ae-9969-2afaf7345a46.png)

I think api is expecting port 443 insted of 8443

Homepage container log
![image](https://user-images.githubusercontent.com/42968687/196029378-e10a4b65-8ac5-4a68-9fb7-973e4eab56ff.png)

**Comment by GertJanH** [comment]
you also need to provide a url user en password in de widgets.yaml

- unifi_console:
    url: https://192.168.1.9:8443
    username: John
    password: p@ssw0rd

**Comment by frozendark01** [comment]
Yes, thank you @GertJanH it works. 
In wiki on Information widget that was not provided but that was a trap :)
