### ISSUE TITLE
[Feature Request] Add auth header to widget requests

### ISSUE THREAD

**Issue by ThisIsNoahEvans** [benphelps/homepage#40]
Hi, loving Homepage so far but I have one question - is it possible to add some sort of way to allow Homepage to pull data from Pi-hole etc when it's behind auth & a reverse proxy?

I run Pi-hole behind Authelia and Nginx Proxy Manager - meaning that when going to pihole.mydomain.com, I have to sign in with a username & password before I see the Pi-hole admin page.
Authelia can bypass auth based on headers and URL paths - for example I currently bypass auth for Pi-hole's `/admin/api.php` so Homepage can pull data. I'm not too keen on this for privacy reasons however.
If I could supply a header and value in Homepage and then add that to my Authelia config, it would ensure that Homepage's API requests to Pi-hole only bypass the username/password prompt. I don't think any actual authentication keys or whatever is needed here - as long as the value of the header is unique & known to Homepage and Authelia, the request can be specifically allowed through.

Thanks, I hope this is possible - and I'm more than happy to assist in testing it :)

**Comment by benphelps** [comment]
Now that the widget API refactor is complete, this seems like a much more achievable request.

I think it should be pretty easy to include HTTP Basic Auth support for most widgets as a simple configuration option.

I'll do some work locally and see if I can get something working.

**Comment by benphelps** [comment]
This has been in place for quite a while now, I'll get the wiki docs updates to reflect it.
