### ISSUE TITLE
[Bug] Pi-Hole returning NaN

### ISSUE THREAD

**Issue by jbeck22** [benphelps/homepage#401]
I am running version v0.4.18 (4ea2798, Oct 15, 2022)
 and Pi-hole is returning NaN instead of actual information.

I have tried the proxy: true trick, but that didn't help either.

I also tried to add in the API key, just in case it was needed, but that didn't change anything either.

My setup is currently running on unRAID and I'm targeting my pi-hole instance directly using IP address.

Here is the code snippet ----  

    - Pi Hole:
        href: http://192.168.1.254/
        icon: pihole.png
        widget:
          type: pihole
          url: http://192.168.1.254/

**Comment by isuelt** [comment]
I have the same problem! I also have a PiHole docker on Unraid 

- Docker Tag 2022.10 
- Pi-hole v5.13
- FTL v5.18.2
- Web Interface v5.16

**Comment by TobiasDax** [comment]
i am also quite new to this tool, but try deleting the trailing / at the end of both URLs, that did the trick for me for some tools (not using piHole)

**Comment by rohan3au** [comment]
I'm also facing this issue, have tried all steps OP tried.

**Comment by shamoon** [comment]
What does `curl -L http://PIHOLEIPORDOMAIN/admin/api.php` show? Also depending on some networking specifics, sometimes using http://pi.hole will work instead of an IP

**Comment by xenogear74** [comment]
I was originally getting API error, but using your suggestion and switching to pi.hole I am now getting NaN for all my values. 
When I run the CURL you metioned i get this: 
`{"domains_being_blocked":1266903,"dns_queries_today":42900,"ads_blocked_today":6791,"ads_percentage_today":15.829837,"unique_domains":9078,"queries_forwarded":33327,"queries_cached":2651,"clients_ever_seen":18,"unique_clients":16,"dns_queries_all_types":42900,"reply_UNKNOWN":150,"reply_NODATA":1546,"reply_NXDOMAIN":1062,"reply_CNAME":20701,"reply_IP":17974,"reply_DOMAIN":226,"reply_RRNAME":0,"reply_SERVFAIL":1157,"reply_REFUSED":0,"reply_NOTIMP":2,"reply_OTHER":0,"reply_DNSSEC":0,"reply_NONE":0,"reply_BLOB":82,"dns_queries_all_replies":42900,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1666514732,"relative":{"days":0,"hours":11,"minutes":43}}}`

**Comment by shamoon** [comment]
That looks ok, so we know your pihole is alive and well. The final question is whether it’s reachable from inside the container, eg `docker exec homepage ping pi.hole`, if not you will need to sort out why your container(s) can’t reach it (eg networking)

**Comment by xenogear74** [comment]
> That looks ok, so we know your pihole is alive and well. The final question is whether it’s reachable from inside the container, eg `docker exec homepage ping pi.hole`, if not you will need to sort out why your container(s) can’t reach it (eg networking)

you're a genius sir! added homepage to the bridge network as well (using dockstarter) and it's working when I use the IP. For some reason it doesn't work when I use pi.hole but that's a fight for another day lol
