### ISSUE TITLE
[Feature Request] Unifi widget label!

### ISSUE THREAD

**Issue by frozendark01** [benphelps/homepage#411]
**Is your feature request related to a service? Please describe.**
Hey, can be add a label to Unifi Controller widget? like:

- unifi_console:
    **_label: my network_**
    url: https://unifi.host.or.ip:port
    username: user
    password: pass

**Comment by shamoon** [comment]
It should already show the name of your device / network, no?

**Comment by frozendark01** [comment]
> It should already show the name of your device / network, no?

![image](https://user-images.githubusercontent.com/42968687/196720875-5842f790-9966-48c2-93dd-2566a492090c.png)
this is how it looks to me

**Comment by shamoon** [comment]
Ah yea there normally would be a name at the top there. It seems there are a few different situations out there for how to get info like that. Can I ask what type of device you're using / or how you're running the controller?

**Comment by frozendark01** [comment]
it is docker container image from linuxserver

**Comment by shamoon** [comment]
Gotcha, in that case I think it will be fixed by #398. 

Just to make sure, would you be willing to post the results of the commands here: https://github.com/benphelps/homepage/issues/394#issuecomment-1280058596 (using the correct URL / login of course)?

**Comment by frozendark01** [comment]
Here is the output.. just edited my wan ip :)


{
   "meta":{
      "rc":"ok"
   },
   "data":[
      {
         "_id":"5e88e27f9a532817b0f4d32a",
         "name":"default",
         "desc":"localnet",
         "attr_hidden_id":"default",
         "attr_no_delete":true,
         "anonymous_id":"4fd83465-22c8-4bc3-b2cc-4ef0f0b8a6c6",
         "health":[
            {
               "subsystem":"wlan",
               "num_user":10,
               "num_guest":0,
               "num_iot":0,
               "tx_bytes-r":23425,
               "rx_bytes-r":1495531,
               "status":"ok",
               "num_ap":2,
               "num_adopted":2,
               "num_disabled":0,
               "num_disconnected":0,
               "num_pending":0
            },
            {
               "subsystem":"wan",
               "num_gw":1,
               "num_adopted":1,
               "num_disconnected":0,
               "num_pending":0,
               "status":"ok",
               "wan_ip":"00.00.00.00",
               "gateways":[
                  
               ],
               "netmask":"255.255.255.255",
               "nameservers":[
                  "127.0.0.1"
               ],
               "num_sta":16,
               "tx_bytes-r":4246,
               "rx_bytes-r":10972,
               "gw_mac":"68:d7:9a:34:e0:64",
               "gw_name":null,
               "gw_system-stats":{
                  "cpu":"0",
                  "mem":"24",
                  "uptime":"2867325"
               },
               "gw_version":"4.4.56.5449062",
               "uptime_stats":{
                  "WAN":{
                     "latency_average":1
                  }
               }
            },
            {
               "subsystem":"www",
               "status":"ok",
               "tx_bytes-r":4246,
               "rx_bytes-r":10972,
               "latency":1,
               "uptime":21539,
               "drops":6,
               "xput_up":127.051,
               "xput_down":153.345,
               "speedtest_status":"Success",
               "speedtest_lastrun":1665603585,
               "speedtest_ping":2,
               "gw_mac":"68:d7:9a:34:e0:64"
            },
            {
               "subsystem":"lan",
               "lan_ip":"192.168.1.1",
               "status":"ok",
               "num_user":6,
               "num_guest":0,
               "num_iot":0,
               "tx_bytes-r":0,
               "rx_bytes-r":0,
               "num_sw":0,
               "num_adopted":0,
               "num_disconnected":0,
               "num_pending":0
            },
            {
               "subsystem":"vpn",
               "status":"ok",
               "remote_user_enabled":true,
               "remote_user_num_active":0,
               "remote_user_num_inactive":0,
               "remote_user_rx_bytes":0,
               "remote_user_tx_bytes":0,
               "remote_user_rx_packets":0,
               "remote_user_tx_packets":0,
               "site_to_site_enabled":false
            }
         ],
         "num_new_alarms":5
      }
   ]
}"%"

**Comment by frozendark01** [comment]
Great :), thanks.
