### ISSUE TITLE
[Bug] Services not auto-populating

### ISSUE THREAD

**Issue by JPDucky** [benphelps/homepage#412]
**Describe the bug**
Services not autopopulating/being discovered despite having properly configured docker integration

**Expected behavior**
Services populated in services.yaml, with default services.yaml

**Additional context**
- Happens with both "latest" and "main" images
- Docker version 20.10.19, build d85ef84
- Deployment method: Docker-compose/portainer stack

Now, I don't know if the documentation is a little unclear or if I'm just doing something incorrectly, but I can't seem to figure out how to get the services to auto-populate. Chances are it's me, and I can't get it to work. Let me know what else I may need to do or provide.

**Comment by shamoon** [comment]
Services don't auto-populate, you can add integration that shows container status (dot currently) and stats if you click it.

**Comment by JPDucky** [comment]
I'm... not entirely sure. Is anything supposed to be pulled in automatically- local links, services detected on the same host, etc.- on the vanilla config?

**Comment by shamoon** [comment]
Please read the wiki a bit more and try things out. You can "link" items in homepage with a docker container which will then show its status and some info if you click the status indicator, that's https://github.com/benphelps/homepage/wiki/Docker-Integration and you add `server` and `container` values to each item to tell homepage which container to look at

If you want to not add items to your services.yaml and let them "automatically" be discovered that's https://github.com/benphelps/homepage/wiki/Service-Discovery which requires using docker labels.
