### ISSUE TITLE
Custom Search now returns application error

### ISSUE THREAD

**Issue by Livefour2day** [benphelps/homepage#423]
Describe the bug
After the latest update now receives the following error after a search using a custom search engine.
"Application error: a client-side exception has occurred (see the browser console for more information)."

Expected behaviour
When using search bar in Homepage the results would open a new results page using my custom SearXNG engine, the IP address and port is not being used set in the widgets.yaml file the port that is specified in the widgets.yaml file is not being picked up and instead, the hosting server port is being used. This used to work flawlessly but has stopped since the last docker update.

Configuration

Unraid Docker
Using SearXNG search engine.

**Comment by lehezal** [comment]
Confirm same issue after update to new version of Homepage.

**Comment by shamoon** [comment]
Ah yea, I see the issue here.
