### ISSUE TITLE
Sonarr and Radarr both say 0 wanted

### ISSUE THREAD

**Issue by lukeeexd** [benphelps/homepage#43]
![image](https://user-images.githubusercontent.com/31347888/187297301-04663b46-ea2b-4ced-8d7a-d5ecc7936f42.png)
There's 25 wanted for Radarr and less for Sonarr but both show 0

**Comment by benphelps** [comment]
Alright, I'll take a look.  What versions of Sonarr and Radarr are you running, and is there anything special or otherwise non-standard with your installs?

**Comment by lukeeexd** [comment]
> Alright, I'll take a look. What versions of Sonarr and Radarr are you running, and is there anything special or otherwise non-standard with your installs?

Radarr: 4.1.0.6175
Sonarr: 3.0.9.1555

Nothing unusual about the install, just bare metal debian

**Comment by benphelps** [comment]
Radarr uses the `isAvailable` attribute for each movie as reported by the API to determine the wanted count.  So if no movies are marked as being `isAvailable = false`, the count would be 0.

Sonarr uses the `api/v3/wanted/missing` API endpoint for it's wanted count, so that value comes directly from Sonarr.

I'm not sure what could be the issue, other than some custom availability rules or other such thing.  I'm running nearly the same versions of both as you are.

**Comment by lukeeexd** [comment]
If I go to api/v3/wanted/missing on sonarr it says 

```
{
  "error": "Unauthorized"
}```

**Comment by lukeeexd** [comment]
It says I have 178 movies but I actually have 150 and 28 wanted so it seems to be combining wanted into total movies

**Comment by benphelps** [comment]
Fixed movies count in e72efe7.

If you can go to `/api/v3/wanted/missing?apikey=apikeyhere` and show me the output, that would help.

**Comment by lukeeexd** [comment]
```
{
  "page": 1,
  "pageSize": 10,
  "sortKey": "airDateUtc",
  "sortDirection": "descending",
  "totalRecords": 0,
  "records": []
}
```
I actually think Sonarr has none missing as all the shows are current ones so the episodes aren't released

**Comment by lukeeexd** [comment]
So it seems it's including wanted movies in "movies" count and not wanted in wanted. I have 172 total which includes wanted but it should show 26 for wanted and 146 under "movies"

**Comment by benphelps** [comment]
The check is simply done on the `isAvailable` flag, if `isAvailable` is `false` then I add it to a list of "wanted" movies, if it's `true`, I add it to a list of "have" movies.  Queued count comes directly from the `queue/status` endpoint.

I'm not sure what could cause the differences you're seeing, but this is all of the information I get from the API for building the stats.

**Comment by neildeadman** [comment]
I am having this issue but only in Radarr. Sonarr is working correctly.

I am using Radarr v4.1.0.6175

**Comment by C8opmBM** [comment]
Same here issue only on radarr. 
Sonarr displays wanted correctly. Only radarr has issues.

**Comment by hflatoey** [comment]
Same as C8opmBM here as well.

Version
4.1.0.6175

**Comment by JazzFisch** [comment]
Can you try again on the latest release?  Ben and I did some work to both clean this up as well as improve performance.

**Comment by lukeeexd** [comment]
> Can you try again on the latest release? Ben and I did some work to both clean this up as well as improve performance.

Mine still say 0 wanted

**Comment by C8opmBM** [comment]
Same here. Sonarr works as it should, radarr still has 0 wanted.

![Screenshot_20220919-133516~2](https://user-images.githubusercontent.com/60513190/190999768-fc02dfa9-c57d-4eaf-a5d2-8a4bc08cc327.png)

**Comment by JazzFisch** [comment]
Just to make sure we can narrow this down, which version of which software is presenting display issues:
Radarr:
* v3
* v4

Sonarr:
* v3
* v4

**Comment by neildeadman** [comment]
For me v3 and v4 of Sonarr seems to work fine.

I only use v4 of Radarr (same reason) which does not work.

**Comment by lukeeexd** [comment]
> I think it says "Queued" while downloading. Wanted is for missing. Could be wrong though.

Well yeah, the whole point of this issue is that it doesn't show wanted. And I'm saying it shows wanted when it's downloading something which is obviously not meant to happen

**Comment by benphelps** [comment]
Well, the values being shown _are_ the values given back from Sonarr and Radarr.

The wanted count, comes from the endpoint `wanted/missing`.
The queued count, comes from the endpoint `queue`.

**Comment by lukeeexd** [comment]
This is still happening

**Comment by lukeeexd** [comment]
I’m on version 4.1.0.6175 of radarr and version 3.0.9.1555 of sonarr

Nothing unusual about the install, just bare metal Debian no docker or any virtualisation

**Comment by benphelps** [comment]
For Sonarr:

We use the `totalRecords` value reported by this API to display the missing count: https://sonarr.tv/docs/api/#/Missing/get_api_v3_wanted_missing

We use the `totalRecords` value reported by this API to display the queue count: https://sonarr.tv/docs/api/#/Queue/get_api_v3_queue

For Radarr:

We use the `isAvailable` flags reported by this API to display the wanted and missing values (when isAvailable is false, it's counted as "missing"), https://radarr.video/docs/api/#/Movie/get_api_v3_movie

We use the `totalRecords` value reported by this API to display the queue count: https://radarr.video/docs/api/#/Queue/get_api_v3_queue

**Comment by neildeadman** [comment]
Sonarr for me seems to work, so I am just interested in Radarr.

You are using the `isAvailable` flag reported by the API. I ran a query from a terminal against my Radarr install and for movies I have in my collection, that is set to `true` and if they are missing then the value is `false` as you'd expect.

I'm therefore confused. From the sounds of it, the way you are counting the missing movies would seem to work, but the value of 0 is wrong and I don't understand how it is getting 0.

**Comment by Magelo** [comment]
For radarr, @benphelps, I think you are misinterpreting the value "isAvailable: false"... It mean it's not in local Radarr library **and not yet available**, it simply mean it is not available at all, it's a futur movie not available period. So counting "isAvailable: false" will result in a partial Wanted/Missing totalRecords...

You should count "sizeOnDisk": 0 to determined Wanted/Missing movies in a local Radarr Library.

**Comment by Magelo** [comment]
I have mixted result. Depending on certain combination with "Min availability" and "Status", the movie will be "isAvailable: false" or "isAvailable: true"...

Adding "Hancock 2" with min availability "Announced" status will be "Missing" and "isAvailable: true".
Adding "HAncock 2" with min availability "Released" status will be "Not available" and "isAvailable: false".

For Radarr widget, **Wanted** should be counted with "sizeOnDisk = 0" and **Have (Movies)** counted with "sizeOnDisk > 0". 

Queued is working properly.
