### ISSUE TITLE
[Bug] AdGuard Home only showing NaN

### ISSUE THREAD

**Issue by TobiasDax** [benphelps/homepage#432]
**Describe the bug**
AdGuard Home only displays NaN for all values

**Expected behavior**
Should display the correct values for all fields

**Configuration**
If applicable,
```
  - AdGuard Home:
     icon: adguard-home.png
     href: http://192.168.1.250
     widget:
         type: adguard
         url: http://192.168.1.250
         username: USER
         password: PASSWORD
```

**Additional context**
- AdGuard Home runs on its own IP Address (see above), Homepage runs on 192.168.1.123  

The main question is: Is there some additional configuartion that needs to happen on AdGuard Home for this to work or is something wrong with Homepage?

**Comment by shamoon** [comment]
Well, often these “bugs” are configuration issues.

Did you confirm the endpoint is working for you? Looks like it would be something like 
`curl -L -u 'username:password' http://192.168.1.250/control/stats`

(I don’t use adguard to double check that command but looks like that should be correct)

**Comment by trythatagain** [comment]
I'm experiencing the same problem, I too have Adguard on a separate ip to Homepage and the server using a macvlan.
I tried the curl command from my laptop and it works, but when I ssh into server and try the same command I get 'curl: (7) Failed to connect to 192.168.1.231 port 80: No route to host' error, so I'm assuming it's something to do with the macvlan and accessing it from the same pc. I'm running OMV as my NAS.

**Comment by trythatagain** [comment]
Just been doing a little duckduckgoing and it does look as though it's a macvlan problem, looks as though there are some work arounds, involving creating another macvlan. Not sure I'm going to do that, just for homepage to report a few stats, I might try adguard in a VM, but I'm lazy :) so I'll probably just leave it as is, especially as it works.

**Comment by shamoon** [comment]
Yea, macvlan networks can be tricky. Maybe look at using `network_mode: host` instead and then 
https://github.com/compose-spec/compose-spec/blob/master/spec.md#extra_hosts (if youre using compose)

OP, please re-open if theres truly a bug here.
