### ISSUE TITLE
[Bug] Language strings are broken after the WebUI Refreshes/Reloads/Regenerates

### ISSUE THREAD

**Issue by rursache** [benphelps/homepage#436]
**Describe the bug**
Installed homepage with docker like this:
```
docker run -d \
  --name homepage \
  --restart always \
  -p 80:3000 \
  -v /home/radu/.homepage:/app/config \
  -v /home/radu/.homepage/img:/app/public \
  -v /var/run/docker.sock:/var/run/docker.sock \
ghcr.io/benphelps/homepage:latest
```

After a fresh container install, I go to **localhost** and press the refreshes/reload/regenerate in the bottom right corner
From now on, all strings won't be localized in any language including english...

**Expected behavior**
Display the strings correctly even after refresh button is pressed

**Screenshots**
https://i.imgur.com/UCKlNMV.png

**Configuration**
Absolutly vanilla

**Comment by Nonoss117** [comment]
You can try to force the language,

`settings.yaml`
```yaml
language: fr
    #Currently supported languages: ca, de, en, es, fr, he, hr, hu, it, nb-NO, nl, pl, pt, pt-BR, ro, ru, sv, vi, yue, zh-CN, zh-Hant
```

**Comment by rursache** [comment]
i already did with english, russian and spanish

```yaml
language: en/ru/es
```

nothing fixes it

**Comment by JazzFisch** [comment]
This is happening because you mapped a folder over top of the /app/public folder inside of the container.  That folder is where all locales live.

**Comment by rursache** [comment]
so it should be
```sh
-v /home/radu/.homepage/images:/app/public/images
```
instead of 
```sh
-v /home/radu/.homepage/images:/app/public
```
thanks for the help, it works now
