### ISSUE TITLE
[Feature Request] Authelia

### ISSUE THREAD

**Issue by Na0mir** [benphelps/homepage#439]
Hello there :)

Is that possible to create an Authelia service the same way you did for Authentik ? 
With informations such as number of users and successfull / failed logins in the last 24h

Thanks ! ❤🤘

**Comment by shamoon** [comment]
Just curious, what would you link to for Authelia?

**Comment by JazzFisch** [comment]
From looking at [Authelia's Open API Spec](https://github.com/authelia/authelia/blob/master/api/openapi.yml) there does not appear to be any of the information available.  If you are able to find any other sources of API information, please update this feature request.

**Comment by Na0mir** [comment]
Hi!

Sorry I didn't paste in the first post.
I found this:
https://github.com/authelia/authelia/pull/3234
https://www.authelia.com/reference/guides/metrics/
Thanks !

**Comment by BancarelValentin** [comment]
> If you are able to find any other sources of API information, please update this feature request.

It looks like @Na0mir found some endpoint. Is it possible to reopen ?

**Comment by shamoon** [comment]
We can't use Prometheus metrics

**Comment by llaumgui** [comment]
> We can't use Prometheus metrics

Why we can't ? For me Authelia propose now a metric endpoint and we can repoen the issue.
