### ISSUE TITLE
Link opened even if empty in configuration

### ISSUE THREAD

**Issue by LovelessCodes** [benphelps/homepage#44]
Hello.

I like the idea of your homepage, but there's one thing that is annoying me as a whole.
I want to check up on some services, like if they're running or not.
Therefore I've put no href on them - they should not be clickable.

Also, as a bonus question:
Is it possible for me to develop my own widgets and put on my own icons for my services?

Cheers!

**Comment by benphelps** [comment]
I just released a new version that disables the link action if the href is blank or `#`.

For icons, you can load relative or remote icons, see here: https://github.com/benphelps/homepage/wiki/Services#icons
