### ISSUE TITLE
[Documentation] Inconsistent Docker Integration examples

### ISSUE THREAD

**Issue by rswafford** [benphelps/homepage#461]
### Description

The docker.yaml and services.yaml examples aren't consistent in how the reference docker servers.  See:
![image](https://user-images.githubusercontent.com/3413092/198385364-ecc424c2-d6ae-48ca-a8f2-3fc6ba34a2ac.png)

versus referencing docker servers my-server and other-server, on the Services configuration page:
![image](https://user-images.githubusercontent.com/3413092/198385460-7d0d8af6-fd21-4091-bc0a-0656483ea9f0.png)

Should the server tag in the services.yaml reference the same name as the "my-docker" name in docker.yaml? Or is there some other configuration option in the docker.yaml that isn't noted we should use?

### Steps to reproduce

View the documentation on gethomepage.dev

### homepage version

v0.4.18

### Installation method

Unraid

**Comment by shamoon** [comment]
Those two screenshots are on different pages, so Im not sure consistency is totally needed but I made the examples on https://gethomepage.dev/en/configs/docker/ consistent.

The server tag in services.yaml uses whatever you set in docker.yaml, "my-server" and "other-server" are just giving examples. Also, I suspect with a bit of quick experimentation this could be figured out if there is confusion.

Thanks

**Comment by rswafford** [comment]
That is sort of what I assumed, however I also observe that the docker status light works regardless of what I put for a server name in my services.yaml (I only have one Docker server, to be fair).  I opened the issue at the request of @JazzFisch on Discord.

**Comment by shamoon** [comment]
Well, that sounds like a different issue than one with documentation =)

That is intentional, I think and is due to it "falling back" to [using the local socket `/var/run/docker.sock`](https://github.com/benphelps/homepage/blob/5d101b0ded8897caf8500e4bd74abc55c4eaff1b/src/utils/config/docker.js#L15)
