### ISSUE TITLE
[Feature Request] Any solution that can replace the cdn.jadelivr.net?

### ISSUE THREAD

**Issue by xinmans** [benphelps/homepage#465]
### Description

Any solution that can replace the cdn.jadelivr.net, I want to use local images.

Next.config.js
const nextConfig = {
  reactStrictMode: true,
  output: "standalone",
  swcMinify: false,
  images: {
    domains: ["cdn.jsdelivr.net"],
    unoptimized: true,
  },
  i18n,
};

**Comment by shamoon** [comment]
You can already use local images, please review https://gethomepage.dev/en/configs/services/
