### ISSUE TITLE
[Bug] Api error when Sonarr library is empty.

### ISSUE THREAD

**Issue by ptbsare** [benphelps/homepage#469]
### Description

Widget shows api error when adding a empty sonarr library.

### Steps to reproduce

1.Run Sonarr in docker, no series added.
2.Add a sonarr widget in services.yaml of homepage.
![IMG_20221031_152019](https://user-images.githubusercontent.com/3147576/198953905-972d25db-9e17-4ed9-8ebb-488b5b7481c7.jpg)

### homepage version

v0.4.18

### Installation method

Docker

**Comment by shamoon** [comment]
I cant reproduce this (screenshot). Please see https://gethomepage.dev/en/more/troubleshooting/

<img width="378" alt="Screen Shot 2022-10-31 at 9 58 24 PM" src="https://user-images.githubusercontent.com/4887959/199163126-58a5a2c4-9c42-4ba7-b519-19f40941bace.png">
