### ISSUE TITLE
docker integration with changing container names

### ISSUE THREAD

**Issue by Bijoejinj** [benphelps/homepage#47]
Hi,

not really an issue but is there a way to specify what container to check for availability if the (ending) of the container name changes?

KR

**Comment by Trever123** [comment]
You can force the name to not change using `—name` parameter when the container is created. Or is this something you can’t control?

**Comment by Bijoejinj** [comment]
unfortunately the -name parameter doesnt work with docker-compose (im using portainers stack service for configuration)

but what appears to be working is using the container_name parameter :)

so everything is working fine
