### ISSUE TITLE
[Feature Request] Komga Widget

### ISSUE THREAD

**Issue by Ravencentric** [benphelps/homepage#474]
### Description

A widget for https://github.com/gotson/komga

**Comment by javijuji** [comment]
Would love to have a komga widget as well.

**Comment by KillahB33** [comment]
@Ravencentric and @javijuji what data would be shown? 
As a Komga user I can't think of any generic info that I can pull, take a look at the swagger page and tell me if you see anything there of value cause I didn't.
<yourkomgaurl>/swagger-ui.html

**Comment by Zlendy** [comment]
@KillahB33 This information may be useful, however, the data returned by these endpoints is way too large.

- users: http://komga.host.or.ip/api/v2/users
- library_count: http://komga.host.or.ip/api/v1/libraries
- series_count: http://komga.host.or.ip/api/v1/series?unpaged=true
- book_count: http://komga.host.or.ip/api/v1/books?unpaged=true

**Comment by KillahB33** [comment]
Thanks!! I'm surprised the metrics stuff isn't available directly through the AI. I'll dig into this a bit and see what I can do.

**Comment by Zlendy** [comment]
AI?

**Comment by KillahB33** [comment]
Was on my phone. API is what I meant

**Comment by Zlendy** [comment]
Oh, okay xD. I'll investigate a bit more and tell you if I find any other promising metrics to pull.

**Comment by KillahB33** [comment]
Haha ok cool! Team work make the dream work!

**Comment by KillahB33** [comment]
Gonna see if they wouldn't mind making it available, I know with some work we can do some counts and do it that way but if they will make it easily available I would rather go that way.

**Comment by KillahB33** [comment]
Alright so I feel like a dummy cause I would usually check network to see where that info is coming from but I guess I forgot. I need some help from the rest of you though. Sidecars is my libraries count + 1, I want to confirm from the rest of you that that is normal. Please confirm cause if it is I can grab that value than minus 1 it for the library count in the widget.

**Comment by Zlendy** [comment]
> Sidecars is my libraries count + 1, I want to confirm from the rest of you that that is normal.

Sidecars do not seem to be related in any way to the libraries themselves. Rather, it seems like it's a separate file that stores metadata from the books.
However, you can get the number of libraries from this endpoint: http://komga.host.or.ip/actuator/metrics/komga.libraries
![image](https://user-images.githubusercontent.com/22578704/215897331-590406e9-7922-4ecf-bc56-7308970db32b.png)

You can get a list of all the available metrics if you go to http://komga.host.or.ip/actuator/metrics

**Comment by KillahB33** [comment]
Yeah after I posted that I found the libraries one, unfortunately users isn't there so just gonna skip that one.
I hit a speed bump though, I have the internal api return the correct numbers but homepage just sits there pulsing the dashes and never populates them. I have tried a few things and not sure how to proceed. Gonna go relax but I pushed to my repo if anyone wants to take a look. https://github.com/KillahB33/homepage
@shamoon let me know if it's easier if I submit a PR and then fix it like last time.

**Comment by shamoon** [comment]
Yes a PR is fine but it would be better to make sure it works first... I will have to spin up an installation but docker containers are usually easy enough.

One thing, you updated the credentialed proxy but the generic one supports basic auth already, do you really need that? See https://github.com/KillahB33/homepage/blob/8920217411b81643ad8e938ea07db6b29da92ae9/src/utils/proxy/handlers/generic.js#L24

**Comment by KillahB33** [comment]
Ok I'll keep poking around myself.

Ah my bad, didn't realize it was there. Updating code for that. Is there a good way to pass User Agent? Adding it to generic seems to break the rest of the widgets using generic.

**Comment by KillahB33** [comment]
Also here is what homepage is showing for the response for libraries.

```json
{
  "name": "komga.series",
  "description": "The number of series",
  "baseUnit": "count",
  "measurements": [
    {
      "statistic": "VALUE",
      "value": 28
    }
  ],
  "availableTags": [
    {
      "tag": "library",
      "values": [
        "Magazines",
        "Comics"
      ]
    }
  ]
}
```

Then I am trying to populate it with the following.

const libraries = libraryData.measurements?.value ?? libraryData.measurements[0]?.value;

<Block label="libraries" value={libraries} />

And it's not populating in the UI. I tried a few things this morning and not sure where to trouble shoot now.
