### ISSUE TITLE
[Feature Request] Add automatic location support for weather wiget

### ISSUE THREAD

**Issue by Aidan-B** [benphelps/homepage#48]
Sometimes I may travel or not be local to my homeserver. I would like the weather widget to function for my current location in these situations.
I imagine this could look something like an "automatic location" config parameter that makes use of `getCurrentPosition()` to ask the user for their location before making a query for the weather.
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition

**Comment by benphelps** [comment]
What a great idea!  I'll see about getting this added.

**Comment by benphelps** [comment]
This has been implemented in the latest commit, with some caveats.

The Geolocation API forcefully requires a secure context (HTTP), so this can only be used if you've got an SSL setup.  It also requires a user interaction event, and cannot be pulled automatically.

This is what the prompt looks like:

<img width="178" alt="Screenshot 2022-09-09 at 12 48 43 PM" src="https://user-images.githubusercontent.com/82196/189322777-8757a7d4-cf79-4623-8daf-15793626b2a3.png">

You can find updated documentation here: https://github.com/benphelps/homepage/wiki/Information-Widgets#weatherapi
