### ISSUE TITLE
Storage info widget shows API Error

### ISSUE THREAD

**Issue by RickyChan21** [benphelps/homepage#489]
### Description

I have an additional drive that I want to add but it just shows API error. I mounted the drive in the compose file but it just doesn't seem to work. Any suggestions?

![Screenshot_1](https://user-images.githubusercontent.com/26828150/200090498-acff8a42-da72-4090-87cb-04ea26459d44.png)

### homepage version

v0.4.18

### Installation method

Docker

### Configuration

```yaml
volumes:
      - /config/homepage:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/disk/by-label/data:/data
```

```
- resources:
    disk: /data
```
```

**Comment by donslice** [comment]
According to the documentation, you need to add the "Mounted On" listing, not the Filesystem. https://gethomepage.dev/en/widgets/resources/

    - resources:
        label: Storage
        disk: /mnt/storage

**Comment by shamoon** [comment]
Thanks was just coming to say that =)

**Comment by RickyChan21** [comment]
This is the drive I want to add. After running the df command: 
![image](https://user-images.githubusercontent.com/26828150/200091085-bfe7120f-cc78-4677-bf15-ed63f3bf7860.png)

still not working with this volume:
```
volumes:
      - /config/homepage:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/mnt/data
```

```
- resources:
    disk: /mnt/data

```

**Comment by shamoon** [comment]
```
volumes:
      - /config/homepage:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/sda:/mnt/data
```

**Comment by RickyChan21** [comment]
It's working now with:

```
volumes:
      - /config/homepage:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/mnt/data
```

I just had to recreate the container to be updated. Thanks!
