### ISSUE TITLE
[Bug] custom search error

### ISSUE THREAD

**Issue by peterthepeter** [benphelps/homepage#506]
### Description

I have set a custom serach provider in widgets.yaml as follows:

- search:
    provider: custom
    url: http://192.168.1.3:8085/search?q=
    target: _blank

unfortunately I get an error "Application error: a client-side exception has occurred (see the browser console for more information)" every time I search for it.

The url works though and gives me my locale SearXNG page.

### Steps to reproduce

_

### homepage version

v0.4.18 (4ea2798, Oct 15, 2022)

### Installation method

Unraid

**Comment by shamoon** [comment]
Please see #423, #446

**Comment by itguy327** [comment]
> Please see #423, #446

Do either of these referenced issues contain a fix or is a fix pending?

Thank you

**Comment by peterthepeter** [comment]
Sorry for my questions, but atm there is no fix and it will get fixed in some of the next releases? Or i reading this wrong?

**Comment by shamoon** [comment]
It will be in the next release, in the meantime you could switch to using the development image `main` which has this already
