### ISSUE TITLE
Bookmarks layout changed in latest nightly [Bug] 

### ISSUE THREAD

**Issue by Magelo** [benphelps/homepage#507]
### Description

This is probably not a bug, maybe it is... But, since icons were introduced (mainly in november nightly) in bookmakrs, I now don't have a 4 columns layout for my 4 bookmark category. Before, my 4 bookmark category were in a 4 columns layout.

Maybe related or not, above bookmarks I have 3 groups with a modified style in settings.yaml :

layout:
  Applications:
    style: row
    columns: 3
  Services:
    style: row
    columns: 3
  Servers:
    style: row
    columns: 3

The "Servers" group style is affecting the bookmark layout?

![image](https://user-images.githubusercontent.com/10362303/200638473-90b37204-2623-480d-9192-ffedd6f5f3bf.png)

### Steps to reproduce

1. At the top of my homepage, 3 groups with no style override in settings.yaml
2. followed by 3 groups with style row/columns:3 defined in settings.yaml
3. finally, my 4 categories bookmarks

### homepage version

nightly (4a9a034, Nov 7, 2022)

### Installation method

Docker

**Comment by shamoon** [comment]
Ah thanks, that was because the bookmarks were using a different means of generating columns. They dont have fine-control (at the moment) over the number of columns like services but it should now more closely mimic services, basically equal columns to max 6, fewer on smaller window/screen sizes. Please let me know if the new build (eta ~10m) works better for you

**Comment by shamoon** [comment]
Yes I understood correctly I think! It wasn't the icon it was trying to fix the gutters (don't have the exact commit on hand). I think it'll be fixed for you now in `main` and `nightly` which I believe point to the same image. Next time you try make sure you pull the latest image, not sure exactly what you mean by "refresh".

**Comment by Magelo** [comment]
By refresh I meant pulling the latest nightly docker image available. Docker container Watchtower did pull the latest at midnight EDT, so the now installed version is nightly (f48ff3c, Nov 8, 2022). Bookmarks section is back to my liking. Thanks.
