### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lsaadeh** [benphelps/homepage#516]
### Description

![image](https://user-images.githubusercontent.com/43462320/200952207-22765d64-6d2d-459b-9612-c7448cadbfe9.png)
Active stream not centring correctly

### Steps to reproduce

set page size to half screen

### homepage version

v0.4.18 (4ea2798, Oct 16, 2022)

### Installation method

Docker

**Comment by shamoon** [comment]
This is actually true for any widget with longer text, on small screens:
<img width="362" alt="Screen Shot 2022-11-09 at 9 06 01 PM" src="https://user-images.githubusercontent.com/4887959/201005714-6eb67eda-6461-41df-aec3-d2748d85770e.png">

Easy enough to fix =)
<img width="359" alt="Screen Shot 2022-11-09 at 9 06 37 PM" src="https://user-images.githubusercontent.com/4887959/201005737-4e38cd86-18e0-4419-b2ec-0d3109d4ba72.png">
