### ISSUE TITLE
[Feature Request] Synology Download Station widget

### ISSUE THREAD

**Issue by szczottie** [benphelps/homepage#523]
### Description

Is there any chance to get widget similar to one for qbittorrent but for Synology Download Station?

**Comment by c4rver** [comment]
I'm interested on it, too. I don't know about next.js, but I have a Synology and can help testing the API calls, or whatever you need.

Here is the official documentation for Download Station API:
https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/DownloadStation/All/enu/Synology_Download_Station_Web_API.pdf
