### ISSUE TITLE
[Feature Request] new widget for audiobookshelf

### ISSUE THREAD

**Issue by eskiiom** [benphelps/homepage#525]
### Description

a new widget for audiobookshelf would be cool :)
it could display number of listeners, and number of podcasts and audiobooks

Thanks

https://api.audiobookshelf.org/

**Comment by ozdeadmeat** [comment]
+1!

**Comment by MasterSmurf** [comment]
+1! There are some neat library stats to grab.

**Comment by madkatz01** [comment]
+1!

**Comment by spandan13** [comment]
+1!

**Comment by augerl** [comment]
+1

**Comment by shamoon** [comment]
Please just up-vote the feature request instead of the +1 comments unless you have something specific to add to the convo. Thanks all
