### ISSUE TITLE
[Feature Request] Support for more speedtest apps since Speedtest-tracker seems abandoned

### ISSUE THREAD

**Issue by loof2736** [benphelps/homepage#531]
### Description

It seems that henrywhitaker3's speedtest-tracker has been abandoned, so it would be great if there was greater support for different speedtest applications, such as [this one](https://github.com/alexjustesen/speedtest-tracker) which seems to just be an active fork of the original speedtest-tracker

**Comment by shamoon** [comment]
Is something about the existing one not working for you? That fork has been “active” for all of 2 months, so we have to be mindful not to keep chasing a project around, but yes I suppose supporting multiple could be possible

**Comment by loof2736** [comment]
> Is something about the existing one not working for you? That fork has been “active” for all of 2 months, so we have to be mindful not to keep chasing a project around, but yes I suppose supporting multiple could be possible

I've been having a bunch of issues with it just not running the automated speedtests. When it works its fine, but it seems I have to keep randomly restarting the container to keep it working. My internet has been cutting in and out so it might have something to do with that, maybe if it cuts out mid speedtest the whole app just kinda stops? I'm not sure

I know that supporting a bunch of different apps is probably a very difficult task though. Would it be possible to set up a simple cron task to run the a speedtest through the ookla speedtest and somehow pipe the results into homepage? I personally don't need a whole UI just for speedtests, seeing the results on my dashboard is more than enough

**Comment by CorneliousJD** [comment]
The new version seems very nice - adding my 2 cents in here that support for it would be great.
not sure if the API is the same to retrieve the values or not, but as of now authentication is required and the current speedtest widget doesn't support authentication so that's probably part of the showstopper for this.

**Comment by sarcasticsapien** [comment]
Cron jobs quit working for me on henrywhitaker3/Speedtest-Tracker for me. It also has over 140 issues with no updates in 15+ months.

I do understand your point of not chasing a project around, especially considering alexjustesen/speedtest-tracker has only been around for 3 months. But on the flip side, at some point a project must be considered abandoned and move on.

**Comment by shamoon** [comment]
https://github.com/alexjustesen/speedtest-tracker doesnt currently have any api endpoint...

**Comment by shamoon** [comment]
Happy to report that thanks to some folks over there, the next version of alexjustseen's version of speedtest-tracker will be a drop-in replacement, meaning this widget will support both versions "as-is".

See https://github.com/alexjustesen/speedtest-tracker/pull/81 --> https://github.com/alexjustesen/speedtest-tracker/pull/463

**Comment by alexjustesen** [comment]
> Happy to report that thanks to some folks over there, the next version of alexjustseen's version of speedtest-tracker will be a drop-in replacement, meaning this widget will support both versions "as-is".
> 
> See [alexjustesen/speedtest-tracker#81](https://github.com/alexjustesen/speedtest-tracker/issues/81) --> [alexjustesen/speedtest-tracker#463](https://github.com/alexjustesen/speedtest-tracker/pull/463)

Ya beat me to it! `v0.11.8` is building now and will be available shortly!

https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.11.8
