### ISSUE TITLE
Client should not crash if the API key for services is not valid

### ISSUE THREAD

**Issue by jackblk** [benphelps/homepage#55]
Reproduce: just use any invalid key in Radarr (or any other services), then refresh the homepage

Expected: unable to see info of the service, only an indicator/logo telling that the config for the service is invalid

Observed: cannot view the page, the client crashes.

`Application error: a client-side exception has occurred (see the browser console for more information).`

**Comment by benphelps** [comment]
I believe 08afa0b should fix this, let me know.

**Comment by jackblk** [comment]
@benphelps great work 😄 , just tested and it is fixed.
