### ISSUE TITLE
After latest update the Services part stopped showing [Bug] 

### ISSUE THREAD

**Issue by jmlc11** [benphelps/homepage#560]
### Description

After the latest update, the Services part was replaced with this:
![image](https://user-images.githubusercontent.com/6006781/204141080-2c77290b-5196-4475-94d2-bbc9ea9f9931.png)
But the bookmarks part is fine.
My Services.yaml file is fine and still has all my things, they just do not show in the homepage.

### Steps to reproduce

Just update to the latest docker tag.

### homepage version

v0.5.1

### Installation method

Docker

**Comment by shamoon** [comment]
Do you have a `layout` section in your settings?

**Comment by jmlc11** [comment]
No i dont. Is it required now?

**Comment by shamoon** [comment]
No its not, and if you dont things should work the same. Can you post your configs? I cant reproduce this issue.

**Comment by shamoon** [comment]
Also, did you check the browser or container logs?

**Comment by jmlc11** [comment]
Ok, adding the layout tag in the settings.yaml worked, but now all of my widgets are having an API error:
![image](https://user-images.githubusercontent.com/6006781/204142001-7ae4ebc6-8a68-4e96-b6ea-ba14c60480ab.png)

**Comment by jmlc11** [comment]
Let me check all my configs and the browser console.

**Comment by shamoon** [comment]
Again, you shouldn't need the layout block.

**Comment by jmlc11** [comment]
Does not work without it.

They all have this error now:
![image](https://user-images.githubusercontent.com/6006781/204142608-f0d6bd21-1e4c-4a3b-a2f2-7cda97bb3c25.png)
And this is the docker logs:
![image](https://user-images.githubusercontent.com/6006781/204142647-dc578e95-4457-4aa5-94d8-cd8681779801.png)
My configs:
[services.txt](https://github.com/benphelps/homepage/files/10098598/services.txt)
[settings.txt](https://github.com/benphelps/homepage/files/10098602/settings.txt)

If i remove the layout tag it stops working.

**Comment by jmlc11** [comment]
After restarting the container, it now works fine.

Sorry for wasting your time.

**Comment by jmlc11** [comment]
Working as Designed.
