### ISSUE TITLE
[Bug] qBittorrent showing wrong bandwidth metric (Mbps instead of MB/s)

### ISSUE THREAD

**Issue by snnacks** [benphelps/homepage#562]
### Description

Currently homepage is showing "MB/s" as "Mbps" when using the qBittorrent widget. There is a significant difference between a megabit and a megabyte and it would be nice to see the true metric here. See images below:

Homepage Widget:
![image](https://user-images.githubusercontent.com/58410628/204159410-cdef2ed4-caec-4236-8e32-632dc40e2009.png)

qBittorrent stats:
![image](https://user-images.githubusercontent.com/58410628/204159502-41903a28-9baf-42d2-8ba0-c0da4bfb3b04.png)

### Steps to reproduce

1. Use the qBittorrent widget
2. Reach at least 1 MB/s in download or upload
3. Check homepage and look at the widget (it will show the measurement in Mbps)

### homepage version

v0.5.1

### Installation method

Unraid

**Comment by snnacks** [comment]
I would also like to add it would be fine for the homepage widget to show the usage in megabits per second, but only if it is accurate.

**Comment by shamoon** [comment]
Theyre actually mebibits, e.g. MiBps. Seems youre the first to notice that =)
<img width="523" alt="Screen Shot 2022-11-27 at 2 21 11 PM" src="https://user-images.githubusercontent.com/4887959/204163041-b3cb5409-5a72-4d56-9f25-784764c6f120.png">
