### ISSUE TITLE
[Bug] Homepage container logs no longer writing to stdout

### ISSUE THREAD

**Issue by kBraDrs** [benphelps/homepage#566]
### Description

Hello,

I have noticed an issue that may be relating to 0.5.1 or 0.5.2. My WatchTower container does not update on a daily schedule and due to 0.5.1 and 0.5.2 being released at such similar times, I am unsure which of these caused the issue.
I use Dozzle to monitor my containers logs when I need to, and the Homepage logs are no longer showing on there, where before they were working correctly.
On a previous occasion, I have asked the Dozzle developer where the container reads logs from and can confirm that this is stdout. Can you perform some checks on this and return this to a working state if possible please.

Thank you

### Steps to reproduce

1. Ensure homepage is installed
2. Install Dozzle via Docker
3. View homepage logs

### homepage version

v0.5.2

### Installation method

Docker

**Comment by shamoon** [comment]
Im not sure I understand, so you do have the problem with 0.5.2 or no?

The only relevant change in 0.5.2 vs 0.5.1 was that an unrelated bug was causing an issue for users with completely empty `settings.yaml` files, in which case the logging function (among other things) [would have been broken](https://github.com/benphelps/homepage/blob/f16bd919788ac6d1fcd094da8eff8531437ccf98/src/utils/logger.js#L15). But 0.5.2 should fix that, and again would have been only if your settings was empty

In general, from 0.4.18 to 0.5.2 I dont think any changes were made to the logging except that you can now optionally specify a different log path #535 see https://github.com/benphelps/homepage/compare/v0.4.18...v0.5.2

**Comment by shamoon** [comment]
👻
