### ISSUE TITLE
[Bug] v0.5.2 Sonarr API Error

### ISSUE THREAD

**Issue by ptbsare** [benphelps/homepage#569]
### Description

mentioned here https://github.com/Sonarr/Sonarr/issues/4950

application is making a bad API call.

[markus101](https://github.com/markus101) commented [on Mar 22](https://github.com/Sonarr/Sonarr/issues/4950#issuecomment-1074296369)
The request is missing the sortKey

### Steps to reproduce

v0.5.2 homepage in docker
1.add a sonarr widget. Sonarr version 3.0.6
2.
```logs
API Error Information
API Error: Invalid data
URL: http://192.168.195.122:8989/api/v3/wanted/missing?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Response Data:
{
  "message": "Object reference not set to an instance of an object",
  "description": "System.NullReferenceException: Object reference not set to an instance of an object\n  at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.CreateExpression[TModel] (System.String propertyName) [0x00019] in M:\\BuildAgent\\work\\63739567f01dbcc2\\src\\NzbDrone.Core\\Datastore\\Extensions\\PagingSpecExtensions.cs:32 \n  at NzbDrone.Core.Datastore.Extensions.PagingSpecExtensions.OrderByClause[TModel] (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x00000] in M:\\BuildAgent\\work\\63739567f01dbcc2\\src\\NzbDrone.Core\\Datastore\\Extensions\\PagingSpecExtensions.cs:11 \n  at NzbDrone.Core.Tv.EpisodeRepository.GetMissingEpisodesQuery (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.DateTime currentTime, System.Int32 startingSeasonNumber) [0x0000d] in M:\\BuildAgent\\work\\63739567f01dbcc2\\src\\NzbDrone.Core\\Tv\\EpisodeRepository.cs:216 \n  at NzbDrone.Core.Tv.EpisodeRepository.EpisodesWithoutFiles (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Boolean includeSpecials) [0x0000d] in M:\\BuildAgent\\work\\63739567f01dbcc2\\src\\NzbDrone.Core\\Tv\\EpisodeRepository.cs:111 \n  at NzbDrone.Core.Tv.EpisodeService.EpisodesWithoutFiles (NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec) [0x00000] in M:\\BuildAgent\\work\\63739567f01dbcc2\\src\\NzbDrone.Core\\Tv\\EpisodeService.cs:152 \n  at Sonarr.Http.SonarrRestModule`1[TResource].ApplyToPage[TModel] (System.Func`2[T,TResult] function, NzbDrone.Core.Datastore.PagingSpec`1[TModel] pagingSpec, System.Converter`2[TInput,TOutput] mapper) [0x00000] in M:\\BuildAgent\\work\\63739567f01dbcc2\\src\\Sonarr.Http\\SonarrRestModule.cs:43 \n  at Sonarr.Api.V3.Wanted.MissingModule.GetMissingEpisodes (Sonarr.Http.PagingResource`1[TResource] pagingResource) [0x00210] in M:\\BuildAgent\\work\\63739567f01dbcc2\\src\\Sonarr.Api.V3\\Wanted\\MissingModule.cs:47 \n  at Sonarr.Http.REST.RestModule`1[TResource].<set_GetResourcePaged>b__36_0 (System.Object options) [0x00000] in M:\\BuildAgent\\work\\63739567f01dbcc2\\src\\Sonarr.Http\\REST\\RestModule.cs:139 \n  at Nancy.NancyModule+<>c__DisplayClass14_0`1[T].<Get>b__0 (System.Object args) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 \n  at Nancy.NancyModule+<>c__DisplayClass16_0`1[T].<Get>b__0 (System.Object args, System.Threading.CancellationToken ct) [0x00047] in <e31b230dbd29407fadcc55713e0bbd0f>:0 \n  at Nancy.Routing.Route`1[T].Invoke (Nancy.DynamicDictionary parameters, System.Threading.CancellationToken cancellationToken) [0x00017] in <e31b230dbd29407fadcc55713e0bbd0f>:0 \n  at Nancy.Routing.DefaultRouteInvoker.Invoke (Nancy.Routing.Route route, System.Threading.CancellationToken cancellationToken, Nancy.DynamicDictionary parameters, Nancy.NancyContext context) [0x00086] in <e31b230dbd29407fadcc55713e0bbd0f>:0 \n  at Nancy.Routing.DefaultRequestDispatcher.Dispatch (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken) [0x002b7] in <e31b230dbd29407fadcc55713e0bbd0f>:0 \n  at Nancy.NancyEngine.InvokeRequestLifeCycle (Nancy.NancyContext context, System.Threading.CancellationToken cancellationToken, Nancy.Bootstrapper.IPipelines pipelines) [0x0011d] in <e31b230dbd29407fadcc55713e0bbd0f>:0 "
}
```

### homepage version

v0.5.2

### Installation method

Docker

**Comment by GertJanH** [comment]
I had the same problem, after updating sonarr to the latest version this problem was solved

the currunt version of sonarr is 3.0.9.1549

**Comment by ptbsare** [comment]
Hi  thanks for the advice. I think many people, like us, are stilling using  the old version of sonarr because not everyone updates the sonarr docker frequently. Maybe homepage can add the sortkey in the api call to avoid this issue rather than demand people  upgrade to the latest version of sonarr.

**Comment by shamoon** [comment]
Ha, a bit hyperbolic. I’m not sure anyone is “demanding” anything here what with this being free open source software, using an entirely optional widget and all…

so you’re saying older versions of the sonarr API break without including an optional parameter and newer versions fixed that? I understand the “fix” might be simple here but also seems like updating sonarr is simple… and essentially we’re implementing a workaround to a bug that was already fixed? It’s kinda like, where do we draw the line, how many versions do we have to support? When we test the sonarr widget do we need to test multiple versions?

not trying to be obtuse, I realize this might be a fairly isolated thing but this seems like a solution to a problem that already has a solution, no?

**Comment by JazzFisch** [comment]
According the the [Sonarr Open API spec for wanted/missing](https://sonarr.tv/docs/api/#/Missing/get_api_v3_wanted_missing), it doesn't even support a sortkey parameter.  Heck, the only way I found out about that parameter is by going in and reading their source code [here](https://github.com/Sonarr/Sonarr/blob/08b677ca7d2ee3cb41384747a4df4187def4b644/src/Sonarr.Http/Extensions/RequestExtensions.cs).  While this is something homepage could do, not following API specs is a recipe for unexpected behavior down the road.

Like @shamoon, I'm not trying to be glib.  I think there is an opportunity to improve homepage's documentation and version window policy.

**Comment by shamoon** [comment]
I think updating sonarr is honestly the better solution here. If many people find this to be a burden we can always re-address this in the future, appreciate you raising the issue.
