### ISSUE TITLE
[Bug] Z-index on Tautilli widget with search bar

### ISSUE THREAD

**Issue by bgiovand** [benphelps/homepage#582]
### Description

The Tautilli play items have a higher z-index than the search bar.

Same result in Safari and Chrome

<img width="772" alt="Screenshot 2022-11-29 at 11 07 34 AM" src="https://user-images.githubusercontent.com/179564/204624072-6b0b86d5-6f6b-474e-9ffd-679cda76b8ce.png">

### Steps to reproduce

1. Place Tautilli widget in centre of screen
2. Invoke search by starting to type on the keyboard

### homepage version

v0.5.2 (04fbf31, Nov 27, 2022)

### Installation method

Unraid

**Comment by shamoon** [comment]
Thanks for reporting, easy fix =)
