### ISSUE TITLE
[Bug] 24h format wrong

### ISSUE THREAD

**Issue by JigSawFr** [benphelps/homepage#585]
### Description

If we enable 24hour format for datetime, you will face 24:58 which is wrong, correct time is 00:58 ;)

![image](https://user-images.githubusercontent.com/5781907/204674782-eb100a66-bc06-4109-8a16-c1c8ae45f88e.png)

### Steps to reproduce

Enable 24hour format for time.

### homepage version

0.5.2

### Installation method

Docker

**Comment by shamoon** [comment]
Well thats certainly odd and I cant reproduce it (screenshots attached). At its core this just uses [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) which comes from Javascript. I did find some bugs online. Can you post your settings / widgets configs please.

**Comment by JigSawFr** [comment]
here is my current widget config for time:

```
- datetime:
    text_size: xl
    format:
      timeStyle: short
      hour12: false
```

Pretty simple

**Comment by shamoon** [comment]
And your settings? What is your locale?

Try `hourCycle: h23` instead of `hour12: false`
