### ISSUE TITLE
[Feature Request] Logins

### ISSUE THREAD

**Issue by modem7** [benphelps/homepage#59]
Heya, 

Would it be possible to at some point add a login method (preferably something like oauth for things like Google login), so that we can show/hide certain things on the dashboard without putting the dashboard fully behind a login?

E.g.:

Without login/public: 
Shows Group A, C, D.
Shows bookmarks Social, Development

With Login:
Shows Group A, B, C, D.
Shows bookmarks Social, Development, Entertainment

In config file, proposed suggestion is a new boolean such as "private:true" or similar for each section.

**Comment by benphelps** [comment]
I'm not too sure about this one.  I know that it may be useful for some people, but not the majority.  Keeping the scope small and focused is important in keeping the service fast and lightweight.  Adding a full auth layer, which often comes with the addition of users, rolls, etc... it's a deep rabbit hole to go down, and will never satisfy everyone.

I also believe this could be handled for the most part, by other existing services, like [Authelia](https://www.authelia.com/).

**Comment by georgzoeller** [comment]
Could be as simple as gating visibility of groups or items by a proxy header. Then auth can be punted to the proxy.

**Comment by zell-mbc** [comment]
My use case is such that I need users to authenticate before getting to the dashboard. No need for groups and granularity but rather a binary approach, no authentication = no dashboard.
I got this working with Dashy, but Homepage looks a lot slicker to me.

**Comment by shamoon** [comment]
There are many other solutions to this, e.g. as mentioned https://www.authelia.com/ I agree it can be left outside the scope of this project, especially since by default its not particularly private data.

**Comment by Visne** [comment]
I consider what services I run and their statistics to be quite "private", and wouldn't use Homepage without being able to hide it somehow. Luckily reverse proxies make it quite simple to add HTTP basic auth in between, but it's not particularly nice and it also doesn't stop anyone from accessing Homepage if they can somehow access it without the reverse proxy (although this shouldn't be possible with a good setup).
