### ISSUE TITLE
[Feature Request] Add type select for Scrutiny Widget

### ISSUE THREAD

**Issue by Xm798** [benphelps/homepage#596]
### Description

On the scrutiny's settings panel, we can change the device status between Smart, Scrutiny and Both. I changed it to "Smart" because I only want to get the information of smartctl and ignore failures scrutiny detected. But the widget doesn’t seem to be able to configure the device status type, which always shows that there are several FAILED disks.

So we want a switch to select the type of status report to be consistent with the display on scrutiny's panel.

Thanks so much !

### Other

Ref https://github.com/AnalogJ/scrutiny/issues/275 and https://github.com/AnalogJ/scrutiny/blob/d8d56f77f9e868127c4849dac74d65512db658e8/webapp/frontend/src/app/shared/device-status.pipe.ts#L12-L17.

**Comment by Tarow** [comment]
I addressed this issue in my [latest PR](https://github.com/benphelps/homepage/pull/620).

**Comment by Xm798** [comment]
> I addressed this issue in my [latest PR](https://github.com/benphelps/homepage/pull/620).

That's great, thanks a million!
