### ISSUE TITLE
[Feature Request] Hostname as Information Widgets

### ISSUE THREAD

**Issue by corasaniti** [benphelps/homepage#599]
### Description

It would be nice to be able to see the hostname as a Information Widgets
Thanks

**Comment by shamoon** [comment]
Cant you just label your `resources` widget?

**Comment by corasaniti** [comment]
Yes, you're right, that's what I did!!! 
Here is my widget.yml

- resources:
    label: raspi4-office
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

Is there a way to align the label under the CPU symbol?

![Cattura](https://user-images.githubusercontent.com/5001932/205130012-eb354046-4c4d-43bd-9029-98ed363acbeb.PNG)
