### ISSUE TITLE
[Bug] Speedtest Tracker shows incorrect unit abbreviations

### ISSUE THREAD

**Issue by eboddington** [benphelps/homepage#619]
### Description

The Speedtest Tracker widget shows `MiB` (mebibytes) when it surely means `Mb` (megabits), which is completely off. If I open Speedtest Tracker it shows `Mbit/s` which is correct.

<img width="412" alt="Screenshot 2022-12-04 at 17 13 02" src="https://user-images.githubusercontent.com/3886999/205505228-33ef0794-80db-461d-82a8-4aaebbb34fef.png">

### Steps to reproduce

1. Add a resource and widget connected to Speedtest Tracker
2. Wait for a result which is in the region of Mb/s (kb/s and Gb/s might show differently, I don't know)

### homepage version

v0.5.3 (df5ff48, Nov 30, 2022)

### Installation method

Docker

**Comment by shamoon** [comment]
Honestly, whomever is in charge of all the abbreviations for these units should be fired, its darn confusing.

I think theres two things here:

- Homepage should say `MiB/s`
- This widget is converting wrong, its using 1024 when it should be using 1000 before display, e.g.

i.e.
<img width="562" alt="Screen Shot 2022-12-04 at 4 05 01 PM" src="https://user-images.githubusercontent.com/4887959/205524139-6a939cc7-d631-4f5e-b504-c0a5fda2eb5a.png">
= 
<img width="505" alt="Screen Shot 2022-12-04 at 4 05 32 PM" src="https://user-images.githubusercontent.com/4887959/205524242-b0f249b4-3382-4cc7-87c8-0658e7b8f376.png">

I mean, [RIGHT?!](https://www.google.com/search?q=243.9Mbit%2Fs+to+MiB%2Fs)

Related to #562

**Comment by eboddington** [comment]
Haha, I mean, part of the issue is probably that nobody is in charge, so there's multiple systems used confusingly.

Agree that there's a few things going on here but not sure I agree with your conclusions:
- The data is in bits (`b`) yet the Homepage widget shows the unit as bytes (`B`).  The _values_ it's showing are in bits, but the unit is written wrong.
- Yes, it should be using base 10 (e.g. 1000) IMO because that matches the values shown in Speedtest.net and Speedtest Tracker. The `Mi` prefix is short for mebi, which specifically means base 2 (`2^20` or `1024 * 1024`), but I see no reason why it should display mebibits when everyone else is using megabits?
- Looking at the code:
https://github.com/benphelps/homepage/blob/f89093a0672f989b8428f7ded34df4dd5129c29f/src/widgets/speedtest/component.jsx#L32
we can see that the conversion it's doing is actually correct if it wanted to show mebibits (backed up by your Google link), but as I said above, I think that's unusual anyway and it also doesn't match the unit it's showing.
- So, IMO, it should display in megabits and therefore, the conversion should be something like `* 1000 * 1000` or perhaps `* 10^6` and the unit should be written as one of `Mb/s`, `Mbit/s`, or `Mbps`.

**Comment by Nonoss117** [comment]
Hi,
In my case, values and units of the widget are the same than the docker's value of speedtest tracker. I'm satisfied with that.😀

**Comment by eboddington** [comment]
> Hi,
> In my case, values and units of the widget are the same than the docker's value of speedtest tracker. I'm satisfied with that.😀

What do you mean by "the docker's value of speedtest tracker"?

Converting them could be one thing, but is a bit odd/unexpected IMO. But they're also just wrong, it says MiB but doesn't show MiB. The usage of K, M, G prefixes etc. is up for debate, but the difference between bits and bytes is clear 😄

**Comment by eboddington** [comment]
> So you disagree with the choice but the above was correct? I mean, it was converting the value to mebibits you would just prefer it didnt?
> 
> At the moment the issue is theres only one option for unit display of rates, youre right perhaps it should just do both and the widget can choose whichever one to match the source.

Yeah, the number it's displaying seems to be converted to mebibits. But yes, I disagree with that choice because everywhere else that I can think of uses megabits for display (e.g. your ISP when it advertises packages, speedtest.net, and the Speedtest Tracker app that this widget connects to)

And then, the second issue is that the unit it shows after the value is mebi _bytes_ instead of bits. Obviously, I know what it's meant be, but it's a bit like reading 12lbs when you know it means 12oz, it's still unarguably wrong 😅 

What do you mean about matching the source? From the snippet I linked to above, it looks to me like it's always getting the data in bits. But then if you were to click on the Homepage widget and open Speedtest Tracker, as far as I can tell that always displays in Mbit/s, so at the moment it seems odd to have the Homepage widget showing one thing and then click through to the app which will display a different number.

**Comment by shamoon** [comment]
Holy cow, my head hurts but I think I've got it...

<img width="854" alt="Screen Shot 2022-12-08 at 3 52 02 PM" src="https://user-images.githubusercontent.com/4887959/206591284-8b6171e2-c8a0-484d-8fc9-aaa658646a21.png">

<img width="613" alt="Screen Shot 2022-12-08 at 3 51 13 PM" src="https://user-images.githubusercontent.com/4887959/206591275-ad585b5c-b279-44bd-8cf3-6e2f5c4fa330.png">
(4.4 vs 4.9 is just delay in updating)

**Comment by eboddington** [comment]
Looks good, thanks!

**Comment by Cinj216** [comment]
Just a bit of a comment here and at the risk of sounding like an a-hole, but why did you insist on going in and changing something that wasn't broken to begin with and inevitably break it when it's clearly a confusing subject for you? This whole thing was just a pointless exercise with absolutely no end benefit because now we're back where we started after annoying people over the course of several updates. It's one thing to try to push this mebi crap on people (as annoying and pretentious as it usually comes off being), but at least make sure you're doing it right.

**Comment by dangerman200k** [comment]
> why did you insist on going in and changing something that wasn't broken to begin with

But it _was_ broken. The units didn't match the numbers shown.

> It's one thing to try to push this mebi crap on people (as annoying and pretentious as it usually comes off being), but at least make sure you're doing it right.

Two comments on this:
1. I'm not really sure what you mean because the mebi-prefixed units were the ones before this change, and this change moves away from mebi to using megabits per second, which is in line with everything else.
2. Maybe I'm missing some context but you've mentioned that things have been broken and here imply that they're not being done right, can you explain what you mean?

> The only difference is now instead of Mbps we have the lengthier Mbits/s 

This is wrong on two levels:
1. It didn't say Mbps before, it said MiBps
3. The change in unit label isn't the only difference, the conversion has also been changed. So the numbers will be different too (but actually match the unit labels)

That said, I stated in a previous comment that Mbps or Mbit/s would both be correct, but I wasn't really trying to pass judgement on which would be the better choice for the labels here. Perhaps Mbps would be preferable, but that's not what was shown before.

**Comment by eboddington** [comment]
> why did you insist on going in and changing something that wasn't broken to begin with

But it _was_ broken. The units didn't match the numbers shown.

> It's one thing to try to push this mebi crap on people (as annoying and pretentious as it usually comes off being), but at least make sure you're doing it right.

Two comments on this:
1. I'm not really sure what you mean because the mebi-prefixed units were the ones before this change, and this change moves away from mebi to using megabits per second, which is in line with everything else.
2. Maybe I'm missing some context but you've mentioned that things have been broken and here imply that they're not being done right, can you explain what you mean?

> The only difference is now instead of Mbps we have the lengthier Mbits/s 

This is wrong on two levels:
1. It didn't say Mbps before, it said MiBps
3. The change in unit label isn't the only difference, the conversion has also been changed. So the numbers will be different too (but actually match the unit labels)

That said, I stated in a previous comment that Mbps or Mbit/s would both be correct, but I wasn't really trying to pass judgement on which would be the better choice for the labels here. Perhaps Mbps would be preferable, but that's not what was shown before.

**Comment by shamoon** [comment]
> Just a bit of a comment here and at the risk of sounding like an a-hole, 

You correctly predicted how it would sound! Your tone isn’t appreciated, this is a volunteer free project. If you have a problem with it please go elsewhere
