### ISSUE TITLE
[Bug] possible issue with watchtower metrics endpoint

### ISSUE THREAD

**Issue by MrOnak** [benphelps/homepage#624]
### Description

I had opened a ticket with the watchtower team but it seems something is wrong in homepage or at least my configuration of it. For clarity I'm linking the watchtower issue here: https://github.com/containrrr/watchtower/issues/1488#event-7953006074

When I fetch the watchtower metrics manually through `curl -H "Authorization: Bearer MYTOKEN" http://containerhost:8080/v1/metrics > watchtower_metrics.txt` I do get what looks like a correctly formatted Prometheus text exposition format:

```
[...]
promhttp_metric_handler_requests_total{code="503"} 0
# HELP watchtower_containers_failed Number of containers where update failed during the last scan
# TYPE watchtower_containers_failed gauge
watchtower_containers_failed 0
# HELP watchtower_containers_scanned Number of containers scanned for changes by watchtower during the last scan
# TYPE watchtower_containers_scanned gauge
watchtower_containers_scanned 0
# HELP watchtower_containers_updated Number of containers updated by watchtower during the last scan
# TYPE watchtower_containers_updated gauge
watchtower_containers_updated 0
# HELP watchtower_scans_skipped Number of skipped scans since watchtower started
# TYPE watchtower_scans_skipped counter
watchtower_scans_skipped 0
# HELP watchtower_scans_total Number of scans since the watchtower started
# TYPE watchtower_scans_total counter
watchtower_scans_total 0
```

But within the widget I do get a JSON error: "API Error: JSON.parse: unexpeted character at line 1 column 1 of the JSON data" (See screenshot in the watchtower issue report)

### Steps to reproduce

1. set up watchtower with API metrics enabled
2. set up homepage docker container and configure watchtower widget

### homepage version

v0.5.3 (df5ff48)

### Installation method

Docker

### Configuration

```yaml
- testwatchtower:
        name: test tower
        description: api tests
        container: watchtower
        widget:
          type: watchtower
          url: WATCHTOWER_IP:8080
          key: MYTOKEN
```

### Other

environment is:
ARM64, Debian 11, Docker Version 20.10.21

**Comment by shamoon** [comment]
Sorry, I cant reproduce this. My guess is a networking issue. Did you the troubleshooting guide from inside the container? https://gethomepage.dev/en/more/troubleshooting/

<img width="376" alt="Screen Shot 2022-12-05 at 10 07 12 AM" src="https://user-images.githubusercontent.com/4887959/205710394-5e1665e7-3920-4e27-9ed8-a268da21740b.png">
