### ISSUE TITLE
Locatization, we need translations of this proyect. Spanish, German, French....

### ISSUE THREAD

**Issue by AmadeusGraves** [benphelps/homepage#63]
I have seen the project and it attracts me a lot, the only problem is that it is not internationalized, that is to say, translated into other languages. I have been looking at the code and I have seen that internationalization is not implemented. I think this is one of the most urgent functionality because it is discarding the public who speak languages other than English.

**Comment by AmadeusGraves** [comment]
I apologize if I have misspelled or misunderstood, English is not my first language, I also put this task so that when the internationalization is done, help with the translation of this application.

**Comment by AmadeusGraves** [comment]
when the internationalization is ready I will help with the translation into Spanish.

**Comment by benphelps** [comment]
@AmadeusGraves This has been implemented, I've added machine translated versions for a few languages, so you can start there with `es`.

**Comment by AmadeusGraves** [comment]
Thanks! I'll start translating to spanish

**Comment by benphelps** [comment]
Thank you for the Spanish translation :)
