### ISSUE TITLE
[Feature Request] Mylar3 Comics Widget support

### ISSUE THREAD

**Issue by ConnorEMacLean** [benphelps/homepage#630]
### Description

Similar to the other "arr" applications would be awesome to have a [widget](https://gethomepage.dev/en/services/sonarr/) for keeping track of [Mylar3](https://github.com/mylar3/mylar3) status via [API](https://github.com/mylar3/mylar3/wiki/API-Documentation). 

Thanks!

**Comment by KillahB33** [comment]
Cheers on providing a link to the API docs but unfortunately most of the links are broken. 
If it's possible to get the same stats we get from sonarr I agree that would be great but I'll need docs to figure out how to get those stats.
