### ISSUE TITLE
[Bug] qBittorrent and Flood widgets do not fetch data from specified port

### ISSUE THREAD

**Issue by future10se** [benphelps/homepage#635]
### Description

Hello,

When the qBittorrent and Flood widgets are configured to use a URL with a port specified, it seems they do not respect the port and try to connect as usual on port 80.

In the case of qBittorrent specifically, this seems to be a regression, as this was working with `v0.4.18` and stopped working in `v0.5.1`. (Possibly in `v0.5.0`, but I did not specifically run that version.)

In the logs, I see entries like:

```
[2022-12-06T23:13:38.737Z] error: <qbittorrentProxyHandler> HTTP 404 getting data from qBittorrent.  Data: Not Found

[2022-12-06T23:14:18.902Z] error: <floodProxyHandler> HTTP 404 getting data from flood.  Data: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET //api/torrents</pre>
</body>
</html>
```

### Steps to reproduce

1. Configure a service as usual.
2. Specify a widget with a URL containing a port.
3. Widget fails to load data, showing "API Error Information"

### homepage version

v0.5.4 (f89093a)

### Installation method

Unraid

### Container Logs

```
[2022-12-06T23:13:38.737Z] error: <qbittorrentProxyHandler> HTTP 404 getting data from qBittorrent.  Data: Not Found

[2022-12-06T23:14:18.902Z] error: <floodProxyHandler> HTTP 404 getting data from flood.  Data: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET //api/torrents</pre>
</body>
</html>
```

**Comment by shamoon** [comment]
`homepage.widget.url=http://localhost:3001`

<img width="531" alt="Screen Shot 2022-12-06 at 3 35 13 PM" src="https://user-images.githubusercontent.com/4887959/206048416-98a3119a-34cb-4ba7-a499-83d863451210.png">

**Comment by future10se** [comment]
Hello,

I figured out the problem: when there is a trailing `/` in the `url` value, then the fetch fails. 

For example:

```    
- qBittorrent:
  icon: qbittorrent.png
  href: http://some.host:8080/
  container: qbittorrent
  widget:
    type: qbittorrent
    url: http://some.host:8080/
```

Removing the trailing `/` solves the issue.

I didn't think this was an issue because this used to work in `v0.4.18`. In addition, some widgets (such as `adguard`) still work fine with the trailing `/`.

It might be worth doing some input sanitation/normalization, or at least noting this in the docs.

**Comment by shamoon** [comment]
Yea agree. Glad it’s sorted
