### ISSUE TITLE
[Bug] Version und update information is not displayed 

### ISSUE THREAD

**Issue by bentschrader** [benphelps/homepage#637]
### Description

Even published in the changelog with version v.0.3.70: "Added version information and an update check to the bottom of the page" this version information nor the update information is displayed at the bottom of the page?
Is it a configuration option somewhere in the config files? If so, it is missing in the documentation.

### Steps to reproduce

Refresh the page - no version information at the bottom of the page.

### homepage version

v0.5.4

### Installation method

Source

**Comment by shamoon** [comment]
You didnt complete the issue form but no configuration is needed and Im not aware of any problems with this at the moment:
<img width="226" alt="Screen Shot 2022-12-07 at 9 41 45 AM" src="https://user-images.githubusercontent.com/4887959/206253958-a47d888c-a0d8-4ce2-b3e5-38ef735279cb.png">
<img width="224" alt="Screen Shot 2022-12-07 at 9 40 18 AM" src="https://user-images.githubusercontent.com/4887959/206253972-3758b76d-1622-4781-8955-b849a5a6249b.png">

**Comment by shamoon** [comment]
You would need to specify build arguments, see https://github.com/benphelps/homepage/discussions/578#discussioncomment-4266804

**Comment by bentschrader** [comment]
I do not use docker - so I'd use the commands:
git clone https://github.com/benphelps/homepage.git
pnpm install
pnpm build
What is wrong here?

**Comment by shamoon** [comment]
You would still need to pass those in

`NEXT_PUBLIC_BUILDTIME=$BUILDTIME NEXT_PUBLIC_VERSION=$VERSION NEXT_PUBLIC_REVISION=$REVISION pnpm run build`
