### ISSUE TITLE
[Feature Request] Ability to configure favicon, site title, background image

### ISSUE THREAD

**Issue by jackblk** [benphelps/homepage#64]
It would be great if we can configure the site title, favicon & background image in `settings.yaml`

**Comment by benphelps** [comment]
Here are two examples of background images,

<img width="1450" alt="3" src="https://user-images.githubusercontent.com/82196/189267267-cfc94a83-8261-4c98-97fe-71fe9c131a98.png">

<img width="1450" alt="2" src="https://user-images.githubusercontent.com/82196/189267274-5babc84b-b5c3-45e6-8e7d-38c5a392d4cf.png">

There is a new "white" theme, that is built to work well with background images, be them light or dark centric.

I've also allowed the page title to be configured as well.

**Comment by benphelps** [comment]
There is also a new "refresh" button in the bottom right, which will allow you to regenerate the static HTML for the page, which is required for changing the background image and title.

**Comment by benphelps** [comment]
Updated documentation here: https://github.com/benphelps/homepage/wiki/Settings

**Comment by jackblk** [comment]
Great work! Unfortunately I cannot test yet, the build seems to be broken right now.

**Comment by benphelps** [comment]
Fixed build will be up soon :)

**Comment by richardphi1618** [comment]
Can confirm this works! Thank you for the continued developement!

**Comment by hunkyn** [comment]
I just tried adding title and background from the documentation.  Homepage is not picking up the changes. I am on the **main** tag. I also restarted homepage docker to see if that helps.
