### ISSUE TITLE
[Bug] Layout settings not getting applied after update

### ISSUE THREAD

**Issue by stefangrosaru** [benphelps/homepage#642]
### Description

After updating the docker image the layout config does not apply anymore.

The workaround is to remove and then re-add the config.

### Steps to reproduce

1. Set some custom layout
2. Update the docker image to a new version

### homepage version

v0.5.4 (f89093a, Dec 5, 2022)

### Installation method

Docker

**Comment by shamoon** [comment]
I think youre referring to #576 --> #609
