### ISSUE TITLE
[Feature Request] Add Support for Xteve in a widget

### ISSUE THREAD

**Issue by iceman73** [benphelps/homepage#643]
### Description

I would love to get the status of Xteve and how many streams its playing

xteve converts IPTV into a mock hdhomerun to play inside of plex.

It has an API
https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/configuration.md#api

And its Status API returns, which is very useful in knowing its status:
  "status": true,
  "streams.active": 2,
  "streams.all": 21,
  "streams.xepg": 2,

**Comment by HamzaM** [comment]
This would be really good !

**Comment by iceman73** [comment]
Thankyou works great

**Comment by HamzaM** [comment]
> Author

Just wondering, what repo of Xteve do you use ? I found these 2 that are still in development : 
https://github.com/dnsforge-repo/xteve
https://github.com/SenexCrenshaw/xTeVe

**Comment by shamoon** [comment]
Those are just docker wrappers for the actual project. Hopefully it doesn’t matter? I tested his code with dnsforge one
