### ISSUE TITLE
Jellyfin NaN Bitrate

### ISSUE THREAD

**Issue by thunder3057** [benphelps/homepage#65]
Hey,

Maybe I missed another issue on here, but my Jellyfin Widget is working really nice the only thing thats not working is the bitrate indicator. For some reason when a user is playing something it will default to NaN. Might be a setting on my Jellyfin that is messing with the indicator but I'm not sure. 

Thanks in advance

**Comment by wjbridge** [comment]
I have also seen this issue when there is an active stream.

**Comment by benphelps** [comment]
Alright, there might be an API difference between Emby and Jellyfin then, I'll check it out.

**Comment by jackblk** [comment]
Also have the same issue.

From my check, I think we can use `NowPlayingQueueFullItems` and sum every MediaSources's bitrate.

![image](https://user-images.githubusercontent.com/12843654/189028557-63bc6a59-93d9-4dbc-ae27-7b4009a1290b.png)

**Comment by benphelps** [comment]
This has been fixed :)

**Comment by jackblk** [comment]
@varunpan I think @benphelps has changed the design. It is what you see right now, bitrate is not displayed anymore.
