### ISSUE TITLE
[Bug] UniFi Widget not displaying correct information

### ISSUE THREAD

**Issue by Pureball** [benphelps/homepage#653]
### Issue:
Currently the UniFi Widget is not displaying the correct information:

![image](https://user-images.githubusercontent.com/14904817/206705099-88728741-1936-47bb-8a78-acc548180e55.png)

![image](https://user-images.githubusercontent.com/14904817/206705268-feba3c8c-561d-4d7c-ab96-161eed5b45f7.png)
![image](https://user-images.githubusercontent.com/14904817/206705321-830b390e-7409-4b6b-9c51-5000bde1d011.png)

As you can see I have a total of 37 Wireless clients and 3 Wired clients. The only thing that seems correct is the Uptime and that WAN is up.

I have a UDM Pro and Network App both running the latest official version.
Homepage is installed on Docker on a Synology device (also running latest versions).
Also the user which has access to the UniFi Widget (UniFi OS) has "View Only" Network Role enabled nothing more (this should be sufficient).

### Expectation:
LAN users and WLAN Users should align with the information given in the UniFi Network app (in this case LAN 3 and WLAN 37).

Many thanks for looking into this.
Cheers!

**Comment by shamoon** [comment]
First of all, this data is reported directly from the API, e.g. `site.health[subsystem: wlan].num_users`, so theres not much we can do. Also, I have found that its the Unifi dashboard widget thats off. For example my UniFi dashboard (like the thing in your screenshot) shows 38 wireless clients but going to the actual clients tab shows me only 26, which is what homepage shows =)
