### ISSUE TITLE
[Feature Request] Mikrotik

### ISSUE THREAD

**Issue by babybenz0** [benphelps/homepage#655]
### Description

It would be nice to have a Mikrotik widget like Unifi or Omada, I try to do it but my programming skills is very poor😢
Mikrotik have an API and REST API, with API can write full commands but is most difficult to integrate, the only project that I think can be implemented is https://github.com/Trakkasure/mikronode , with REST API (https://help.mikrotik.com/docs/display/ROS/REST+API)  is not possible to execute full commands.
F.e to list active clients with command line is _ip dhcp-server lease print active count-only_  but with REST API is https://{ip}/rest/ip/dhcp-server/lease and gives all details for leases.
To show uptime in command line is _system resource print_ and REST API is ​https://{ip}/rest/system/resource (If is possible to show values like cpu usage or memmory it would be great)

It can be virtualized if you doesn't have a Mikrotik (https://mikrotik.com/download Check Cloud Hoster Router) but here I am for whatever you need. 

Thanks for this amazing project!

[output.txt](https://github.com/benphelps/homepage/files/10197510/output.txt)

**Comment by Oupsman** [comment]
Well, for now I have a widget that displays Uptime, Cpu Load and memory used. I'll work on the number of leases later (but I can't test it)

![DeepinScreenshot_select-area_20221223001439](https://user-images.githubusercontent.com/11260343/209240998-f82877ca-ba23-4672-8b96-95c63ce0e0ce.png)

**Comment by shamoon** [comment]
> Well, for now I have a widget that displays Uptime, Cpu Load and memory used. I'll work on the number of leases later (but I can't test it)

If you submit will offer comment feedback only =)

**Comment by Oupsman** [comment]
Well, I do have a working widget with the number of leases in my repo (mikrotik-widget branch), so fell free to comment :)

**Comment by babybenz0** [comment]
Hello @Oupsman and @shamoon ! I tested and works so good, the only thing that I would change is to add % to cpu load.
And by the way, would it be possible to create an information widget like unifi?
Thanks you guys😁
![mk](https://user-images.githubusercontent.com/1674567/209320694-c0fb27fc-a3dd-4833-9557-327631a7c6a0.png)

**Comment by Oupsman** [comment]
I'll do that this afternoon, thank you so much for your feedback.
