### ISSUE TITLE
[Feature Request]  Immich Support

### ISSUE THREAD

**Issue by C8opmBM** [benphelps/homepage#689]
### Description

Would be nice to have immich images widget support.

**Comment by madkatz01** [comment]
+1 for this

**Comment by spupuz** [comment]
i also would like it too :)

**Comment by Zlendy** [comment]
Hi! I'm thinking about implementing this feature. Would you like Homepage to pull this data plus the number of registered users?
![image](https://user-images.githubusercontent.com/22578704/214693967-d64d1b90-babd-41be-a04a-ca222e6dcb62.png)

**Comment by madkatz01** [comment]
This looks great! Thanks for looking into this! I wouldn't personally need the registered users, but maybe having the "allowed fields" notation for those who want to add it.

**Comment by C8opmBM** [comment]
Yes, it does look great.
