### ISSUE TITLE
ELIFECYCLE error during node install

### ISSUE THREAD

**Issue by droidus** [benphelps/homepage#692]
### Description

`<username>@homepage:~/homepage$ pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +382
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/<username>/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Downloading registry.npmjs.org/next/12.3.1: 6.51 MB/6.51 MB, done
Downloading registry.npmjs.org/react-icons/4.4.0: 13.6 MB/13.6 MB, done
Downloading registry.npmjs.org/@next/swc-linux-x64-musl/12.3.1: 15.3 MB/15.3 MB, done
Downloading registry.npmjs.org/@next/swc-linux-x64-gnu/12.3.1: 15.8 MB/15.8 MB, done
Downloading registry.npmjs.org/typescript/4.8.3: 11.9 MB/11.9 MB, done
Progress: resolved 382, reused 0, downloaded 380, added 382, done
node_modules/.pnpm/cpu-features@0.0.4/node_modules/cpu-features: Running install script...
node_modules/.pnpm/core-js-pure@3.25.2/node_modules/core-js-pure: Running postinstall script...
node_modules/.pnpm/core-js@3.25.2/node_modules/core-js: Running postinstall script...
 ELIFECYCLE  Command failed.
<username>@homepage:~/homepage$ pnpm build

> startpage@0.1.0 build /home/<username>/homepage
> next build

sh: 1: next: not found
 ELIFECYCLE  Command failed.
`

### Steps to reproduce

`pnpm install
pnpm build
`

### homepage version

latest

### Installation method

Other (please describe above)

**Comment by shamoon** [comment]
I think something is broken for you locally or perhaps its an issue with [`core-js`](https://github.com/zloirock/core-js) (I dont see anything obvious) but this cant really be broken since thats how the docker images are built etc, working for me locally.

**Comment by droidus** [comment]
How/where can I troubleshoot this?  Are there logs somewhere?

**Comment by shamoon** [comment]
You didn’t answer most of the questions in the template so I’m not sure of platform, os, etc, but it looks like your `pnpm install` is failing, maybe at the post-install script for core-js or the next package, can’t tell. You can start fresh but if you’re consistently getting the error you need to narrow down why the install is failing. That’s a general npm (/ pnpm) kinda issue of course.

If you’re not sure how to debug this perhaps building from source isn’t the ideal deployment for you, eg maybe docker would be better.

**Comment by remz1337** [comment]
For anyone else having the same issue, make sure you have the latest version of NodeJS/NPM install. I faced the same issue when installing from source on a fresh Ubuntu 22 with `apt install npm`, which only installed NodeJS 12 and NPM 8. Get the latest from https://github.com/nodesource/distributions
