### ISSUE TITLE
[Bug] New logo feature doesn't work as expected

### ISSUE THREAD

**Issue by vladaurosh** [benphelps/homepage#693]
### Description

New feature from https://github.com/benphelps/homepage/pull/664 doesn't work as expected, at least for me. I'm using v0.5.5
Setting this in widgets.yaml:
```
- logo:
    icon: sonarr.png
```
I get this
![image](https://user-images.githubusercontent.com/47857324/208276219-c23ff8fd-1da3-4d19-a59f-2bd1dff9a191.png)

According to PR icon should be all the way to the left.

### Steps to reproduce

Add this into widgets.yaml:
- logo:
    icon: sonarr.png

### homepage version

v0.5.5

### Installation method

Source

**Comment by vladaurosh** [comment]
Ah, ok, just figured out, position of the icon depends on where you've placed - logo: in widgets.yaml.
Is this intended? If yes, issue can be closed.

**Comment by vladaurosh** [comment]
Setting logo multiple times in widgets.yaml, produces this:
![image](https://user-images.githubusercontent.com/47857324/208278136-51fba77a-a530-4553-82ca-f9442a12e2c8.png)

**Comment by igorfrag** [comment]
Just did some testing here, logo should be place before the widget that you picked. So if you want in the left corner you should put logo before the resources widget.

**Comment by vladaurosh** [comment]
@igorfrag Yep, figured that out.
More interesting results, double logo:
![image](https://user-images.githubusercontent.com/47857324/208278322-27eb0a1b-cc8d-4bc6-99c1-a23368abc05e.png)

**Comment by igorfrag** [comment]
Not sure that's intended but it could be better explained.

**Comment by shamoon** [comment]
It’s not obvious yes, some widgets are right-aligned, but yes, order matters

**Comment by cchrkk** [comment]
Mmh, no matter what I do, it doesn't load any logo to me, also tried external hosted pngs. What could it be?

```
- resources:
    expanded: true
    disk:
      - /mnt/charlie
 - logo:
    source: sonarr.png
```
![image](https://user-images.githubusercontent.com/12370126/208396830-20e9da03-9f38-45ba-8b5f-2a9aecde858d.png)

**Comment by shamoon** [comment]
> Mmh, no matter what I do, it doesn't load any logo to me, also tried external hosted pngs. What could it be?

It’s `icon`
https://gethomepage.dev/en/widgets/logo/
