### ISSUE TITLE
[Bug] Prowlarr Service API Error

### ISSUE THREAD

**Issue by abramter** [benphelps/homepage#694]
### Description

The services widget for Prowlarr is giving a API Error. Nothing has changed and was working fine until a 2 updates ago.

Here is the error the API is showing. (BTW nothing in the logs for this.)

`API Error: HTTP Error
URL: http://192.168.1.150:9696/api/v1/indexerstats?apikey=apikey
Response Data:
{
  "message": "Error parsing column 3 (Data=07/23/2022 05:17:10 - DateTime)",
  "description": "System.Data.DataException: Error parsing column 3 (Data=07/23/2022 05:17:10 - DateTime)\n ---\u003E System.OutOfMemoryException: Exception of type \u0027System.OutOfMemoryException\u0027 was thrown.\n   at System.Data.SQLite.SQLiteConvert.UTF8ToString(IntPtr nativestring, Int32 nativestringlen)\n   at System.Data.SQLite.SQLite3.GetText(SQLiteStatement stmt, Int32 index)\n   at System.Data.SQLite.SQLite3.GetValue(SQLiteStatement stmt, SQLiteConnectionFlags flags, Int32 index, SQLiteType typ)\n   at System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i)\n   at Deserialize585f0fed-5b90-415f-b9a7-4129cc5a8fcb(IDataReader )\n   --- End of inner exception stack trace ---\n   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706\n   at Deserialize585f0fed-5b90-415f-b9a7-4129cc5a8fcb(IDataReader )\n   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)\u002BMoveNext()\n   at System.Collections.Generic.List\u00601..ctor(IEnumerable\u00601 collection)\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable\u00601 source)\n   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable\u00601 commandTimeout, Nullable\u00601 commandType)\n   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)\n   at NzbDrone.Core.Datastore.BasicRepository\u00601.Query(SqlBuilder builder)\n   at NzbDrone.Core.History.HistoryRepository.Between(DateTime start, DateTime end)\n   at NzbDrone.Core.History.HistoryService.Between(DateTime start, DateTime end)\n   at NzbDrone.Core.IndexerStats.IndexerStatisticsService.IndexerStatistics(DateTime start, DateTime end)\n   at Prowlarr.Api.V1.Indexers.IndexerStatsController.GetAll(Nullable\u00601 startDate, Nullable\u00601 endDate)\n   at lambda_method56(Closure , Object , Object[] )\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context)\n   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context)\n   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context)\n   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context)\n   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context)\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"
}`

### Steps to reproduce

1. Just setup a service widget for Prowlarr

### homepage version

v0.5.5

### Installation method

Docker

### Configuration

```yaml
- Prowlarr:
        icon: prowlarr.png
        href: http://192.168.1.150:9696
        description: Indexer Management
        server: local
        container: Prowlarr
        widget:
          type: prowlarr
          fields: ["enableIndexers", "numberOfGrabs", "numberOfQueries"]
          url: http://192.168.1.150:9696
          key: apikey
```

**Comment by shamoon** [comment]
On goal of the new api error feature is to give you a hint when there’s a problem, in this case output is telling you where the bug is coming from, it’s Prowlarr, not homepage:

eg `System.OutOfMemoryException: Exception of type \u0027System.OutOfMemoryException\u0027 was thrown.\n at System.Data.SQLite.SQLiteConvert.UTF8ToString` … `Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker`

**Comment by shamoon** [comment]
Presumably you should be able to reproduce the error by hitting the API which is all homepage is doing, eg https://gethomepage.dev/en/more/troubleshooting/
