### ISSUE TITLE
Unifi Widget: Add ability to specify site name

### ISSUE THREAD

**Issue by frg** [benphelps/homepage#706]
### Description

At the moment the Unifi Widget assumes the `default` site name as seem at this line https://github.com/benphelps/homepage/blob/main/src/widgets/unifi/component.jsx#L18. It would be ideal if this is configurable so that Homepage would be able to support Unifi Controllers with multiple sites.

Example payload
```json
{
   "meta":{
      "rc":"ok"
   },
   "data":[
      {
         "_id":"cF9v9DwRzPV8FG7woZRy8U2Z66cBJ4bpZ684yBQL3v6fcranc",
         "desc":"Site name",
         "name":"24AFK4j739653",
         "anonymous_id":"363dedcb-0df6-456c-b84a-266c9275d118",
         "health":[
            ...
         ],
         "num_new_alarms":0
      }
   ]
}
```

**Comment by micgogo** [comment]
+1 for multisite support

**Comment by Jimmy-SafeCash** [comment]
+1 for multisite support. Would be a welcome addition

**Comment by shamoon** [comment]
If anyone can test this is in `main` now, I don't want to muck with my production controller and its hard to test this with a dummy setup, its pretty straightforward though.

You can now optionally specify a `site` parameter to the widget which is the site name, e.g.
```
    url: https://localhost:8443
    username: admin
    password: password
    site: Test Site
```
(looks same for service widget)

**Comment by Jimmy-SafeCash** [comment]
> If anyone can test this is in `main` now, I don't want to muck with my production controller and its hard to test this with a dummy setup, its pretty straightforward though.
> 
> You can now optionally specify a `site` parameter to the widget which is the site name, e.g.
> 
> ```
>     url: https://localhost:8443
>     username: admin
>     password: password
>     site: Test Site
> ```
> 
> (looks same for service widget)

Thanks for this. Will have to test later (running helm version).

**Comment by Jimmy-SafeCash** [comment]
> If anyone can test this is in `main` now, I don't want to muck with my production controller and its hard to test this with a dummy setup, its pretty straightforward though.
> 
> You can now optionally specify a `site` parameter to the widget which is the site name, e.g.
> 
> ```
>     url: https://localhost:8443
>     username: admin
>     password: password
>     site: Test Site
> ```
> 
> (looks same for service widget)

Can confirm this is working on Helm - thanks
