### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Nindohana** [benphelps/homepage#709]
### Description

Having the ability to stack services who don't have any widgets for better aesthetic.
Please see attachments below :

![Old](https://user-images.githubusercontent.com/49897838/209077313-4cdd8aa8-0940-4fb5-afa0-b95e7b890c38.png)
![New](https://user-images.githubusercontent.com/49897838/209077319-03962300-0b18-4260-9cd8-64f752348e07.png)

**Comment by shamoon** [comment]
Please use #235
