### ISSUE TITLE
[Bug] Pi-hole API needs auth

### ISSUE THREAD

**Issue by brhahlen** [benphelps/homepage#711]
### Description

After updating Pi-hole to the latest version, there is no data coming from the API anymore, as it [now needs auth](https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/#page-content).
So, an `auth=` option is needed that will include the API token

### Steps to reproduce

Update Pi-hole to:
```
Pi-hole version is v5.14.2 (Latest: v5.14.2)
AdminLTE version is v5.18 (Latest: v5.18)
FTL version is v5.20 (Latest: v5.20)
Container tag is: 2022.12
```

### homepage version

nightly (de584ea, Dec 22, 2022)

### Installation method

Docker

**Comment by shamoon** [comment]
Thanks! Will update documentation after the changes are released but should be safe to merge into `main` before that
