### ISSUE TITLE
PiHole Widget Error

### ISSUE THREAD

**Issue by itguy327** [benphelps/homepage#717]
After updating pihole I get errors in the widget (NaN). I found this entry regarding an authentication requirement for the API but not sure it's relevant. https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/#page-content

If a browse the api.php directly, it returns data without issue. I updated homepage and still no joy.

Hoping it's my issue but if I can give any more details, please let me know

**Comment by farstrider** [comment]
I'm also having this issue.

PiHole v5.13: Homepage widget displays data as expected.
PiHole v5.14.2: Homepage widget displays "NaN."

**Comment by shamoon** [comment]
You didn’t use the template, but I’m assuming you’re on `main`

Pihole does now require auth on the endpoints if you have an admin password set, the widget now accepts a `key` with the api key

**Comment by shamoon** [comment]
See #711 closed by #714

**Comment by farstrider** [comment]
> You didn’t use the template, but I’m assuming you’re on `main`
> 
> Pihole does now require auth on the endpoints if you have an admin password set, the widget now accepts a `key` with the api key

I tried including "key" in the widget configuration, but it still shows "NaN."

**Comment by shamoon** [comment]
Please let me know the output of `curl -L -k http://piholehostorip/admin/api.php?summaryRaw&auth=yourpiholekey`

**Comment by farstrider** [comment]
> Please let me know the output of `curl -L -k http://piholehostorip/admin/api.php?summaryRaw&auth=yourpiholekey`

{"domains_being_blocked":166633,"dns_queries_today":60543,"ads_blocked_today":1486,"ads_percentage_today":2.454454,"unique_domains":1767,"queries_forwarded":23758,"queries_cached":35248,"clients_ever_seen":22,"unique_clients":21,"dns_queries_all_types":60543,"reply_UNKNOWN":781,"reply_NODATA":6798,"reply_NXDOMAIN":13157,"reply_CNAME":23969,"reply_IP":10003,"reply_DOMAIN":167,"reply_RRNAME":0,"reply_SERVFAIL":5646,"reply_REFUSED":0,"reply_NOTIMP":0,"reply_OTHER":0,"reply_DNSSEC":0,"reply_NONE":0,"reply_BLOB":22,"dns_queries_all_replies":60543,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1671757264,"relative":{"days":0,"hours":3,"minutes":13}}}

**Comment by shamoon** [comment]
Ah, there’s confusion here. 

To clarify, pihole updated their API which broke the homepage widget, the fix is currently in `main` but hasnt been released yet (eg will be in 0.5.6)

thanks for the curl, I think the aforementioned fix will work for you too
