### ISSUE TITLE
Docker Support - Container Start/Stop/Restart [Feature Request] 

### ISSUE THREAD

**Issue by cmuc24** [benphelps/homepage#725]
### Description

i've a bunch of services not running 24/7. portainer is nice but homepage is even better :) 
Each time login portainer search stack container however,, its worth time.

A simple API Call should do the work, Start / Stop container, maybe also Restart. 
Is the ContainerID present if i use docker.labels for the integration in homepage?
If not, a new label could do the job? 

The API Call and the UI Integration should not the big issue... tadaaa 👍 

Alternative, a direct jump into portainer, container management should also work.
But as i know, for that, there is no reference present (only if online)

If someone works with another solution for simple start/stop containers, please tell us 🥇 
Thx

**Comment by ilkersigirci** [comment]
This would be definitely a good addition to homepage. Is there any roadmap for this feature?

**Comment by cmuc24** [comment]
> Is there any roadmap for this feature?
Yes, there is/was a roadmap, but not here.

I've found only one Dashboard with an already implemented docker support.
Full featured imho, with all kind of useful things.
https://youtu.be/Mk9ZZiH5qi0?t=380
