### ISSUE TITLE
[Bug] Wrong debug messages around pyload proxy (minor)

### ISSUE THREAD

**Issue by kamilkrz** [benphelps/homepage#733]
### Description

I had to debug why I have problems with pyload widget I follow https://github.com/benphelps/homepage/issues/517 this and found that some debug info containing wrong service (Plex) so this is just simply copy/paste error and nothing major.

### Steps to reproduce

https://github.com/benphelps/homepage/blob/main/src/widgets/pyload/proxy.js 
find "plex"

### homepage version

v0.5.7 (9f63a5a)

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Thanks 😊
