### ISSUE TITLE
[Feature Request] CPU usage shouldn't "start" at 100%

### ISSUE THREAD

**Issue by itsthejb** [benphelps/homepage#737]
### Description

- Given the CPU widget is added to the homepage banner
- When loading the page, the CPU widget's usage will start from 100%:

<img width="250" alt="Screenshot 2022-12-28 at 09 07 43" src="https://user-images.githubusercontent.com/557391/209787791-cdae62e9-6c0e-4622-b994-f5ed5ec2fb32.png">

- Then over a few refreshes, it will reduce down to the true value
- This seems very misleading; in my opinion, it would be better to start at 0 to prevent giving the temporary idea that the server is overloaded
- Even better would be a loading state until there's a true value
- Seems like an easy fix?

Thanks very much for this great project, otherwise!

**Comment by shamoon** [comment]
Seems reasonable, Im assuming most folks dont feel as strongly in the opposite direction but then again it wouldn't surprise me too much =)

**Comment by itsthejb** [comment]
Cool! Thanks for the quick response

**Comment by itsthejb** [comment]
I updated my container, and I believe this fix is merged? Trying it out, it still doesn't quite seem to have the desired effect, and perhaps the fix isn't as simple as expected: Now the meter starts at 0%, jumps up to 100%, but then still stays at quite a high value:

<img width="188" alt="Screenshot 2022-12-31 at 10 04 55" src="https://user-images.githubusercontent.com/557391/210132731-545340b7-1866-47af-95b0-045e943a1240.png">

Running something like `uptime` directly gives a low average load:

```
» uptime
 10:05:18 up 17:35,  3 users,  load average: 3.10, 2.38, 2.27
```

Could it be that actually the measurement method is incorrect?

**Comment by brhahlen** [comment]
You're confusing load with CPU usage. Load is an average of the total usage over certain period s
If your load is 3.10, your CPU usage can definitely be high for a bit.


Better would be to look at it with `top` at the same time as loading homepage.
My assumption is that when homepage is loading, it consumes a bunch of cycles, as it needs to get information from multiple places, resulting in high CPU usage, and once it has that, CPU usage goes down again.

**Comment by itsthejb** [comment]
Hey,

Yeah that's possible. But using `top` I'm still seeing single digit numbers, so it seems strange that it would even get anywhere near 100%...

**Comment by benphelps** [comment]
Load average is not CPU usage as a %, a load average of 3.10 does not mean you're using 3.10% of your CPU.

On a single core system, a load average of 3.10 means your CPU is overloaded 210% of the time.  i.e, 2.10 processes had to wait for CPU time.

On a quad core system, it would mean 3.10 processes where able to be scheduled in time, which would mean mean your CPU usage is around 78%.

The math is: `load average / number of cores * 100`.

**Comment by shamoon** [comment]
Yes it works as expected for me and watching the bar move upwards (not usually to 100%) is satisfying, like watching it come alive.
