### ISSUE TITLE
Homepage dashboard breaks due to rate limiting on a query[Bug] 

### ISSUE THREAD

**Issue by ShrinivasKR** [benphelps/homepage#738]
### Description

Currently homepage dashboard does not work when it is opened repeatedly after a (currently unknown) number of times.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/8919133/209795210-10987857-e757-431c-8e77-dfc98a4b4156.png">

Response:
{"message":"API rate limit exceeded for **HIDDEN IP** (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

I only recently started to see this issue. I'm not sure if this query always used to be there and I'm only hitting the rate limits now or if this is a newly introduced query.

This doesn't seem like a necessary query for loading the homepage dashboard.

### Steps to reproduce

1. Go to Homepage Dashboard UI.
2. Reload (X) amount of times?

### homepage version

sha256:65b1a775e3323fe202c94161e40672f61446c4af8349c16bd24e2679c1912cd3

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
well ironically, the update checker was broken and I fixed it so now you’re seeing this. It was actually already hitting the API (so this limit was still getting hit) but response wasn’t being used.

but anyway, the limits should be very high looking at the docs. Are you intentionally just hitting refresh until you hit it? I don’t see why it would happen in normal use…

it’s also supposed to cache the data for 5 minutes but I suppose I’d need to make sure that’s working

**Comment by shamoon** [comment]
The unauthenticated limit is 60 per hour, I will double-check the caching but that’s still a lot of refreshes…

**Comment by ShrinivasKR** [comment]
> well ironically, the update checker was broken and I fixed it so now you’re seeing this. It was actually already hitting the API (so this limit was still getting hit) but response wasn’t being used.
> 
> but anyway, the limits should be very high looking at the docs. Are you intentionally just hitting refresh until you hit it? I don’t see why it would happen in normal use…
> 
> it’s also supposed to cache the data for 5 minutes but I suppose I’d need to make sure that’s working

I was migrating from my Synology's built in reverse proxy to Traefik and onboarding Authentik and using the homepage dashboard as my test page. There were much more refreshes than regular use for sure. Idk if it should have hit 60 though, especially if data is cached for 5 minutes.

**Comment by shamoon** [comment]
Yea, fair enough 👍
