### ISSUE TITLE
API Error Radarr / Sonarr works fine

### ISSUE THREAD

**Issue by Nomlla** [benphelps/homepage#74]
I used this template, and as you can see Sonarr works fine. But for some reason Radarr is reporting API error.
I made sure api and all other data is correct in services.yaml file. Am i missing something?

- Group A:
    - Sonarr:
        icon: sonarr.png
        href: http://sonarr.host/
        description: Series management
        widget:
          type: sonarr
          url: http://sonarr.host
          key: apikeyapikeyapikeyapikeyapikey

- Group B:
    - Radarr:
        icon: radarr.png
        href: http://radarr.host/
        description: Movie management
        widget:
          type: radarr
          url: http://radarr.host
          key: apikeyapikeyapikeyapikeyapikey

![Screenshot from 2022-09-08 20-29-26](https://user-images.githubusercontent.com/85586586/189248281-c7aa8b95-ed43-4da1-a01c-0945a5d32799.png)

**Comment by benphelps** [comment]
If you could provide logs from the browser console and the container console, it would help to narrow down the problem.

**Comment by beansQ** [comment]
Container Log:
Listening on port 3000
(node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[Error: ENOENT: no such file or directory, open '/app/config/services.yaml'] {

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/config/services.yaml'
}
[Error: ENOENT: no such file or directory, open '/app/config/services.yaml'] {

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/config/services.yaml'
}
[Error: ENOENT: no such file or directory, open '/app/config/services.yaml'] {

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/config/services.yaml'
}
services.yaml was copied to the config folder
bookmarks.yaml was copied to the config folder
widgets.yaml was copied to the config folder
docker.yaml was copied to the config folder
[
  500,
  Error: read ETIMEDOUT
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'read'
  }
]
[
  500,
  Error: read ETIMEDOUT
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'read'
  }
]
[
  500,
  Error: read ETIMEDOUT
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'read'
  }
]

Browser Console:
![co](https://user-images.githubusercontent.com/85586586/189430288-09e6fc0b-22ca-4dd1-87ba-86eb77c75733.png)

**Comment by mrbagpipe** [comment]
I have the same problem. I also captured the Network request that is failing:

![image](https://user-images.githubusercontent.com/24282649/189550955-e37f15af-f870-42c5-8f23-5397ed6c0667.png)

As for the container logs, the look the same as @Nomlla's

```
homepage | Listening on port 3000
homepage | (node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
homepage | (Use `node --trace-warnings ...` to show where the warning was created)
homepage | [Error: ENOENT: no such file or directory, open '/app/config/services.yaml'] {
homepage |   errno: -2,
homepage |   code: 'ENOENT',
homepage |   syscall: 'open',
homepage |   path: '/app/config/services.yaml'
homepage | }
```
I also tried using the IP address to no avail

**Comment by Nomlla** [comment]
> I have the same problem. I also captured the Network request that is failing:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/24282649/189550955-e37f15af-f870-42c5-8f23-5397ed6c0667.png)
> 
> 
> 
> As for the container logs, the look the same as @Nomlla's
> 
> 
> 
> ```
> 
> homepage | Listening on port 3000
> 
> homepage | (node:1) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
> 
> homepage | (Use `node --trace-warnings ...` to show where the warning was created)
> 
> homepage | [Error: ENOENT: no such file or directory, open '/app/config/services.yaml'] {
> 
> homepage |   errno: -2,
> 
> homepage |   code: 'ENOENT',
> 
> homepage |   syscall: 'open',
> 
> homepage |   path: '/app/config/services.yaml'
> 
> homepage | }
> 
> ```
> 
> I also tried using the IP address to no avail

I believe the latest update fixed this issue. I'm only saying that because this issue was fixed after last update.

**Comment by benphelps** [comment]
Yeah, the latest update fixed some cases where loading would fail due to some specific configuration cases.

The 404 is fine, it's just part the i18n support looking for a more specific language than `en`, but we're sharing the same one for `en-US` and `en-GB`.
