### ISSUE TITLE
Random issue with formatting

### ISSUE THREAD

**Issue by kBraDrs** [benphelps/homepage#755]
I occasionally lose all of my formatting with columns etc, but then after a random time, this fixes itself and everything appears as intended. Not sure how to replicate as it seems random. No code has been changed and the issue arose maybe 3 patches ago.

![image](https://user-images.githubusercontent.com/102444317/210182356-0c45f19e-31b9-4cc6-8ebf-eb4fbfdeba2c.png)

In the image is an example of when it is not working as expected, and then later it might be correctly displayed without any changes.

**Comment by shamoon** [comment]
This is likely #576 —> #609
