### ISSUE TITLE
[Feature Request] Synology Storage Widget

### ISSUE THREAD

**Issue by ozdeadmeat** [benphelps/homepage#762]
### Description

Something that reports health of an array, if it is doing a scrub, total space and space remaining. Also possibly reporting on specific volumes or shares would also be handy.

**Comment by Oupsman** [comment]
I'm actually working on this 

![image](https://user-images.githubusercontent.com/11260343/210785664-d3cfcba2-b24a-4e65-b82b-092fdaf773f4.png)

Not Storage focused though.

**Comment by 2ndwonder** [comment]
> I'm actually working on this 
> 
> ![image](https://user-images.githubusercontent.com/11260343/210785664-d3cfcba2-b24a-4e65-b82b-092fdaf773f4.png)
> 
> Not Storage focused though.

Looks nice, can't wait to try it out

**Comment by szczottie** [comment]
Looking forward for that one! Thank you

**Comment by TibiaBubble** [comment]
> I'm actually working on this
> 
> ![image](https://user-images.githubusercontent.com/11260343/210785664-d3cfcba2-b24a-4e65-b82b-092fdaf773f4.png)
> 
> Not Storage focused though.

wow this looks amazing!
Will you add the option to see total space?

**Comment by Oupsman** [comment]
I'm not sure that that's relevant, you know how much storage you have on your NAS, don't you ?

**Comment by TibiaBubble** [comment]
> I'm not sure that that's relevant, you know how much storage you have on your NAS, don't you ?

Of course I know the size of one or two of them but if I’ll add more in the future or buy new disks I’ll maybe forget 😅

never less it’s an awesome job and do it as you please 😀

**Comment by Oupsman** [comment]
Well, that's not a very difficult thing to do, so here it is :
![image](https://user-images.githubusercontent.com/11260343/211857415-5b73d9de-51e2-4f70-924b-79cfef6e17de.png)

**Comment by TibiaBubble** [comment]
When will you publish this so everyone can try it out? :)

**Comment by Oupsman** [comment]
I'll try to make a PR next weekend.

**Comment by drinksomewhiskey** [comment]
@Oupsman 

Do you think there's any way to pull stats on VMs running through synology virtual machine manager?

**Comment by Oupsman** [comment]
Maybe, but it should be a different widget, from my point of vue.

**Comment by TibiaBubble** [comment]
Waiting with excitement 😅😃🥹

**Comment by xaavian** [comment]
Would love to see something similar for QNAP too

**Comment by JazzFisch** [comment]
> Would love to see something similar for QNAP too

Please create a new feature request with this information.

**Comment by TibiaBubble** [comment]
How will we know when this is released for public use?

**Comment by shamoon** [comment]
> How will we know when this is released for public use?

When it’s in the release notes!

**Comment by TibiaBubble** [comment]
> > How will we know when this is released for public use?
> 
> When it’s in the release notes!

Do we need to upgrade the homepage version via have now (and if so, how do we upgrade?) 😅

**Comment by javijuji** [comment]
> > > How will we know when this is released for public use?
> > 
> > 
> > When it’s in the release notes!
> 
> Do we need to upgrade the homepage version we have now (and if so, how do we upgrade?) 😅

The same way you update any container. Pull new image and recreate the container.

**Comment by Macleykun** [comment]
This can be closed as it's released :)
https://gethomepage.dev/en/services/diskstation/
