### ISSUE TITLE
Local icons don't show

### ISSUE THREAD

**Issue by tnagels** [benphelps/homepage#77]
I have mapped a volume to /public/icons as instructed, but the icon will not show up.

In the folder I have a file otmonitor.png, if I add this as /icons/opentherm.png in the yaml, it shows as a broken image in the homepage.

PS. love your work, only thing which upsets me is that the links are not centered identially depending on the presence of a status indicator and/or an icon.

**Comment by ShlomiPorush** [comment]
sane issue here 
https://github.com/benphelps/homepage/issues/75

**Comment by tnagels** [comment]
Did not see that one as it is closed. But the issue remains, so I will leave it open here. I'm sure the mapping is done correctly.

**Comment by ShlomiPorush** [comment]
> **You need to restart the container for new icons to be recognized.**

This workd for me. Thank you

**Comment by tnagels** [comment]
That works - closing the issue as this is a valid way to do things.
