### ISSUE TITLE
Log path is not working [Bug] 

### ISSUE THREAD

**Issue by serhattsnmz** [benphelps/homepage#775]
### Description

I cannot change the log path even if I change the path in `settings.yaml` file. Still logs go under `/app/config/logs` path. 

### Steps to reproduce

1. Add `logfile: /var/log/homepage` line in `settings.yaml` file.
2. Restart the container
3. Logs are going under `/app/config/logs`. 

### homepage version

v0.5.9 (f6b1304, Dec 31, 2022)

### Installation method

Docker

### Configuration

```yaml
settings.yaml

...
logfile     : /var/log/homepage
..
```
```


### Container Logs

There is not related logs.

### Browser Logs

There is not related logs.

### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Sorry, the correct setting is `logpath`. I've updated the docs
