### ISSUE TITLE
[Bug] Aesthetic failure due to translation in SANnzbd Service Widger

### ISSUE THREAD

**Issue by LETRA** [benphelps/homepage#780]
### Description

The English translation has a too long sentence of the word "timeleft" and the alignment of the widgets is broken. 

![Captura de Pantalla 2023-01-07 a las 20 15 30](https://user-images.githubusercontent.com/16805254/211166904-ecda6087-7412-4bd0-970f-7eb142b4cafb.jpg)

### Steps to reproduce

1. Set translate Homepage to spanish
2. Add SABnzbd service widget to Homepage
3. The alignment is broken

### homepage version

Latest Stable

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
See #235 but I’m not sure the solution here, the site is responsive so if you make it narrower, things change. If you submit a shorter translation perhaps that would help

**Comment by LETRA** [comment]
This could be fixed by changing the translation from "_**Tiempo restante**_" (_time remaining_) to "_**restante**_" _(remaining_).

**Comment by shamoon** [comment]
Great, that’s done over at weblate https://hosted.weblate.org/engage/homepage/

**Comment by LETRA** [comment]
> Great, that’s done over at weblate https://hosted.weblate.org/engage/homepage/

I don't quite understand, is it already done or are you telling me to modify it there?

**Comment by shamoon** [comment]
Weblate is a user-supported translation tool, so this change would need to be submitted over there (and then would be included in the next release here)

**Comment by LETRA** [comment]
Agreed. Thank you. Then I'll send it over there.
