### ISSUE TITLE
[Feature Request] Dockerhub image

### ISSUE THREAD

**Issue by Blitzritze** [benphelps/homepage#781]
### Description

It's not really a new feature, however Watchtower (automatic container updates) is not able to check ghcr.io images, so it would be helpful to publish them to Dockerhub.
Portainer also has problems with ghcr.io but I could work around that with a docker pull command.

**Comment by mattalat1** [comment]
Watchtower has been updating my homepage image just fine?

**Comment by Blitzritze** [comment]
Strangely Portainer and watchtower can't make a pull request on Github images

This is the Watchtower Error
![grafik](https://user-images.githubusercontent.com/34802563/211192521-a88ba803-564d-4333-88fa-26327da401e6.png)

Portainer simply says that no image is found.

**Comment by Blitzritze** [comment]
Okay sorry it was my fault, you have to use the "Advanced Mode" if you don't use a dockerhub image.
