### ISSUE TITLE
[Bug] Tautulli Service Widget Not Updating

### ISSUE THREAD

**Issue by xPoP** [benphelps/homepage#787]
### Description

Hi, after the latest update, v0.5.10 (e1799f1, Jan 7, 2023), the Tautulli Widget's stream progress bar is not updating while the webpage is open and focused. If I switch tabs and return, it will update, but only in 10 second intervals. 

If I recall correctly, the widget would accurately update by the second while the page was focused.

Thanks for all the work done on this project. Appreciate your time.

### Steps to reproduce

If someone on my Plex server is actively watching a show and is at 01:22:

1. I'm looking at my Homepage, the time does not change at all. 
2. Toggle tabs back then forth while that session should be 01:28, it will still show 01:22. 
3. Toggle tabs again while the session should be at 01:38, it will show 01:32.

### homepage version

v0.5.10 (e1799f1)

### Installation method

Docker

### Container Logs

Every ~30sec in logs:
[2023-01-09T01:08:01.935Z] error: undefined

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Ah thanks, should be fixed
