### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ancfdy** [benphelps/homepage#808]
### Description

Only icons added for the first time can be displayed，Icons added later cannot be displayed

### Steps to reproduce

Only icons added for the first time can be displayed，Icons added later cannot be displayed

### homepage version

v0.5.5

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by ancfdy** [comment]
Restarting the container doesn't work either.
Delete the container and reinstall it，The icon will display normally

**Comment by dtypo** [comment]
+1 for this!
I was getting MAD changing the file type/resolution/whatever on my newly added icons 😑

**Comment by shamoon** [comment]
Recreate the container
