### ISSUE TITLE
[Feature Request] Support for Syncthing

### ISSUE THREAD

**Issue by update-freak** [benphelps/homepage#812]
### Description

Hello developer,

it would be great if you could support for the docker container Syncthing (https://github.com/syncthing/syncthing/blob/main/README-Docker.md) that the current status of the Synchronisation can be seen.

**Comment by JazzFisch** [comment]
I think that is being handled by this widget, no?
https://gethomepage.dev/en/services/syncthing-relay-server/

**Comment by rohan3au** [comment]
Can we re-open this for the creation of a Syncthing client Widget (not Syncthing Relay Server)?

**Comment by blumarten** [comment]
> Can we re-open this for the creation of a Syncthing client Widget (not Syncthing Relay Server)?

+1 for this

**Comment by PlexSheep** [comment]
I'm currently looking at this too. [This](https://docs.syncthing.net/rest/system-connections-get) API Point could be used to get the total rx and tx amount for example. My Client does not allow API calls without Token authentification, but that authentification is achieved with an additional HTTP Header (`X-API-Key: abc123`), which seems to be incompatible with the authentification of the regular custom api entry.

**Comment by fede843** [comment]
This feature would be much appreciated indeed.

**Comment by MuratovAS** [comment]
Here is a working example configuration for Syncthing
https://github.com/gethomepage/homepage/pull/1869

**Comment by jumbi77** [comment]
> Here is a working example configuration for Syncthing #1869

Nice, can this config be extracted to an own syncthing client plugin for homepage?

**Comment by 0phoff** [comment]
I used the `customapi` to create a widget that shows statistics of a single folder as this was more useful to me than the global information shown in #1869.

```yaml
# Docker compose syntax
labels:
  - homepage.widget.type=customapi
  - homepage.widget.method=GET
  - homepage.widget.url=http://syncthing:8384/rest/db/status?folder=<<<FOLDER_ID>>>
  - homepage.widget.headers.X-API-Key=<<<API-KEY>>>
  - homepage.widget.mappings[0].label=Files
  - homepage.widget.mappings[0].field=localFiles
  - homepage.widget.mappings[0].format=number
  - homepage.widget.mappings[1].label=Errors
  - homepage.widget.mappings[1].field=pullErrors
  - homepage.widget.mappings[1].format=number
  - homepage.widget.mappings[2].label=Unsynced
  - homepage.widget.mappings[2].field=needBytes
  - homepage.widget.mappings[2].format=bytes
  - homepage.widget.mappings[3].label=Scanned
  - homepage.widget.mappings[3].field=stateChanged
  - homepage.widget.mappings[3].format=relativeDate
  - homepage.widget.mappings[3].locale=en-ie
  - homepage.widget.mappings[3].style=short
```

Enter your *FOLDER_ID* in the `url` label and your *API-KEY* in the `X-API-Key` label, and you should see the following result:

![image](https://github.com/gethomepage/homepage/assets/11853089/9af8cff8-9f86-4bf2-897a-501b8da7415d)

**Comment by B0rax** [comment]
> > Nice, can this config be extracted to an own syncthing client plugin for homepage?
> 
> I made a widget. Extended functions in comparison with `customapi`.
> 
> I follow the rules. I have to collect 5 'up-votes'.
> 
> [main...MuratovAS:homepage:syncthing](https://github.com/gethomepage/homepage/compare/main...MuratovAS:homepage:syncthing)
> 
> ![image](https://private-user-images.githubusercontent.com/50487552/298029489-f36cd3d4-f166-4067-8a60-b50a2ba0e4d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjU4OTYsIm5iZiI6MTcwNzcyNTU5NiwicGF0aCI6Ii81MDQ4NzU1Mi8yOTgwMjk0ODktZjM2Y2QzZDQtZjE2Ni00MDY3LThhNjAtYjUwYTJiYTBlNGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA4MTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZmRhZjc2YTg0NWJjMmE1NjQ3MzJjNmQ0OWQ4ZTA3YjU2YWFjMjlhYmMyZTE1MzkwNGE3ZjQ0MzIwNWNkOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0LMYlV4eu3MKMmAHuhlJHGUbRuECMF4cADWfD-XcXSo)
> 
> P.S. I still couldn’t get a response from `system/connections`, I need to change the proxy.

What do you mean with "upvotes"? Where Can I upvote this? The link you share is not something where I can upvote...
