### ISSUE TITLE
[Bug] PNG favicons are inconsistently not working

### ISSUE THREAD

**Issue by dansity** [benphelps/homepage#821]
### Description

When using PNG images for favicons from a local folder they are inconsistently not working. They are mostly not working.
See two attached png images. Both 300x300px, non interlaced 8bit png files, but one of them is just not loading on the homepage. They are in the same folder, same permissions. Lidl is loading, aliexpress is not.
![lidl](https://user-images.githubusercontent.com/31413689/212493778-691feada-c938-48f3-9f10-771b9079330f.png)
![aliexpress](https://user-images.githubusercontent.com/31413689/212493795-b1a08a14-fd51-4232-8e25-c9bcbcbc2bcc.png)

<img width="911" alt="2023-01-14 20_57_11-favicon - FreeCommander XE" src="https://user-images.githubusercontent.com/31413689/212493954-56428cc6-f14e-4f1a-a61f-2fe42d52e4aa.png">

### Steps to reproduce

Make two bookmarks and use the two png file attached. One will work the other will not.

### homepage version

v0.5.10 (e1799f1, Jan 7, 2023)

### Installation method

Unraid

### Configuration

```yaml
I have tried to save the png in various different way to see if any of it is working with no luck.
```

### Container Logs

There are no errors related to this.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Not sure but seems something specific over there, I cant reproduce. It doesnt really make sense either unless the file is malformed, screenshot is testing with the following config:

```
- Test:
    - Remote 1:
        - icon: https://user-images.githubusercontent.com/31413689/212493795-b1a08a14-fd51-4232-8e25-c9bcbcbc2bcc.png
          href: https://github.com/
    - Local 1:
        - icon: /icons/212493795-b1a08a14-fd51-4232-8e25-c9bcbcbc2bcc.png
          href: https://github.com/
    - Remote 2:
        - icon: https://user-images.githubusercontent.com/31413689/212493778-691feada-c938-48f3-9f10-771b9079330f.png
          href: https://github.com/
    - Local 2:
        - icon: /icons/212493778-691feada-c938-48f3-9f10-771b9079330f.png
          href: https://github.com/
```

<img width="405" alt="Screen Shot 2023-01-14 at 1 51 13 PM" src="https://user-images.githubusercontent.com/4887959/212498703-9ef2d7c1-ac06-42f3-891f-4aa1ff42d591.png">

**Comment by dansity** [comment]
so... do you have any tips what should i try? I'm glad its working for you but for me it is not the case.
Here are the permissions from the console of the container. Outlook, youtube kids, lidl, gmail icon working. Aliexpress, youtube and a couple more does not working. There is simply no pattern in it.
<img width="560" alt="2023-01-14 23_13_01-docker exec -it homepage sh (TEVENAS) – Mozilla Firefox" src="https://user-images.githubusercontent.com/31413689/212499486-4dea038b-7272-41cd-a36e-e7b65bdf61e8.png">

**Comment by httpedo13** [comment]
I have the same issue, I downloaded the home assistant png logo from GitHub, upload into homepage and I have 404 error

**Comment by shamoon** [comment]
I don’t have an obvious guess but the randomness makes me think even less there’s an issue on this code. Those images are loaded as simple image tags so any issue would be related to nextjs serving the images

did you try basic things like recreating the container?

**Comment by dansity** [comment]
I figured it out:
I have to restart the container every time I add a new png file. If I simply add a png to the folder and try to link it it is basically non existent... Is there something like an indexing procedure during the startup of the container?

**Comment by httpedo13** [comment]
> I don’t have an obvious guess but the randomness makes me think even less there’s an issue in our code, which is why this was closed. Those images are loaded as simple image tags so any issue would be related to nextjs serving the images
> 
> did you try basic things like recreating the container?

I recreated with the script listed in this page: https://tteck.github.io/Proxmox/ but still all the images are not loaded. This is an extract of my configuration:
```
- Services:
    - Home Assistant:
        href: url
        icon: /logos/homeAssistant.png

- Network:
    - Unifi Controller:
        href: https://unifi.ui.com/dashboard
        icon: /logos/unifi.png
        widget:
          type: unifi
          url: https://ip:443
          username: user
          password: pass
    - NGINX:
        href: http://ip:81
        icon: /logos/nginx.png
        widget:
          type: npm
          url: url
          username: user
          password: pass
```
<img width="1438" alt="Screenshot 2023-01-15 alle 20 48 09" src="https://user-images.githubusercontent.com/40502451/212563675-e7f84f3b-1d38-4597-b89e-925b85fb3eff.png">

**Comment by httpedo13** [comment]
<img width="549" alt="Screenshot 2023-01-15 alle 20 50 28" src="https://user-images.githubusercontent.com/40502451/212563770-67704b49-9470-43d2-aeec-d7f299769770.png">

**Comment by httpedo13** [comment]
<img width="548" alt="Screenshot 2023-01-15 alle 20 51 44" src="https://user-images.githubusercontent.com/40502451/212563814-09bf223a-e60e-43cc-8e8b-8c709de7febd.png">

**Comment by dansity** [comment]
Try what I did. Add images then edit the yaml then restart the container. You dont need to rebuild it just restart.

**Comment by httpedo13** [comment]
> Try what I did. Add images then edit the yaml then restart the container. You dont need to rebuild it just restart.

Don't work

**Comment by httpedo13** [comment]
I updated to the latest version and it still image doesn't work
