### ISSUE TITLE
[Bug] Placing several portainer widgets in the same services group.

### ISSUE THREAD

**Issue by luckkmaxx** [benphelps/homepage#822]
### Description

When you do it, all portainer widgets inside the same group **will take the values of the first one in group.**

### Steps to reproduce

When you disable/comment the first portainer widget in group, all other portainer widgets in the same group gets an **API error** in its widget:

`Unexpected token 'I', "Internal S"... is not valid JSON`

So to get all working I had to split portainers in different groups.

### homepage version

0.5.10

### Installation method

Docker

### Other

Nothing else. I think its an easy to reproduce bug.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [x] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
You didn’t post your config but my guess is you need to give them different names is all

**Comment by luckkmaxx** [comment]
wow.  As simple as that. I didnt tried yet but Im sure thats the problem. How didnt I saw this before posting?!
Thank you for the fast reply.

**Comment by luckkmaxx** [comment]
I confirm that was my mistake. Setting different names solves everything.

**Comment by shamoon** [comment]
Not always obvious what to search for :)
