### ISSUE TITLE
[Bug] OPNSense widget fails if no `wan` interface

### ISSUE THREAD

**Issue by DjSni** [benphelps/homepage#823]
### Description

I have tried to connect to my OPNSense, but unfortunately the widget always tries to connect via port 443, but since my firewall is only accessible via port 80, this does not work.

The error I get directly in the GUI:
```
Something went wrong.
TypeError: Cannot read properties of undefined (reading 'bytes transmitted')

    at l (http://my.unraid.ip:port/_next/static/chunks/1147.775a9878f52bba10.js:1:1072)
    at d (http://my.unraid.ip:port/_next/static/chunks/3306-995fe34fc4fa03e6.js:1:12200)
    at n (http://my.unraid.ip:port/_next/static/chunks/pages/index-a920fe3fa732cc87.js:1:6177)
    at G (http://my.unraid.ip:port/_next/static/chunks/pages/index-a920fe3fa732cc87.js:1:13586)
    at div
    at li
    at P (http://my.unraid.ip:port/_next/static/chunks/pages/index-a920fe3fa732cc87.js:1:15377)
    at ul
    at L (http://my.unraid.ip:port/_next/static/chunks/pages/index-a920fe3fa732cc87.js:1:18363)
    at div
    at D (http://my.unraid.ip:port/_next/static/chunks/pages/index-a920fe3fa732cc87.js:1:18650)
    at div
    at div
    at Q (http://my.unraid.ip:port/_next/static/chunks/pages/index-a920fe3fa732cc87.js:1:31457)
    at n (http://my.unraid.ip:port/_next/static/chunks/pages/index-a920fe3fa732cc87.js:1:6177)
    at http://my.unraid.ip:port/_next/static/chunks/pages/_app-cdb2197abd3c9b3a.js:1:87716
    at V (http://my.unraid.ip:port/_next/static/chunks/pages/index-a920fe3fa732cc87.js:1:29514)
    at div
    at div
    at te (http://my.unraid.ip:port/_next/static/chunks/pages/index-a920fe3fa732cc87.js:1:34832)
    at a (http://my.unraid.ip:port/_next/static/chunks/pages/_app-cdb2197abd3c9b3a.js:1:70851)
    at s (http://my.unraid.ip:port/_next/static/chunks/pages/_app-cdb2197abd3c9b3a.js:1:71408)
    at u (http://my.unraid.ip:port/_next/static/chunks/pages/_app-cdb2197abd3c9b3a.js:1:70283)
    at http://my.unraid.ip:port/_next/static/chunks/pages/_app-cdb2197abd3c9b3a.js:1:87716
    at http://my.unraid.ip:port/_next/static/chunks/pages/_app-cdb2197abd3c9b3a.js:1:69564
    at l (http://my.unraid.ip:port/_next/static/chunks/pages/_app-cdb2197abd3c9b3a.js:1:1461)
    at n (http://my.unraid.ip:port/_next/static/chunks/pages/_app-cdb2197abd3c9b3a.js:1:61774)
    at r (http://my.unraid.ip:port/_next/static/chunks/main-d2b206db40ae9853.js:1:6948)
    at Y (http://my.unraid.ip:port/_next/static/chunks/main-d2b206db40ae9853.js:1:9190)
    at ie (http://my.unraid.ip:port/_next/static/chunks/main-d2b206db40ae9853.js:1:11830)
```

![image](https://user-images.githubusercontent.com/31524614/212536517-3ff097f6-49ca-465f-a404-6042fb4a2e64.png)

### Steps to reproduce

Add a OPNSense widget but the Firewall ist only on Port 80 reachable.

### homepage version

v.0.5.10 (e1799f1, 7. Jan. 2023)

### Installation method

Unraid

### Container Logs

[2023-01-14T09:32:11.306Z] error: <httpProxy> Error calling https://firewall.ip/api/diagnostics/traffic/interface...
[2023-01-14T09:32:11.307Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT firewall.ip:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: 'firewall.ip',
    port: 443
  }
]

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Please post your config and the output from the troubleshooting guide. I don’t think there is anything that would prevent using :80

**Comment by DjSni** [comment]
my services.yaml
```yaml
- Firewall:
    - OPNSense:
        icon: /icons/opnsense.png
        href: http://firewall.ip
        #description: 
        widget:
          type: opnsense
          url: http://firewall.ip
          username: api_key
          password: api_secret
          fields: ["uptime", "cpu", "memory", "wanUpload", "wanDownload"]
          #fields: ["cpu"]
```


the log part:
```log
[2023-01-14T09:32:11.307Z] error: <httpProxy> Error calling https://firewall.ip//api/diagnostics/traffic/interface...
[2023-01-14T09:32:11.308Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT firewall.ip:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: 'firewall.ip',
    port: 443
  }
]
[2023-01-14T09:32:11.309Z] error: <httpProxy> Error calling https://firewall.ip//api/diagnostics/activity/getActivity...
[2023-01-14T09:32:11.311Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT firewall.ip:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: 'firewall.ip',
    port: 443
  }
]
```

it seems that it always wants to connect via HTTPS even though I entered HTTP.

**Comment by shamoon** [comment]
This widget uses our 'generic' proxy which shouldn't call anything other than the config url. If this were true many of our widgets would fail for the same reason.

Hate to say it, but have you tried re-creating the container?

**Comment by DjSni** [comment]
strange, I have several services running here with only http that are displayed correctly.
I have just reset the container but unfortunately no success.

**Comment by shamoon** [comment]
I will rebuild my testing opnsense vm and double check later

**Comment by shamoon** [comment]
Yea mate, sorry I cant reproduce this, here's with http:
<img width="407" alt="Screen Shot 2023-01-15 at 2 21 44 PM" src="https://user-images.githubusercontent.com/4887959/212570285-a21bc6f0-6ec9-4d66-a08f-75fae77bb096.png">

```yaml
     - OPNSense:
          icon: opnsense.png
          description: opnsense
          widget:
               type: opnsense
               url: http://10.0.1.99
               username: -
               password: -
```

I have to wonder if its something about your firewall setup, something about unraid maybe, not sure. But I dont really think theres a bug here on our end.

**Comment by DjSni** [comment]
Thanks for the help but I can't seem to get it to work.
is there a way to enable a debug log ?

**Comment by DjSni** [comment]
I just remembered that my WAN interface is called COAX, could this produce the error?

**Comment by shamoon** [comment]
Again, it might be helpful to see the output of the curl calls if you follow the troubleshooting guide

![Bug  OPNSense widget · Issue #823 · benphelpshomepage](https://user-images.githubusercontent.com/4887959/213925271-7932b6f4-ec1e-4664-ae45-91a6b49a3549.png)

**Comment by DjSni** [comment]
curl: http://firewall.ip/api/diagnostics/traffic/interface

```
{"interfaces":{"opt1":{"flags":"8843","promiscuous listeners":"0","send queue length":"0","send queue max length":"50","send queue drops":"11405","type":"Ethernet","address length":"6","header length":"14","link state":"2","vhid":"0","datalen":"152","mtu":"1500","metric":"0","line rate":"1000000000 bit\/s","packets received":"1231016259","input errors":"0","packets transmitted":"974383218","output errors":"0","collisions":"0","bytes received":"1297921522537","bytes transmitted":"994602134170","multicasts received":"16018415","multicasts transmitted":"310","input queue drops":"0","packets for unknown protocol":"0","HW offload capabilities":"0x0","uptime at attach or stat reset":"1","name":"COAX"},"lan":{"flags":"8863","promiscuous listeners":"0","send queue length":"0","send queue max length":"50","send queue drops":"0","type":"Ethernet","address length":"6","header length":"18","link state":"2","vhid":"0","datalen":"152","mtu":"1500","metric":"0","line rate":"10000000000 bit\/s","packets received":"980736526","input errors":"0","packets transmitted":"1210947993","output errors":"0","collisions":"0","bytes received":"994637714296","bytes transmitted":"1295580754362","multicasts received":"10580964","multicasts transmitted":"0","input queue drops":"0","packets for unknown protocol":"0","HW offload capabilities":"0x0","uptime at attach or stat reset":"1","name":"LAN"},"opt2":{"flags":"8043","promiscuous listeners":"0","send queue length":"0","send queue max length":"50","send queue drops":"1","type":"PPP","address length":"0","header length":"0","link state":"2","vhid":"0","datalen":"152","mtu":"1420","metric":"0","line rate":"0 bit\/s","packets received":"1109314","input errors":"0","packets transmitted":"1566236","output errors":"0","collisions":"0","bytes received":"111421363","bytes transmitted":"1779167545","multicasts received":"0","multicasts transmitted":"0","input queue drops":"0","packets for unknown protocol":"0","HW offload capabilities":"0x0","uptime at attach or stat reset":"79","name":"VPN"},"opt3":{"flags":"8043","promiscuous listeners":"0","send queue length":"0","send queue max length":"50","send queue drops":"0","type":"PPP","address length":"0","header length":"0","link state":"2","vhid":"0","datalen":"152","mtu":"1420","metric":"0","line rate":"0 bit\/s","packets received":"0","input errors":"0","packets transmitted":"0","output errors":"0","collisions":"0","bytes received":"0","bytes transmitted":"0","multicasts received":"0","multicasts transmitted":"0","input queue drops":"0","packets for unknown protocol":"0","HW offload capabilities":"0x0","uptime at attach or stat reset":"79","name":"VPN_SERVER"}},"time":1674402854.029806}
```

**Comment by shamoon** [comment]
Yep, your setup has no `wan` interface. Any idea why?

**Comment by shamoon** [comment]
(or at least its listed as `opt`)

**Comment by DjSni** [comment]
yes that is because I have virtualized my firewall and when configuring the driver was not yet loaded. might be good if you could just specify wan optX in the config.

**Comment by shamoon** [comment]
Sorry not familiar with opnsense particularly, if no wan is specified can we assume opt1 will? Most likely thing to do here is check rather than making it another option

**Comment by DjSni** [comment]
That is a good idea, but theoretically I can bind the WAN interface everywhere e.g. also opt8. Again it is also possible to build a multi wan system, so with 2 or more WAN interfaces. Therefore I think a config possibility where you can set the interface would be more practical.

**Comment by shamoon** [comment]
Yea fair enough. Will update the PR

**Comment by DjSni** [comment]
Thanks, is there any way I can test the PR as docker?

**Comment by shamoon** [comment]
Unfortunately no. On my wishlist is building containers for testing but we don’t currently do that. You can patch the code directly in your container (not all that easy), spin up a dev instance to test the PR, or tbh we’ll prob merge it into main soon (it’s a pretty simple change) and you can test against that

**Comment by shamoon** [comment]
Once the image builds (~15m or so) you can test this out in `main`

**Comment by DjSni** [comment]
Ok, cool I will test it then immediately.

**Comment by DjSni** [comment]
seems to work now! Big thanks.

![image](https://user-images.githubusercontent.com/31524614/213944665-d54f4569-2bb8-4edf-858f-11025bd9309b.png)
