### ISSUE TITLE
[Feature Request] Proxy requests to internal network when homepage is hosted on a cloud server

### ISSUE THREAD

**Issue by sleepy-soul** [benphelps/homepage#829]
### Description

Hi, 
First of all, Thanks for making this dashboard. Really loving it for its simplicity and minimal resources usage. 

So, in my current setup, I am running homepage on a cloud server. I am able to monitor the services running on same machine properly and API's are also working for public URLs. I have Pi-Hole running in my home and suppose its running on IP - 192.168.1.2/24. Is there any option that this API request and ping request goes out from my browser which is loading homepage, so I can see metrics when I am in home. 

I can run a VPN tunnel which can solve this, but wanted to know if this can be possible. I searched wiki, issues for this, couldn't find it. 

Homepage (Cloud) -------------------- > Browser (in Home) ----------------------> Pi Hole (192.168.1.2)
                                                                   Ping, Metrics work

Homepage (Cloud)  -------------------- > Browser (outside Home) -----------X-----------> Pi Hole (192.168.1.2)
                                                          Ping, metrics Timeout (Expected)

Many thanks in advance.

**Comment by shamoon** [comment]
This is what a VPN is for essentially. Otherwise if you want to be able to access any server from outside its network you’re not going to be  able to use an internal IP (192.168…), of course.  It nothing would stop you from routing a request externally from the internet to your service. Just… be careful (or use a VPN :)

**Comment by shamoon** [comment]
Oh sorry, the other point here is homepage requests are proxied server-side, so they don’t come from your browser and no, that’s unlikely to change
