### ISSUE TITLE
Speedtest Error

### ISSUE THREAD

**Issue by hunkyn** [benphelps/homepage#83]
Hello,

I am using https://github.com/henrywhitaker3/Speedtest-Tracker for speedtest but the widget is not working and seems to error out.  Will this work with the widget in homepage? If not, is there a recommended speedtest that we can use.  Here is my information from the services.yaml for reference.

- Group C:
    - Speedtest:
        href: http://192.168.30.9:8765/
        description: Network Speeds
        widget:
          type: speedtest
          url: http://192.168.30.9:8765/

**Comment by hunkyn** [comment]
Actually, I have it correct when i pasted here it did not came out correctly. Funny thing this only happens in my Ipad same thing works and shows fine in my IPhone.

**Comment by benphelps** [comment]
Could it be that your iPad is connected to a different SSID that might not have access to the `192.168.1.0` network?

**Comment by benphelps** [comment]
> Could it be that your iPad is connected to a different SSID that might not have access to the `192.168.1.0` network?

Actually that shouldn't matter as of the changes made to how widget API calls function, never mind.

**Comment by hunkyn** [comment]
After a restart of services and it is now all good. Closing this issue.
