### ISSUE TITLE
[Feature Request] favicon of Website automatically displayed as the icon of the bookmark entry

### ISSUE THREAD

**Issue by Ainges** [benphelps/homepage#831]
### Description

Hi!

As mentioned in #786, I would love to see the favicon of the corresponding website used automatically as the icon for the bookmark entry.

Cheers!

**Comment by shamoon** [comment]
Closed as dupe

**Comment by Ainges** [comment]
I apologize

**Comment by shamoon** [comment]
Ha no worries mate :)
