### ISSUE TITLE
Docker status broken in 0.6.0

### ISSUE THREAD

**Issue by shamoon** [benphelps/homepage#849]
_Originally posted by @KillahB33 in https://github.com/benphelps/homepage/issues/848

**Comment by shamoon** [comment]
Pretty clearly related to #448, looking into this...

**Comment by KillahB33** [comment]
Agreed, I'll take a look myself in a bit. Also appears to be adding the kubernetes yaml (at least getting status message for it) on every container restart.

**Comment by shamoon** [comment]
I think this may only be for folks using docker sock, curious if others can confirm that.

I won't be able to dig into it until later (unless someone susses it out first 😉)

**Comment by KillahB33** [comment]
FOUND IT! And you were right it was #644 
It was permission on docker.sock, I thought cause you set it to ro that it wouldn't be an issue but I guess it is.
Added the pgid env to my setup with the same GID as the docker on the my main system.

**Comment by shamoon** [comment]
Yea Im reverting that one for now while we decide about how to release without breaking lots of installs =)

**Comment by KillahB33** [comment]
K cool. Found this thread.


https://github.com/portainer/portainer/issues/2744

**Comment by shamoon** [comment]
As far as I can tell the PR was always correct and Im going to re-merge it, if nothing is specified homepage runs as root and socket should work fine, sorry for confusion

**Comment by KillahB33** [comment]
Ok cool, sounds good!!
