### ISSUE TITLE
[Bug] Webpage constantly reloads with docker

### ISSUE THREAD

**Issue by cadegorawrz** [benphelps/homepage#853]
### Description

I've tried re-installing and different browsers. However everytime I go to <whateverip>:3000 the webpage immediately starts reloading!
![chrome_lx8aFhUd4S](https://user-images.githubusercontent.com/25090759/213859235-76add96e-cbd4-4b3e-ac00-ec8d7ce6655e.gif)

### Steps to reproduce

1. Run docker command provided on GitHub
2. Go to ip:3000
3. Watch reload forever

### homepage version

0.6.2

### Installation method

Docker

### Configuration

```yaml
docker run -p 3000 -v /app/config -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/benphelps/homepage:latest
```

### Container Logs

Listening on port 3000
[2023-01-21T08:30:07.076Z] error: undefined
[2023-01-21T08:30:07.136Z] info: docker.yaml was copied to the config folder
[2023-01-21T08:30:07.137Z] info: bookmarks.yaml was copied to the config folder
[2023-01-21T08:30:07.139Z] info: services.yaml was copied to the config folder
[2023-01-21T08:30:07.140Z] info: widgets.yaml was copied to the config folder
[2023-01-21T08:30:07.170Z] info: kubernetes.yaml was copied to the config folder

### Browser Logs

Kinda hard to get browser logs with it refreshing this much but I have tried on Chrome/Chrome Incognito, Firefox and Edge with the same result.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Can you post the content of your configs and try re-creating (not restating) the container

**Comment by cadegorawrz** [comment]
Update I've resolved the issue by setting the /app/config to /app/config:/app/config
