### ISSUE TITLE
[Bug] Proxy util (?) leaks memory.

### ISSUE THREAD

**Issue by supaflyster** [benphelps/homepage#854]
### Description

Hello!

i am running homepage in container, with several services and 2 widgets. I noticed that homepage container leaks about 2-3 MB RAM every 30 mins. I gather metrics with cadvisor.

<img width="1016" alt="Screenshot 2023-01-21 at 12 55 13" src="https://user-images.githubusercontent.com/6348312/213865726-b14365ac-24eb-4d4a-bde7-031f76e3ec27.png">

You can see how memory climbs up every few minutes. Even with browser page closed.

I have 2 widgets enabled that pull data from remote services: Adguard and Unifi.  
At 12.35 i disabled Adguard widget, and memory stopped leaking and stabilized at about 94Mb and even went down a little. 

Then i enabled it back at 12.57: 
It started leaking again.
<img width="472" alt="Screenshot 2023-01-21 at 13 01 38" src="https://user-images.githubusercontent.com/6348312/213865915-12cfadb4-f05a-48c1-a349-0e88badbd007.png">

Looking into both widgets code I noticed that Adguard uses proxy module from utils 
`import genericProxyHandler from "utils/proxy/handlers/generic";`
https://github.com/benphelps/homepage/blob/main/src/widgets/adguard/widget.js#L1

While Unifi uses it's own proxy - 
`import unifiProxyHandler from "./proxy";`
https://github.com/benphelps/homepage/blob/main/src/widgets/unifi/widget.js#L1

So i suspect that maybe proxy implementation in utils/proxy is actually leaking memory and not the plugin. But i might be mistaken, just assumptions. Not a JS developer, so can't really debug further into the code.

Hope you have time to look into this.

Thank you!

### Steps to reproduce

1. Add Adguard plugin with widget that pulls data from Adguard instance
2. Open dashboard once to initialize widget
3. Memory starts leaking

### homepage version

0.6.2

### Installation method

Docker

### Configuration

```yaml
- Adguard:
    href: http://adguard/
    description: Adguard home
    icon: adguard-home.png
    widget:
      type: adguard
      url: http://adguard/
      username: admin
      password: password
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Feel free to re-open if needed

<img width="731" alt="Screenshot 2023-04-04 at 11 56 01 PM" src="https://user-images.githubusercontent.com/4887959/230005912-062bbdcc-c984-48a5-82cd-e0388643ca5c.png">
