### ISSUE TITLE
[Feature Request] Add CPU Temp as a resource widget

### ISSUE THREAD

**Issue by mrvalterhugo** [benphelps/homepage#86]
Hi, first of all, thanks for creating this dashboard. It awesome.

I would like to ask if it's possible to add an extra widget showing the CPU temp.

Thank You.

**Comment by benphelps** [comment]
I'll look into this, good idea :)

**Comment by xicopitz** [comment]
Hi @benphelps @mrvalterhugo ,

I made some tests and came with this:
![image](https://user-images.githubusercontent.com/1280521/190262173-7be9a11f-8aad-414a-af5b-4e7b09e24332.png)

It's related to #68 too. 
The implementation dont need any aditional containers, only a npm package.

Both nvidia and amd icons are supported based on vendor information and if the npm package cant get the necessary information it displays something like: 
![image](https://user-images.githubusercontent.com/1280521/190263207-ac9b77ca-e112-4db4-adaf-16e3ba78b8d8.png)

I'm not a UI person, but is this interesting to submit ?

**Comment by alannssantos** [comment]
This is a really good idea, there any provision when we will gonna see this working?

**Comment by lsaadeh** [comment]
> Hi @benphelps @mrvalterhugo ,
> 
> I made some tests and came with this: ![image](https://user-images.githubusercontent.com/1280521/190262173-7be9a11f-8aad-414a-af5b-4e7b09e24332.png)
> 
> It's related to #68 too. The implementation dont need any aditional containers, only a npm package.
> 
> Both nvidia and amd icons are supported based on vendor information and if the npm package cant get the necessary information it displays something like: ![image](https://user-images.githubusercontent.com/1280521/190263207-ac9b77ca-e112-4db4-adaf-16e3ba78b8d8.png)
> 
> I'm not a UI person, but is this interesting to submit ?

how did you add your GPU?

**Comment by mattalat1** [comment]
Just wanted to say that I would love this feature as well!

**Comment by quentains** [comment]
I was looking for such a CPU temp feature. Can't wait to see it on my homepage.
