### ISSUE TITLE
[Feature Request] Unifi UDM Pro Support

### ISSUE THREAD

**Issue by NightShaman** [benphelps/homepage#862]
### Description

Appears the API locations are different between the UniFi controller and the UDM Pro/SE 
I am sure only a couple tweaks need to be made to the current implementation. I do not know python enough to do that. 

Looking at the API Docs here 
https://ubntwiki.com/products/software/unifi-controller/api

NOTE: There are two critical differences between Unifi controllers and the UDM Pro's API:

The login endpoint is /api/auth/login
All API endpoints need to be prefixed with /proxy/network (e.g. https://192.168.0.1/proxy/network/api/s/default/self)

If I add /proxy/network to the end of the widget url i no longer get a 404 error, but a 401. So I think it's not logging in correctly. 

### Other

I am more than willing to help test. May need a little direction on that. As using homepage through TrueNas SCALE.

**Comment by shamoon** [comment]
This has been discussed many times, I’m almost certain they are all supported and there is already code to detect this. Please have a look through previous issues / discussions.

**Comment by NightShaman** [comment]
Yep in commit comments. 

https://github.com/benphelps/homepage/issues/612#issuecomment-1336278877

Thanks, wouldn't think to look in that hole. Maybe in the Docs something noting that you have to reload the container would be helpful. 

Appreciate the help!
