### ISSUE TITLE
[Feature Request] Proxmox Service - LXC Templates Included In Count

### ISSUE THREAD

**Issue by themadman0980** [benphelps/homepage#864]
Just a minor thing, but the counter for LXC containers includes LXC templates. 

In my case, I have 1 template and 5 containers. In Homepage, this appears as 5 / 6 containers running. 

Could LXC templates be excluded from this counter? In my case this would mean a counter of 5 / 5.

**Comment by shamoon** [comment]
Please provide the output of your api endpoint `{url}/api2/json/cluster/resources`, if it can be derived there we can do this, otherwise we’ll change the label :)

(we try hard to minimized api calls so probably wouldn’t want to make one just for this)

**Comment by themadman0980** [comment]
Appreciate the guidance, however unfortunately I'm not very good with API and am struggling to get the auth ticket figured out. Not sure if anyone else is using Proxmox and could maybe chip in here?

There is always the API docs here, but I imagine the output is easier to work with...?

https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/resources

**Comment by JazzFisch** [comment]
> Appreciate the guidance, however unfortunately I'm not very good with API and am struggling to get the auth ticket figured out. Not sure if anyone else is using Proxmox and could maybe chip in here?
> 
> There is always the API docs here, but I imagine the output is easier to work with...?
> 
> https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/resources

I've got a Proxmox setup and will take a look @themadman0980.
