### ISSUE TITLE
[Bug] High CPU usage in Prowlarr when widget is enabled

### ISSUE THREAD

**Issue by SnowDrifterr** [benphelps/homepage#872]
### Description

I noted that Prowlarr has high CPU usage when the widget is enabled, and the home-page tab is selected/active in my browser

### Steps to reproduce

1. Install prowlarr
2. Configure widget
3. Navigate to homepage

### homepage version

0.6.3

### Installation method

Docker

### Other

Prowlarr v1.0.1.2220

Checked w/ the folks over at Prowlarr and they indicated I should file an issue here.

I have confirmed that CPU usage actually increases, and is not a reporting error

![image](https://user-images.githubusercontent.com/57574629/214379117-27b504b7-a0f6-4ac9-8a65-d8a6b554913e.png)

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Are you saying the 74% CPU on Prowlarr? I see no reason how that would be a homepage bug, homepage is just hitting the Prowlarr API, nothing else special...

**Comment by thezak48** [comment]
However you are hitting the indexerstats endpoint which is a known seriously compute intense endpoints

**Comment by shamoon** [comment]
> However you are hitting the indexerstats endpoint which is a known seriously compute intense endpoints

… So sounds like an improvement in efficiency that could be made on the Prowlarr side, if anything, no? (Not saying how likely or not that is)

**Comment by thezak48** [comment]
It is due to the DB access that is required, How often do you poll that endpoint?
