### ISSUE TITLE
[Feature Request] support svg dashboard-icons

### ISSUE THREAD

**Issue by IIIdefconIII** [benphelps/homepage#886]
### Description

png files are loaded lik github:
png works fine, but svg doesnt load.

- Homepage Github:
    icon:  github-light.png
    href: https://github.com/benphelps/homepage

### Steps to reproduce

Changing png to svg, the svg doesn't load while png does, why? cause svg is more faster in loading, more light weight

### homepage version

v0.6.3

### Installation method

Docker

### Configuration

```yaml
- Homepage Github:
    icon:  github-light.svg
    href: https://github.com/benphelps/homepage
```

### Container Logs

No errors about svg or icons

### Browser Logs

No errors. It just won't load svg icons

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
svg aren't supported, feel free to make a FR

**Comment by shamoon** [comment]
We can just make this the FR tbh, silly to open a new one

**Comment by IIIdefconIII** [comment]
cool, thank you

**Comment by IIIdefconIII** [comment]
thank you, loveley! here all working perfect

**Comment by JazzFisch** [comment]
> thank you, loveley! here all working perfect
> 
> only trashguide has been addes twice, im using the one with the dash in it -

Glad to hear it.  Closing since you have it working.
