### ISSUE TITLE
[Bug] Unifi Controller Uptime Incorrect

### ISSUE THREAD

**Issue by themadman0980** [benphelps/homepage#891]
### Description

System Uptime in the Unifi service is currently showing as 126.9 days. 

If I check in the Unifi interface, it tells me "System Uptime: 49min"

The LAN & WAN user counts are both correct. I'm assuming that it's either accidentally grabbing the wrong data point or incorrectly converting it?

Curiously, if I reboot the unifi controller the system uptime resumes in Homepage at the previous time of 126.9 days. Could it be some sort of running total, not the current uptime?

### Steps to reproduce

1. Add Unifi service to homepage
2. Check homepage web ui
3. See incorrect uptime

### homepage version

v0.6.2 (cdbdb86, Jan 21, 2023)

### Installation method

Docker

### Other

System Uptime in Unifi UI: ~49 mins

Response from /stat/sites:

```json
{
   "meta":{
      "rc":"ok"
   },
   "data":[
      {
         "_id":"63c5098408813b00f650309a",
         "anonymous_id":"6bb8e81f-d214-44ba-bb43-3812772e8a87",
         "name":"default",
         "desc":"Default",
         "attr_hidden_id":"default",
         "attr_no_delete":true,
         "health":[
            {
               "subsystem":"wlan",
               "num_user":9,
               "num_guest":0,
               "num_iot":0,
               "tx_bytes-r":11467,
               "rx_bytes-r":7868,
               "status":"ok",
               "num_ap":1,
               "num_adopted":1,
               "num_disabled":0,
               "num_disconnected":0,
               "num_pending":0
            },
            {
               "subsystem":"wan",
               "num_gw":1,
               "num_adopted":1,
               "num_disconnected":0,
               "num_pending":0,
               "status":"ok",
               "wan_ip":"192.168.0.134",
               "gateways":[
                  "192.168.0.1"
               ],
               "netmask":"255.255.255.0",
               "nameservers":[
                  "127.0.0.1"
               ],
               "num_sta":17,
               "tx_bytes-r":72936,
               "rx_bytes-r":2787794,
               "gw_mac":"74:ac:b9:18:81:c1",
               "gw_name":null,
               "gw_system-stats":{
                  "cpu":"0",
                  "mem":"28",
                  "uptime":"10970526"
               },
               "gw_version":"4.4.56.5449062",
               "uptime_stats":{
                  "WAN":{
                     "latency_average":69
                  }
               }
            },
            {
               "subsystem":"www",
               "status":"ok",
               "tx_bytes-r":72936,
               "rx_bytes-r":2787794,
               "latency":69,
               "uptime":6274,
               "drops":34,
               "xput_up":0.0,
               "xput_down":0.0,
               "speedtest_status":"Idle",
               "speedtest_lastrun":0,
               "speedtest_ping":0,
               "gw_mac":"74:ac:b9:18:81:c1"
            },
            {
               "subsystem":"lan",
               "lan_ip":"192.168.1.1",
               "status":"ok",
               "num_user":8,
               "num_guest":0,
               "num_iot":0,
               "tx_bytes-r":16133,
               "rx_bytes-r":1535,
               "num_sw":1,
               "num_adopted":1,
               "num_disconnected":0,
               "num_pending":0
            },
            {
               "subsystem":"vpn",
               "status":"unknown"
            }
         ],
         "num_new_alarms":0
      }
   ]
}
```

I believe the value being used for the uptime display is wan["gw_system-stats"].uptime / 86400.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
You are correct that's where its getting the uptime so that's what we use, don't see how we would do any better, its the value coming from the API, but I agree IM not clear exactly where that comes from

**Comment by shamoon** [comment]
Ps. I updated (and restarted) my UDMP yesterday and it correctly shows 0.6 today
<img width="150" alt="Screenshot 2023-01-28 at 2 57 42 PM" src="https://user-images.githubusercontent.com/4887959/215294957-7df0215e-3b1a-47a8-8e31-1abcbcfba092.png">

**Comment by themadman0980** [comment]
It might be my network tbh. I'm in a granny flat and there's a router downstream of my LAN so I don't know if the uptime stat for WAN might be different from uptime for the controller itself?
