### ISSUE TITLE
[Bug] Search widget

### ISSUE THREAD

**Issue by Nonoss117** [benphelps/homepage#915]
### Description

When I enter this word "MySearch" in the homepage search field and hit ENTER, I've got this following text in the new opened tab :
`Application error: a client-side exception has occurred (see the browser console for more information).`

and the url in my browser is :
`http://192.168.1.100:4000/[object%20Object]MySearch`

I'm using Firefox, but the result is the same with Brave and Microsoft Edge
The quick search is working fine, but the search is not working through the Homepage search field.
Did I miss anything in my configuration file ?

### Steps to reproduce

Type a word in homepage search field and hit ENTER

### homepage version

nightly (e411e2a, 2 févr. 2023)

### Installation method

Docker

### Configuration

```yaml
widgets.yaml


- search:
    provider: [brave, duckduckgo, google]
    target: _blank
    focus: false
```

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
> - search:
>     provider: [brave, duckduckgo, google]

Support for multiple providers hasn't been released yet

**Comment by Nonoss117** [comment]
Thank's for your reply shamoon, sorry I missed that.
