### ISSUE TITLE
Search function no longer works since v 0.6.5[Bug] 

### ISSUE THREAD

**Issue by Livefour2day** [benphelps/homepage#920]
### Description

Since upgrading to v0.6.5 the search function no longer works this includes Google, DuckDuckGo and my Custom search.

When using search it returns the following error - Application error: a client-side exception has occurred (see the browser console for more information).

### Steps to reproduce

type in search criteria, the results screen is Black with the error - Application error: a client-side exception has occurred (see the browser console for more information). 
There are no search results.

### homepage version

v0.6.5

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by Nonoss117** [comment]
May be this can help
https://github.com/benphelps/homepage/issues/915

**Comment by fate8383** [comment]
nope it is just broken, it was working version before.

**Comment by shamoon** [comment]
Thanks, fixed in 0.6.6

**Comment by Livefour2day** [comment]
Thank you shamoon that fixed it.
