### ISSUE TITLE
[Bug] Google search not working since 0.6.5

### ISSUE THREAD

**Issue by robergej** [benphelps/homepage#921]
### Description

Web search does not work since 0.6.5, instead of a Google search, browser shows this error on an otherwise blank page:

Application error: a client-side exception has occurred (see the browser console for more information).

### Steps to reproduce

Open homepage. Type something in search bar. Hit enter.

### homepage version

0.6.5

### Installation method

Docker

### Configuration

```yaml
in widgets.yaml:
- search:
    provider: google
    focus: true
    target: _self
```

### Container Logs

No relevant logs

### Browser Logs

GET https://{domain-omitted}/[object%20Object]query 404

The [object%20Object] part seems to not be set right

### Other

The google search actually works when typing somewhere else on the Homepage Screen, and the search pops up, then I click "Google Search" and it works. But using the search field does not work.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by Nonoss117** [comment]
May be this can help: 
https://github.com/benphelps/homepage/issues/915

**Comment by robergej** [comment]
> May be this can help: #915

That person had multiple search providers listed in their widgets.yaml. I only have google in mine. It is the same error I am seeing tough.

**Comment by robergej** [comment]
duplicate of [](url)

**Comment by Nonoss117** [comment]
I'm this person, and I've tried with only one provider, same result.

**Comment by robergej** [comment]
Ok so it's the same issue
