### ISSUE TITLE
Update made me lose my configuration

### ISSUE THREAD

**Issue by 2ndwonder** [benphelps/homepage#93]
The new update made me lose my services.. I don't want to add labels in docker-compose. how can I fix this?

**Comment by 2ndwonder** [comment]
I went back to v0.3.7 en disabled Pullio (auto update) for now.. hope you can fix this in the next update for users who still want to use services.yaml

**Comment by CameronMacG** [comment]
Yeah i've just had this as well. Little annoyed that i've spent a good number of hours getting everything how I wanted it to be, however, just created a new container to see what I can do.

**Comment by 2ndwonder** [comment]
You can go back to v0.3.7 and your services yaml will work again

**Comment by xenogear74** [comment]
If you comment out mydocker in the docker yaml and the other-docker then the configuration loads correctly.

**Comment by tweek11** [comment]
Appreciate the heads up on commenting out the two lines in the docker file. I was scratching my head and wondering. Also noticed that after the update it added a letter D the following to the services.yaml "http://localhosdt/" - assuming its a typo to the default file and edited it to reflect the documentation via the wiki to "http://localhost/"

**Comment by 2ndwonder** [comment]
> If you comment out mydocker in the docker yaml and the other-docker then the configuration loads correctly.

if you do this, you won't be able to see the docker container information anymore. correct?

**Comment by benphelps** [comment]
This has been fixed.

The issue was caused by having an invalid docker host configured in your `docker.yaml` file, which would often be the case because of the two examples given.  If you had not removed the examples, service discovery would fail and cause services to not load.
