### ISSUE TITLE
[Feature Request] Pterodactyl Panel

### ISSUE THREAD

**Issue by BeeTwenty** [benphelps/homepage#930]
### Description

would love to have a widget like for pterodactyl panel 

showing servers, servers online/offline etc..

**Comment by Oupsman** [comment]
I'm working on something :

<img width="1240" alt="Capture d’écran 2023-02-16 à 13 24 24" src="https://user-images.githubusercontent.com/11260343/219363988-7e18d45c-2549-4951-8801-52c877166386.png">

Right now, I'm struggling to get nodes status (is the node online or not), but the servers status seems to work quite well.
