### ISSUE TITLE
[Bug] Proxmox Backup Server widget is too big when the server is down.

### ISSUE THREAD

**Issue by Krafting** [benphelps/homepage#933]
### Description

Hello,
I just found out about the PBS widgets so I wanted to give it a shot! 

However, when my PBS server is down, instead of showing the default texts with just dashes "-", like the others widgets,  the text of the second module is too big, and instead of having four column, one of them is pushed down, making it a three columns instead of 4. 

After a few seconds it goes away and show the "API error" thingy, but it's a bit annoying as it should not be how it behave by default, is there a language issue ?

Normal view:
![image](https://user-images.githubusercontent.com/36538123/216674155-4277051e-7424-46df-abe9-414f2c43a65a.png)

When the server is not responding:
![image](https://user-images.githubusercontent.com/36538123/216674271-bf5676f8-987d-4a71-a205-7fb6d9a46b00.png)

### Steps to reproduce

Add PBS widget
Turn off PBS
Load Homepage

### homepage version

main (2fae4ac, Feb 3, 2023)

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Thanks, will be fixed in the next release
