### ISSUE TITLE
[Feature Request] S.M.A.R.T. HDDs parameters

### ISSUE THREAD

**Issue by giacomocerquone** [benphelps/homepage#938]
### Description

Great job on this project.
I'm planning to use this tool on my custom home NAS and I'd like to see smart HDD params of all my drives.

**Comment by DanBrezeanu** [comment]
@giacomocerquone 

You can use a S.M.A.R.T. monitoring service such as [Scrutiny](https://github.com/AnalogJ/scrutiny). Homepage has available widgets for this service.

![image](https://user-images.githubusercontent.com/33134460/226737766-3afd854a-2e5a-4122-98c2-c5170c5d3cf0.png)

**Comment by giacomocerquone** [comment]
thank you, much appreciated
