### ISSUE TITLE
[Feature Request] Improve gethomepage.dev search indexing frequency

### ISSUE THREAD

**Issue by moritz-john** [benphelps/homepage#952]
### Description

I noticed that the search function on gethomepage.dev is almost unusable for some search queries.
I use the search in the documentation after a new homepage version gets released to inform myself about new features.

### Steps to reproduce

1) Checkout new [release  v0.6.5](https://github.com/benphelps/homepage/releases/tag/v0.6.5)
2) Read e.g.: "Feature: **Custom CSS** by @lholota in https://github.com/benphelps/homepage/pull/904"
3) Go to https://gethomepage.dev/en/installation/ and search for the keyword `"CSS"`
![image](https://user-images.githubusercontent.com/70295002/217074168-01bc7a37-f2ac-461a-9ba5-7f2184710e57.png)
4) Find absolutley nothing related to the keyword `"CSS"`

I'd expect to find this result: https://gethomepage.dev/en/configs/settings/#custom-css

### Other

Tested in Firefox and Ungoogled Chromium.

I noticed that this happens almost every time a new feature / configuration gets released.
I can never find the new feature / configuration in the documentation via the search.

I think something is missconfigured or the search index outdated.

___

Thank you for creating this awesome application!

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Im not sure of the frequency but the docs are scraped periodically by the algolia crawler, there is no configuration problem

Agree its annoying that doesn't show up (yet?)

https://docsearch.algolia.com

**Comment by shamoon** [comment]
We can double-check the crawler

**Comment by moritz-john** [comment]
https://docsearch.algolia.com/docs/what-is-docsearch/#quick-description

> Crawls are handled by the [Algolia Crawler](https://www.algolia.com/products/search-and-discovery/crawler/) and scheduled to run once a week by default, **you can then trigger new crawls yourself** [...]

I think it would be awesome to manually trigger the crawler for each release.

**Comment by moritz-john** [comment]
> Actually, we will double-check the crawler

Thank you!

**Comment by shamoon** [comment]
Yea eg https://github.com/marketplace/actions/algolia-crawler-automatic-crawl

**Comment by shamoon** [comment]
Thanks, the crawler was updated and should run every 24h now, which should be sufficient.

**Comment by shamoon** [comment]
Ps. just realized custom css doesn't work as-is, its going to be reverted =/

**Comment by moritz-john** [comment]
> Thanks, the crawler was updated and should run every 24h now, which should be sufficient.

Fantastic, thank you for your work!
