### ISSUE TITLE
[Bug] Homepage leaks API keys

### ISSUE THREAD

**Issue by Tokukarin** [benphelps/homepage#961]
### Description

Homepage leaks API keys when it is unable to make a request.
This leads to other people being able to abuse the API key as they wish, and maybe putting you into debt real fast.

![2023-02-08_08-41](https://user-images.githubusercontent.com/50606374/217466839-b8973e70-f8e4-41f1-ada6-e01120f1ad8e.png)

### Steps to reproduce

Block connection to Openweathermap with Firewall/DNS or whatever.

### homepage version

all

### Installation method

Docker

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
You can use `providers` to avoid this: https://gethomepage.dev/en/configs/settings/#providers
