### ISSUE TITLE
[Feature Request] Healthchecks.io Integration/Widget

### ISSUE THREAD

**Issue by ilovepancakes95** [benphelps/homepage#965]
### Description

Being able to display service status tracked through healthchecks.io platform would be great. They do offer an API so would imagine it would be fairly straightforward to add the ability to pull service status reported into the homepage. Kind of like the implementation Organizr offers.

Love the look of this homepage project and can't wait to use it.

**Comment by rommelkott** [comment]
Working on an implementation. 👍
