### ISSUE TITLE
[Feature Request] - Plans for other service widgets

### ISSUE THREAD

**Issue by hunkyn** [benphelps/homepage#97]
Hello,

Are there any plans for enhancements for other service widgets in the future?  Looking for widgets like Jackett, qBittorent etc. If there is a list that is actively maintained, I am happy to add to the list.

**Comment by benphelps** [comment]
There are lots of plans for future service widgets.  I use Issues and Discussions to track requests, so feel free to make a new request for each integration you'd like to see.
