### ISSUE TITLE
Swarm Mode

### ISSUE THREAD

**Issue by rdavey228** [benphelps/homepage#970]
Hi,

I have swarm mode setup as per the instruction manual 

```
docker-swarm:
  socket: /var/run/docker.sock
  swarm: true
```

I then reference the Server and the Service name under my service.

This works, but only when the service I'm referencing is on the same node as the dashboard container.

For example, I have a 3 node swarm cluster.

The dashboard service sits on Node 1
Adguard is also on Node 1
Unifi is on node 2

The dashboard will only show Adguard as healthy/online as its on the same node as the dashboard service.

Unifi container shows as Unknown as its on another node.

If I force Unifi onto the same node as the dashboard service it shows as available.

So.....am I doing something wrong here? Shouldn't this work across all nodes? Or have I setup the Docker service wrong in the config?

**Comment by Bijorn** [comment]
I have the same issue with a 3 nodes cluster. Only the service on the same node work with the running status. All others are show as Unknown

**Comment by shamoon** [comment]
@vinaydawani any thoughts here? I don't have swarm setup (and its not so trivial to setup multi-node without multiple linux machines)

**Comment by shamoon** [comment]
I messed around with this a bit and think I have a partial fix, but it is worth noting that if you are deploying standalone containers on a different node then that won't work, that is from docker. As in, if you run `docker node ps xxx` from the manger you only see containers that are part of a swarm service. I think this may be what you both are describing.

But there is an issue that could also be relevant, see #994

**Comment by rdavey228** [comment]
> I messed around with this a bit and think I have a partial fix, but it is worth noting that if you are deploying standalone containers on a different node then that won't work, that is from docker. As in, if you run `docker node ps xxx` from the manger you only see containers that are part of a swarm service. I think this may be what you both are describing.
> 
> But there is an issue that could also be relevant, see #994

My containers aren't standalone containers. Whilst yes only one copy of the container exists it is still part of the swam as a service, so if I took a node down it would re create automatically on another node. It's not deployed as a standalone container fixed to a specific node.

You can't tell me this swam monitor requires that your container is published across all your nodes just to make sure it ends up on the same node the dashboard is sitting on so that the monitor works, or have the dashboard published to all nodes. Thats just nuts. Not every container needs multiple replicas.

**Comment by shamoon** [comment]
If it's part of a service then I think this PR will improve things with respect to the status but not for the stats. Again, Im not super well-versed in swarm but Im not clear if it's even possible to get remote container stats from the swarm manager host (via the API). This software uses https://github.com/apocas/dockerode, which itself mostly just uses the docker API. I couldn't find any documentation to directly address this but I think that's a limitation of either docker API or perhaps this dependency.

Not sure if you're able to test the PR but again, I believe would help
