### ISSUE TITLE
I use docker compose deploy, but cant request service api

### ISSUE THREAD

**Issue by fireinrain** [benphelps/homepage#98]
<img width="1637" alt="image" src="https://user-images.githubusercontent.com/14249262/189510004-0994e4ed-695f-4ecc-a12f-3fa02bc5a860.png">

**Comment by fireinrain** [comment]
should I need run node in local machine ?   I see the docker container log, it said that  cant connect to node @ port xxxx.
is that the problem?  hope you can help. thanks

**Comment by benphelps** [comment]
This has been fixed in the latest tag, sorry for the hiccup.

**Comment by benphelps** [comment]
> should I need run node in local machine ? I see the docker container log, it said that cant connect to node @ port xxxx. is that the problem? hope you can help. thanks

It all depends on how you want to setup Homepage, you can read more here about Docker integration: https://github.com/benphelps/homepage/wiki/Docker-Integration

**Comment by fireinrain** [comment]
> > should I need run node in local machine ? I see the docker container log, it said that cant connect to node @ port xxxx. is that the problem? hope you can help. thanks
> 
> It all depends on how you want to setup Homepage, you can read more here about Docker integration: https://github.com/benphelps/homepage/wiki/Docker-Integration

thank, I will give a try.
