### ISSUE TITLE
[Feature Request] Add a 5th column for ultra wide screens

### ISSUE THREAD

**Issue by IIIdefconIII** [benphelps/homepage#987]
### Description

Is it possible to add a 5fth catagorie colum? would be lovely on a ultra wide screen

![image](https://user-images.githubusercontent.com/9917659/221219089-b4a1acdc-aa89-4d2c-b063-7112bdbe8f47.png)
### Other

i know there is a css trick, but that shows them all together on a single line and isnt persisstant.
is it possible to make the .flex-wrap side larger? with flex.wrap disabled, its make it too huge:
![image](https://user-images.githubusercontent.com/9917659/221220335-670de34e-acd6-4df5-9fa2-23f9f2ffaba3.png)
![image](https://user-images.githubusercontent.com/9917659/221222191-b7b254fd-b464-4af3-9f8b-c3a07e69eae7.png)

**Comment by IIIdefconIII** [comment]
Only solution so far was use less headers so i now have it like this:

![image](https://user-images.githubusercontent.com/9917659/218284356-028cdd1f-0cb3-40a2-a285-5f61c707c0ae.png)

**Comment by IIIdefconIII** [comment]
Only solution so far was use less headers so i now have it like this:


![image](https://user-images.githubusercontent.com/9917659/218285874-b3fc34a7-5d07-4e95-9ad6-0259fd19766c.png)

**Comment by IIIdefconIII** [comment]
i know there is a css trick, but that shows them all together on a single line

**Comment by IIIdefconIII** [comment]
bump

**Comment by shamoon** [comment]
Please keep comments to ones that add information to the request, "+1" or "bump" comments are kinda just spamming everyone subscribed. Thanks

**Comment by IIIdefconIII** [comment]
> Hello.
> I'd suggest instead adding a 5th column, to be more flexible with columns and let the user decide how many columns they would like. I might need only 3 columns, or 7.
> Should I open a new ticket or this comment is enough to "improve" this request?

That would be nice. This ticket it open for a little while now so I'm wondering is a new request is better. Tag me in if you do. Thanks
