### ISSUE TITLE
No longer accepting config/layout

### ISSUE THREAD

**Issue by kBraDrs** [benphelps/homepage#99]
Hello,

My homepage was working fine until an update  in the recent hours.
I have put my code below.

- Containers:
    - Influxdb:
        icon: https://assets.zabbix.com/img/brands/influxdb.svg
        href: http://192.168.68.130:8086/
        description: Multi-purpose database
    - Overseerr:
        icon: https://user-images.githubusercontent.com/1066576/125193232-b41d8900-e28e-11eb-801b-3b643f672536.png
        href: http://192.168.68.130:5055/
        description: Plex Management
    - Radarr:
        icon: https://www.pngitem.com/pimgs/m/403-4036901_radarr-logo-hd-png-download.png
        href: http://192.168.68.130:7878/
        description: Movie Management
    - Speedtest Tracker:
        icon: https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/Grafana_logo.svg/1200px-Grafana_logo.svg.png
        href: http://192.168.68.130:3010/d/SA4N7cCnz/speedtest-tracker-influxdbv2?orgId=1&from=now-7d&to=now&refresh=2h
        description: Internet Speedtest Monitor
    - Tautulli:
        icon: https://tautulli.com/images/logo-circle.png
        href: http://192.168.68.130:8181/home
        description: Plex  Monitoring
        widget:
          type: tautulli
          url: http://192.168.68.130:8181
          key: 08abddb79f2449e7b50d738aab4b71e4

- Applications:
    - NAS:
        icon: https://cdn-icons-png.flaticon.com/512/2972/2972479.png
        href: http://192.168.68.130:5000
        description: Synology desktop
    - Plex:
        icon: https://images-na.ssl-images-amazon.com/images/I/61-kdNZrX9L.png
        href: http://192.168.68.130:32400/web/index.html#!/
        description: Video Streaming Service
    - Transmission:
        icon: https://transmissionbt.com/assets/images/Transmission_icon.png
        href: http://192.168.68.130:9091/transmission/web/
        description: Torrent Downloading Software

This was working fine, now I get the below screenshot.

![image](https://user-images.githubusercontent.com/102444317/189511732-44010bf2-0592-4c72-bc06-fb9e9574dbf5.png)

The bookmarks have dissapeared.

Any help?

**Comment by kBraDrs** [comment]
Note: The bullet points are hyphens '-' but GitHub defaults these to points.

My services have disappeared, the boomarks are correct and also the widgets at the top of the page.

**Comment by benphelps** [comment]
This is usually due to a format error in your YAML file.

**Comment by kBraDrs** [comment]
Strange how it just randomly occurred without me changing anything.

**Comment by iamdangry** [comment]
Also have this issue with the latest release v0.3.9. Rolled back to v0.3.7 and everything came back

**Comment by iamdangry** [comment]
Ahhh ok, it is a yaml config issue as @benphelps said.

I don't have the Docker API exposed and I still had the Docker API config in the docker.yaml file which is placed there by default. I'd never looked at this file, my own fault for skimming through the Wiki. After removing it, everything went back to normal. Also helpful if I looked at the logs for the container which told me this

**Comment by benphelps** [comment]
> Ahhh ok, it is a yaml config issue as @benphelps said.
> 
> I don't have the Docker API exposed and I still had the Docker API config in the docker.yaml file which is placed there by default. I'd never looked at this file, my own fault for skimming through the Wiki. After removing it, everything went back to normal. Also helpful if I looked at the logs for the container which told me this

This has been fixed in the latest release as well, in either case.
