### ISSUE TITLE
[Feature Request] Replace speedtest service

### ISSUE THREAD

**Issue by myhrmans** [benphelps/homepage#996]
### Description

Hi there,

I wanted to give you a heads up that the henrywhitaker3/Speedtest-Tracker repository is no longer being maintained, as mentioned in [this issue](https://github.com/henrywhitaker3/Speedtest-Tracker/issues/1104). It would be great to have an alternative service for checking connection speed on the homepage.

One option you might consider is this fork [alexjustesen/speedtest-tracker](https://github.com/alexjustesen/speedtest-tracker). This could provide similar functionality to henrywhitaker3/Speedtest-Tracker, and might be a good replacement.

**Comment by shamoon** [comment]
I don’t have a link on hand, but this has been discussed multiple times. If you search the previous issues you’ll see that repository doesn’t have any kind of API available yet. But sure if things stabilize and it does get implemented, it would be a good idea to make a new widget.
